// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_specs.sql

package sqlc

import (
	"context"
)

const countActiveAPISpecsByRepo = `-- name: CountActiveAPISpecsByRepo :one
SELECT COUNT(*)::BIGINT
FROM api_specs
WHERE repo_id = $1
  AND status = 'active'
`

func (q *Queries) CountActiveAPISpecsByRepo(ctx context.Context, repoID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAPISpecsByRepo, repoID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAPISpecRevision = `-- name: CreateAPISpecRevision :one
INSERT INTO api_spec_revisions (
    api_spec_id,
    revision_id,
    root_path_at_revision,
    build_status,
    error
)
SELECT
    $1,
    $2,
    api_specs.root_path,
    $3,
    $4
FROM api_specs
WHERE api_specs.id = $1
ON CONFLICT (api_spec_id, revision_id) DO UPDATE
SET root_path_at_revision = EXCLUDED.root_path_at_revision,
    build_status = EXCLUDED.build_status,
    error = EXCLUDED.error,
    updated_at = NOW()
RETURNING id, api_spec_id, revision_id, root_path_at_revision, build_status, error, created_at, updated_at
`

type CreateAPISpecRevisionParams struct {
	ApiSpecID   int64  `json:"api_spec_id"`
	RevisionID  int64  `json:"revision_id"`
	BuildStatus string `json:"build_status"`
	Error       string `json:"error"`
}

func (q *Queries) CreateAPISpecRevision(ctx context.Context, arg CreateAPISpecRevisionParams) (ApiSpecRevision, error) {
	row := q.db.QueryRow(ctx, createAPISpecRevision,
		arg.ApiSpecID,
		arg.RevisionID,
		arg.BuildStatus,
		arg.Error,
	)
	var i ApiSpecRevision
	err := row.Scan(
		&i.ID,
		&i.ApiSpecID,
		&i.RevisionID,
		&i.RootPathAtRevision,
		&i.BuildStatus,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const replaceAPISpecDependencies = `-- name: ReplaceAPISpecDependencies :exec
WITH replaced AS (
    DELETE FROM api_spec_dependencies
    WHERE api_spec_revision_id = $1
)
INSERT INTO api_spec_dependencies (
    api_spec_revision_id,
    file_path
)
SELECT
    $1,
    dependency_path
FROM UNNEST($2::TEXT[]) AS dependency_path
ON CONFLICT (api_spec_revision_id, file_path) DO NOTHING
`

type ReplaceAPISpecDependenciesParams struct {
	ApiSpecRevisionID int64    `json:"api_spec_revision_id"`
	FilePaths         []string `json:"file_paths"`
}

func (q *Queries) ReplaceAPISpecDependencies(ctx context.Context, arg ReplaceAPISpecDependenciesParams) error {
	_, err := q.db.Exec(ctx, replaceAPISpecDependencies, arg.ApiSpecRevisionID, arg.FilePaths)
	return err
}

const upsertAPISpec = `-- name: UpsertAPISpec :one
INSERT INTO api_specs (
    repo_id,
    root_path,
    status
)
VALUES (
    $1,
    $2,
    'active'
)
ON CONFLICT (repo_id, root_path) DO UPDATE
SET status = 'active',
    updated_at = NOW()
RETURNING id, repo_id, root_path, status, display_name, created_at, updated_at
`

type UpsertAPISpecParams struct {
	RepoID   int64  `json:"repo_id"`
	RootPath string `json:"root_path"`
}

func (q *Queries) UpsertAPISpec(ctx context.Context, arg UpsertAPISpecParams) (ApiSpec, error) {
	row := q.db.QueryRow(ctx, upsertAPISpec, arg.RepoID, arg.RootPath)
	var i ApiSpec
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.RootPath,
		&i.Status,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
