// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_specs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAPISpecsByRepo = `-- name: CountActiveAPISpecsByRepo :one
SELECT COUNT(*)::BIGINT
FROM api_specs
WHERE repo_id = $1
  AND status = 'active'
`

func (q *Queries) CountActiveAPISpecsByRepo(ctx context.Context, repoID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAPISpecsByRepo, repoID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAPISpecRevision = `-- name: CreateAPISpecRevision :one
INSERT INTO api_spec_revisions (
    api_spec_id,
    revision_id,
    root_path_at_revision,
    build_status,
    error
)
SELECT
    $1,
    $2,
    api_specs.root_path,
    $3,
    $4
FROM api_specs
WHERE api_specs.id = $1
ON CONFLICT (api_spec_id, revision_id) DO UPDATE
SET root_path_at_revision = EXCLUDED.root_path_at_revision,
    build_status = EXCLUDED.build_status,
    error = EXCLUDED.error,
    updated_at = NOW()
RETURNING id, api_spec_id, revision_id, root_path_at_revision, build_status, error, created_at, updated_at
`

type CreateAPISpecRevisionParams struct {
	ApiSpecID   int64  `json:"api_spec_id"`
	RevisionID  int64  `json:"revision_id"`
	BuildStatus string `json:"build_status"`
	Error       string `json:"error"`
}

func (q *Queries) CreateAPISpecRevision(ctx context.Context, arg CreateAPISpecRevisionParams) (ApiSpecRevision, error) {
	row := q.db.QueryRow(ctx, createAPISpecRevision,
		arg.ApiSpecID,
		arg.RevisionID,
		arg.BuildStatus,
		arg.Error,
	)
	var i ApiSpecRevision
	err := row.Scan(
		&i.ID,
		&i.ApiSpecID,
		&i.RevisionID,
		&i.RootPathAtRevision,
		&i.BuildStatus,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPISpecListingByRepo = `-- name: ListAPISpecListingByRepo :many
WITH repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $1
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.revision_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, api_spec_revisions.revision_id DESC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    latest_processed.api_spec_revision_id,
    ingest_events.id AS revision_id,
    ingest_events.sha AS revision_sha,
    ingest_events.branch AS revision_branch
FROM repo_specs
LEFT JOIN latest_processed ON latest_processed.api_spec_id = repo_specs.id
LEFT JOIN ingest_events ON ingest_events.id = latest_processed.revision_id
ORDER BY repo_specs.root_path ASC
`

type ListAPISpecListingByRepoRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID pgtype.Int8 `json:"api_spec_revision_id"`
	RevisionID        pgtype.Int8 `json:"revision_id"`
	RevisionSha       pgtype.Text `json:"revision_sha"`
	RevisionBranch    pgtype.Text `json:"revision_branch"`
}

func (q *Queries) ListAPISpecListingByRepo(ctx context.Context, targetRepoID int64) ([]ListAPISpecListingByRepoRow, error) {
	rows, err := q.db.Query(ctx, listAPISpecListingByRepo, targetRepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPISpecListingByRepoRow{}
	for rows.Next() {
		var i ListAPISpecListingByRepoRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.RevisionID,
			&i.RevisionSha,
			&i.RevisionBranch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAPISpecsWithLatestDependencies = `-- name: ListActiveAPISpecsWithLatestDependencies :many
WITH active_specs AS (
    SELECT id, repo_id, root_path, status, display_name, created_at, updated_at
    FROM api_specs
    WHERE repo_id = $1
      AND status = 'active'
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.id,
        api_spec_revisions.api_spec_id
    FROM api_spec_revisions
    JOIN active_specs ON active_specs.id = api_spec_revisions.api_spec_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, api_spec_revisions.revision_id DESC, api_spec_revisions.id DESC
)
SELECT
    active_specs.id,
    active_specs.repo_id,
    active_specs.root_path,
    active_specs.status,
    active_specs.display_name,
    active_specs.created_at,
    active_specs.updated_at,
    COALESCE(dependencies.dependency_paths, ARRAY[]::TEXT[])::TEXT[] AS dependency_paths
FROM active_specs
LEFT JOIN latest_processed ON latest_processed.api_spec_id = active_specs.id
LEFT JOIN LATERAL (
    SELECT ARRAY_AGG(api_spec_dependencies.file_path ORDER BY api_spec_dependencies.file_path)::TEXT[] AS dependency_paths
    FROM api_spec_dependencies
    WHERE api_spec_dependencies.api_spec_revision_id = latest_processed.id
) AS dependencies ON TRUE
ORDER BY active_specs.root_path ASC
`

type ListActiveAPISpecsWithLatestDependenciesRow struct {
	ID              int64              `json:"id"`
	RepoID          int64              `json:"repo_id"`
	RootPath        string             `json:"root_path"`
	Status          string             `json:"status"`
	DisplayName     pgtype.Text        `json:"display_name"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DependencyPaths []string           `json:"dependency_paths"`
}

func (q *Queries) ListActiveAPISpecsWithLatestDependencies(ctx context.Context, repoID int64) ([]ListActiveAPISpecsWithLatestDependenciesRow, error) {
	rows, err := q.db.Query(ctx, listActiveAPISpecsWithLatestDependencies, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAPISpecsWithLatestDependenciesRow{}
	for rows.Next() {
		var i ListActiveAPISpecsWithLatestDependenciesRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.RootPath,
			&i.Status,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DependencyPaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAPISpecDeleted = `-- name: MarkAPISpecDeleted :execrows
UPDATE api_specs
SET status = 'deleted',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkAPISpecDeleted(ctx context.Context, apiSpecID int64) (int64, error) {
	result, err := q.db.Exec(ctx, markAPISpecDeleted, apiSpecID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replaceAPISpecDependencies = `-- name: ReplaceAPISpecDependencies :exec
WITH replaced AS (
    DELETE FROM api_spec_dependencies
    WHERE api_spec_revision_id = $1
)
INSERT INTO api_spec_dependencies (
    api_spec_revision_id,
    file_path
)
SELECT
    $1,
    dependency_path
FROM UNNEST($2::TEXT[]) AS dependency_path
ON CONFLICT (api_spec_revision_id, file_path) DO NOTHING
`

type ReplaceAPISpecDependenciesParams struct {
	ApiSpecRevisionID int64    `json:"api_spec_revision_id"`
	FilePaths         []string `json:"file_paths"`
}

func (q *Queries) ReplaceAPISpecDependencies(ctx context.Context, arg ReplaceAPISpecDependenciesParams) error {
	_, err := q.db.Exec(ctx, replaceAPISpecDependencies, arg.ApiSpecRevisionID, arg.FilePaths)
	return err
}

const upsertAPISpec = `-- name: UpsertAPISpec :one
INSERT INTO api_specs (
    repo_id,
    root_path,
    status
)
VALUES (
    $1,
    $2,
    'active'
)
ON CONFLICT (repo_id, root_path) DO UPDATE
SET status = 'active',
    updated_at = NOW()
RETURNING id, repo_id, root_path, status, display_name, created_at, updated_at
`

type UpsertAPISpecParams struct {
	RepoID   int64  `json:"repo_id"`
	RootPath string `json:"root_path"`
}

func (q *Queries) UpsertAPISpec(ctx context.Context, arg UpsertAPISpecParams) (ApiSpec, error) {
	row := q.db.QueryRow(ctx, upsertAPISpec, arg.RepoID, arg.RootPath)
	var i ApiSpec
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.RootPath,
		&i.Status,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
