// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cli_reads.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findOperationCandidatesByRepoRevisionAndAPIAndMethodPath = `-- name: FindOperationCandidatesByRepoRevisionAndAPIAndMethodPath :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $3
      AND ingest_events.id = $4
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $3
      AND api_specs.root_path = $5
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed
JOIN repo_specs ON repo_specs.id = latest_processed.api_spec_id
JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
WHERE endpoint_index.method = $1
  AND endpoint_index.path = $2
ORDER BY endpoint_index.method ASC, endpoint_index.path ASC
`

type FindOperationCandidatesByRepoRevisionAndAPIAndMethodPathParams struct {
	Method             string `json:"method"`
	Path               string `json:"path"`
	RepoID             int64  `json:"repo_id"`
	SnapshotRevisionID int64  `json:"snapshot_revision_id"`
	Api                string `json:"api"`
}

type FindOperationCandidatesByRepoRevisionAndAPIAndMethodPathRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) FindOperationCandidatesByRepoRevisionAndAPIAndMethodPath(ctx context.Context, arg FindOperationCandidatesByRepoRevisionAndAPIAndMethodPathParams) ([]FindOperationCandidatesByRepoRevisionAndAPIAndMethodPathRow, error) {
	rows, err := q.db.Query(ctx, findOperationCandidatesByRepoRevisionAndAPIAndMethodPath,
		arg.Method,
		arg.Path,
		arg.RepoID,
		arg.SnapshotRevisionID,
		arg.Api,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindOperationCandidatesByRepoRevisionAndAPIAndMethodPathRow{}
	for rows.Next() {
		var i FindOperationCandidatesByRepoRevisionAndAPIAndMethodPathRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOperationCandidatesByRepoRevisionAndAPIAndOperationID = `-- name: FindOperationCandidatesByRepoRevisionAndAPIAndOperationID :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $2
      AND ingest_events.id = $3
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $2
      AND api_specs.root_path = $4
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed
JOIN repo_specs ON repo_specs.id = latest_processed.api_spec_id
JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
WHERE endpoint_index.operation_id = $1
ORDER BY endpoint_index.method ASC, endpoint_index.path ASC
`

type FindOperationCandidatesByRepoRevisionAndAPIAndOperationIDParams struct {
	OperationID        pgtype.Text `json:"operation_id"`
	RepoID             int64       `json:"repo_id"`
	SnapshotRevisionID int64       `json:"snapshot_revision_id"`
	Api                string      `json:"api"`
}

type FindOperationCandidatesByRepoRevisionAndAPIAndOperationIDRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) FindOperationCandidatesByRepoRevisionAndAPIAndOperationID(ctx context.Context, arg FindOperationCandidatesByRepoRevisionAndAPIAndOperationIDParams) ([]FindOperationCandidatesByRepoRevisionAndAPIAndOperationIDRow, error) {
	rows, err := q.db.Query(ctx, findOperationCandidatesByRepoRevisionAndAPIAndOperationID,
		arg.OperationID,
		arg.RepoID,
		arg.SnapshotRevisionID,
		arg.Api,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindOperationCandidatesByRepoRevisionAndAPIAndOperationIDRow{}
	for rows.Next() {
		var i FindOperationCandidatesByRepoRevisionAndAPIAndOperationIDRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOperationCandidatesByRepoRevisionAndMethodPath = `-- name: FindOperationCandidatesByRepoRevisionAndMethodPath :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $3
      AND ingest_events.id = $4
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $3
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed
JOIN repo_specs ON repo_specs.id = latest_processed.api_spec_id
JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
WHERE endpoint_index.method = $1
  AND endpoint_index.path = $2
ORDER BY repo_specs.root_path ASC, endpoint_index.method ASC, endpoint_index.path ASC
`

type FindOperationCandidatesByRepoRevisionAndMethodPathParams struct {
	Method             string `json:"method"`
	Path               string `json:"path"`
	RepoID             int64  `json:"repo_id"`
	SnapshotRevisionID int64  `json:"snapshot_revision_id"`
}

type FindOperationCandidatesByRepoRevisionAndMethodPathRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) FindOperationCandidatesByRepoRevisionAndMethodPath(ctx context.Context, arg FindOperationCandidatesByRepoRevisionAndMethodPathParams) ([]FindOperationCandidatesByRepoRevisionAndMethodPathRow, error) {
	rows, err := q.db.Query(ctx, findOperationCandidatesByRepoRevisionAndMethodPath,
		arg.Method,
		arg.Path,
		arg.RepoID,
		arg.SnapshotRevisionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindOperationCandidatesByRepoRevisionAndMethodPathRow{}
	for rows.Next() {
		var i FindOperationCandidatesByRepoRevisionAndMethodPathRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOperationCandidatesByRepoRevisionAndOperationID = `-- name: FindOperationCandidatesByRepoRevisionAndOperationID :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $2
      AND ingest_events.id = $3
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $2
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed
JOIN repo_specs ON repo_specs.id = latest_processed.api_spec_id
JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
WHERE endpoint_index.operation_id = $1
ORDER BY repo_specs.root_path ASC, endpoint_index.method ASC, endpoint_index.path ASC
`

type FindOperationCandidatesByRepoRevisionAndOperationIDParams struct {
	OperationID        pgtype.Text `json:"operation_id"`
	RepoID             int64       `json:"repo_id"`
	SnapshotRevisionID int64       `json:"snapshot_revision_id"`
}

type FindOperationCandidatesByRepoRevisionAndOperationIDRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) FindOperationCandidatesByRepoRevisionAndOperationID(ctx context.Context, arg FindOperationCandidatesByRepoRevisionAndOperationIDParams) ([]FindOperationCandidatesByRepoRevisionAndOperationIDRow, error) {
	rows, err := q.db.Query(ctx, findOperationCandidatesByRepoRevisionAndOperationID, arg.OperationID, arg.RepoID, arg.SnapshotRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindOperationCandidatesByRepoRevisionAndOperationIDRow{}
	for rows.Next() {
		var i FindOperationCandidatesByRepoRevisionAndOperationIDRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAPISnapshotByRepoRevisionAndAPI = `-- name: GetAPISnapshotByRepoRevisionAndAPI :one
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $1
      AND ingest_events.id = $2
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status, display_name
    FROM api_specs
    WHERE api_specs.repo_id = $1
      AND api_specs.root_path = $3
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    repo_specs.display_name,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    spec_artifacts.etag AS spec_etag,
    spec_artifacts.size_bytes AS spec_size_bytes,
    COALESCE(operation_counts.operation_count, 0)::BIGINT AS operation_count
FROM repo_specs
LEFT JOIN latest_processed ON latest_processed.api_spec_id = repo_specs.id
LEFT JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
LEFT JOIN spec_artifacts ON spec_artifacts.api_spec_revision_id = latest_processed.api_spec_revision_id
LEFT JOIN LATERAL (
    SELECT COUNT(*)::BIGINT AS operation_count
    FROM endpoint_index
    WHERE endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
) AS operation_counts ON TRUE
`

type GetAPISnapshotByRepoRevisionAndAPIParams struct {
	RepoID             int64  `json:"repo_id"`
	SnapshotRevisionID int64  `json:"snapshot_revision_id"`
	Api                string `json:"api"`
}

type GetAPISnapshotByRepoRevisionAndAPIRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	DisplayName       pgtype.Text `json:"display_name"`
	ApiSpecRevisionID pgtype.Int8 `json:"api_spec_revision_id"`
	IngestEventID     pgtype.Int8 `json:"ingest_event_id"`
	IngestEventSha    pgtype.Text `json:"ingest_event_sha"`
	IngestEventBranch pgtype.Text `json:"ingest_event_branch"`
	SpecEtag          pgtype.Text `json:"spec_etag"`
	SpecSizeBytes     pgtype.Int8 `json:"spec_size_bytes"`
	OperationCount    int64       `json:"operation_count"`
}

func (q *Queries) GetAPISnapshotByRepoRevisionAndAPI(ctx context.Context, arg GetAPISnapshotByRepoRevisionAndAPIParams) (GetAPISnapshotByRepoRevisionAndAPIRow, error) {
	row := q.db.QueryRow(ctx, getAPISnapshotByRepoRevisionAndAPI, arg.RepoID, arg.SnapshotRevisionID, arg.Api)
	var i GetAPISnapshotByRepoRevisionAndAPIRow
	err := row.Scan(
		&i.ApiSpecID,
		&i.Api,
		&i.Status,
		&i.DisplayName,
		&i.ApiSpecRevisionID,
		&i.IngestEventID,
		&i.IngestEventSha,
		&i.IngestEventBranch,
		&i.SpecEtag,
		&i.SpecSizeBytes,
		&i.OperationCount,
	)
	return i, err
}

const getRepoCatalogFreshness = `-- name: GetRepoCatalogFreshness :one
SELECT
    repos.id,
    repos.gitlab_project_id,
    namespaces.namespace,
    repos.repo,
    repos.default_branch,
    repos.openapi_force_rescan,
    COALESCE(active_api_counts.active_api_count, 0)::BIGINT AS active_api_count,
    (head.id IS NOT NULL) AS head_present,
    COALESCE(head.id, 0)::BIGINT AS head_revision_id,
    COALESCE(head.sha, '')::TEXT AS head_revision_sha,
    COALESCE(head.status, '')::TEXT AS head_revision_status,
    head.openapi_changed AS head_revision_openapi_changed,
    COALESCE(head.received_at, TIMESTAMPTZ 'epoch') AS head_revision_received_at,
    head.processed_at AS head_revision_processed_at,
    (latest_openapi.id IS NOT NULL) AS snapshot_present,
    COALESCE(latest_openapi.id, 0)::BIGINT AS snapshot_revision_id,
    COALESCE(latest_openapi.sha, '')::TEXT AS snapshot_revision_sha,
    latest_openapi.processed_at AS snapshot_revision_processed_at
FROM repos
JOIN namespaces ON namespaces.id = repos.namespace_id
LEFT JOIN LATERAL (
    SELECT COUNT(*)::BIGINT AS active_api_count
    FROM api_specs
    WHERE api_specs.repo_id = repos.id
      AND api_specs.status = 'active'
) AS active_api_counts ON TRUE
LEFT JOIN LATERAL (
    SELECT id, sha, status, openapi_changed, received_at, processed_at
    FROM ingest_events
    WHERE ingest_events.repo_id = repos.id
      AND ingest_events.branch = repos.default_branch
    ORDER BY ingest_events.received_at DESC, ingest_events.id DESC
    LIMIT 1
) AS head ON TRUE
LEFT JOIN LATERAL (
    SELECT id, sha, processed_at
    FROM ingest_events
    WHERE ingest_events.repo_id = repos.id
      AND ingest_events.branch = repos.default_branch
      AND ingest_events.status = 'processed'
      AND ingest_events.openapi_changed = TRUE
    ORDER BY ingest_events.processed_at DESC NULLS LAST, ingest_events.id DESC
    LIMIT 1
) AS latest_openapi ON TRUE
WHERE namespaces.namespace = $1
  AND repos.repo = $2
`

type GetRepoCatalogFreshnessParams struct {
	Namespace string `json:"namespace"`
	Repo      string `json:"repo"`
}

type GetRepoCatalogFreshnessRow struct {
	ID                          int64              `json:"id"`
	GitlabProjectID             int64              `json:"gitlab_project_id"`
	Namespace                   string             `json:"namespace"`
	Repo                        string             `json:"repo"`
	DefaultBranch               string             `json:"default_branch"`
	OpenapiForceRescan          bool               `json:"openapi_force_rescan"`
	ActiveApiCount              int64              `json:"active_api_count"`
	HeadPresent                 interface{}        `json:"head_present"`
	HeadRevisionID              int64              `json:"head_revision_id"`
	HeadRevisionSha             string             `json:"head_revision_sha"`
	HeadRevisionStatus          string             `json:"head_revision_status"`
	HeadRevisionOpenapiChanged  pgtype.Bool        `json:"head_revision_openapi_changed"`
	HeadRevisionReceivedAt      pgtype.Timestamptz `json:"head_revision_received_at"`
	HeadRevisionProcessedAt     pgtype.Timestamptz `json:"head_revision_processed_at"`
	SnapshotPresent             interface{}        `json:"snapshot_present"`
	SnapshotRevisionID          int64              `json:"snapshot_revision_id"`
	SnapshotRevisionSha         string             `json:"snapshot_revision_sha"`
	SnapshotRevisionProcessedAt pgtype.Timestamptz `json:"snapshot_revision_processed_at"`
}

func (q *Queries) GetRepoCatalogFreshness(ctx context.Context, arg GetRepoCatalogFreshnessParams) (GetRepoCatalogFreshnessRow, error) {
	row := q.db.QueryRow(ctx, getRepoCatalogFreshness, arg.Namespace, arg.Repo)
	var i GetRepoCatalogFreshnessRow
	err := row.Scan(
		&i.ID,
		&i.GitlabProjectID,
		&i.Namespace,
		&i.Repo,
		&i.DefaultBranch,
		&i.OpenapiForceRescan,
		&i.ActiveApiCount,
		&i.HeadPresent,
		&i.HeadRevisionID,
		&i.HeadRevisionSha,
		&i.HeadRevisionStatus,
		&i.HeadRevisionOpenapiChanged,
		&i.HeadRevisionReceivedAt,
		&i.HeadRevisionProcessedAt,
		&i.SnapshotPresent,
		&i.SnapshotRevisionID,
		&i.SnapshotRevisionSha,
		&i.SnapshotRevisionProcessedAt,
	)
	return i, err
}

const listAPISnapshotInventoryByRepoRevision = `-- name: ListAPISnapshotInventoryByRepoRevision :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $1
      AND ingest_events.id = $2
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status, display_name
    FROM api_specs
    WHERE api_specs.repo_id = $1
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    repo_specs.display_name,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    spec_artifacts.etag AS spec_etag,
    spec_artifacts.size_bytes AS spec_size_bytes,
    COALESCE(operation_counts.operation_count, 0)::BIGINT AS operation_count
FROM repo_specs
LEFT JOIN latest_processed ON latest_processed.api_spec_id = repo_specs.id
LEFT JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
LEFT JOIN spec_artifacts ON spec_artifacts.api_spec_revision_id = latest_processed.api_spec_revision_id
LEFT JOIN LATERAL (
    SELECT COUNT(*)::BIGINT AS operation_count
    FROM endpoint_index
    WHERE endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
) AS operation_counts ON TRUE
ORDER BY repo_specs.root_path ASC
`

type ListAPISnapshotInventoryByRepoRevisionParams struct {
	RepoID             int64 `json:"repo_id"`
	SnapshotRevisionID int64 `json:"snapshot_revision_id"`
}

type ListAPISnapshotInventoryByRepoRevisionRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	DisplayName       pgtype.Text `json:"display_name"`
	ApiSpecRevisionID pgtype.Int8 `json:"api_spec_revision_id"`
	IngestEventID     pgtype.Int8 `json:"ingest_event_id"`
	IngestEventSha    pgtype.Text `json:"ingest_event_sha"`
	IngestEventBranch pgtype.Text `json:"ingest_event_branch"`
	SpecEtag          pgtype.Text `json:"spec_etag"`
	SpecSizeBytes     pgtype.Int8 `json:"spec_size_bytes"`
	OperationCount    int64       `json:"operation_count"`
}

func (q *Queries) ListAPISnapshotInventoryByRepoRevision(ctx context.Context, arg ListAPISnapshotInventoryByRepoRevisionParams) ([]ListAPISnapshotInventoryByRepoRevisionRow, error) {
	rows, err := q.db.Query(ctx, listAPISnapshotInventoryByRepoRevision, arg.RepoID, arg.SnapshotRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPISnapshotInventoryByRepoRevisionRow{}
	for rows.Next() {
		var i ListAPISnapshotInventoryByRepoRevisionRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.DisplayName,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.SpecEtag,
			&i.SpecSizeBytes,
			&i.OperationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNamespaceCatalogInventory = `-- name: ListNamespaceCatalogInventory :many
SELECT
    namespaces.namespace,
    COUNT(*)::BIGINT AS repo_count,
    COALESCE(BOOL_AND(COALESCE(head.status IN ('pending', 'processing'), FALSE)), FALSE) AS all_pending
FROM namespaces
JOIN repos ON repos.namespace_id = namespaces.id
LEFT JOIN LATERAL (
    SELECT status
    FROM ingest_events
    WHERE ingest_events.repo_id = repos.id
      AND ingest_events.branch = repos.default_branch
    ORDER BY ingest_events.received_at DESC, ingest_events.id DESC
    LIMIT 1
) AS head ON TRUE
GROUP BY namespaces.namespace
ORDER BY namespaces.namespace ASC
`

type ListNamespaceCatalogInventoryRow struct {
	Namespace  string      `json:"namespace"`
	RepoCount  int64       `json:"repo_count"`
	AllPending interface{} `json:"all_pending"`
}

func (q *Queries) ListNamespaceCatalogInventory(ctx context.Context) ([]ListNamespaceCatalogInventoryRow, error) {
	rows, err := q.db.Query(ctx, listNamespaceCatalogInventory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNamespaceCatalogInventoryRow{}
	for rows.Next() {
		var i ListNamespaceCatalogInventoryRow
		if err := rows.Scan(&i.Namespace, &i.RepoCount, &i.AllPending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationInventoryByRepoRevision = `-- name: ListOperationInventoryByRepoRevision :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $1
      AND ingest_events.id = $2
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $1
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed
JOIN repo_specs ON repo_specs.id = latest_processed.api_spec_id
JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
ORDER BY repo_specs.root_path ASC, endpoint_index.method ASC, endpoint_index.path ASC
`

type ListOperationInventoryByRepoRevisionParams struct {
	RepoID             int64 `json:"repo_id"`
	SnapshotRevisionID int64 `json:"snapshot_revision_id"`
}

type ListOperationInventoryByRepoRevisionRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) ListOperationInventoryByRepoRevision(ctx context.Context, arg ListOperationInventoryByRepoRevisionParams) ([]ListOperationInventoryByRepoRevisionRow, error) {
	rows, err := q.db.Query(ctx, listOperationInventoryByRepoRevision, arg.RepoID, arg.SnapshotRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperationInventoryByRepoRevisionRow{}
	for rows.Next() {
		var i ListOperationInventoryByRepoRevisionRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationInventoryByRepoRevisionAndAPI = `-- name: ListOperationInventoryByRepoRevisionAndAPI :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $1
      AND ingest_events.id = $2
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $1
      AND api_specs.root_path = $3
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed
JOIN repo_specs ON repo_specs.id = latest_processed.api_spec_id
JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
ORDER BY endpoint_index.method ASC, endpoint_index.path ASC
`

type ListOperationInventoryByRepoRevisionAndAPIParams struct {
	RepoID             int64  `json:"repo_id"`
	SnapshotRevisionID int64  `json:"snapshot_revision_id"`
	Api                string `json:"api"`
}

type ListOperationInventoryByRepoRevisionAndAPIRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) ListOperationInventoryByRepoRevisionAndAPI(ctx context.Context, arg ListOperationInventoryByRepoRevisionAndAPIParams) ([]ListOperationInventoryByRepoRevisionAndAPIRow, error) {
	rows, err := q.db.Query(ctx, listOperationInventoryByRepoRevisionAndAPI, arg.RepoID, arg.SnapshotRevisionID, arg.Api)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperationInventoryByRepoRevisionAndAPIRow{}
	for rows.Next() {
		var i ListOperationInventoryByRepoRevisionAndAPIRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoCatalogInventory = `-- name: ListRepoCatalogInventory :many
SELECT
    repos.id,
    repos.gitlab_project_id,
    namespaces.namespace,
    repos.repo,
    repos.default_branch,
    repos.openapi_force_rescan,
    COALESCE(active_api_counts.active_api_count, 0)::BIGINT AS active_api_count,
    (head.id IS NOT NULL) AS head_present,
    COALESCE(head.id, 0)::BIGINT AS head_revision_id,
    COALESCE(head.sha, '')::TEXT AS head_revision_sha,
    COALESCE(head.status, '')::TEXT AS head_revision_status,
    head.openapi_changed AS head_revision_openapi_changed,
    COALESCE(head.received_at, TIMESTAMPTZ 'epoch') AS head_revision_received_at,
    head.processed_at AS head_revision_processed_at,
    (latest_openapi.id IS NOT NULL) AS snapshot_present,
    COALESCE(latest_openapi.id, 0)::BIGINT AS snapshot_revision_id,
    COALESCE(latest_openapi.sha, '')::TEXT AS snapshot_revision_sha,
    latest_openapi.processed_at AS snapshot_revision_processed_at
FROM repos
JOIN namespaces ON namespaces.id = repos.namespace_id
LEFT JOIN LATERAL (
    SELECT COUNT(*)::BIGINT AS active_api_count
    FROM api_specs
    WHERE api_specs.repo_id = repos.id
      AND api_specs.status = 'active'
) AS active_api_counts ON TRUE
LEFT JOIN LATERAL (
    SELECT id, sha, status, openapi_changed, received_at, processed_at
    FROM ingest_events
    WHERE ingest_events.repo_id = repos.id
      AND ingest_events.branch = repos.default_branch
    ORDER BY ingest_events.received_at DESC, ingest_events.id DESC
    LIMIT 1
) AS head ON TRUE
LEFT JOIN LATERAL (
    SELECT id, sha, processed_at
    FROM ingest_events
    WHERE ingest_events.repo_id = repos.id
      AND ingest_events.branch = repos.default_branch
      AND ingest_events.status = 'processed'
      AND ingest_events.openapi_changed = TRUE
    ORDER BY ingest_events.processed_at DESC NULLS LAST, ingest_events.id DESC
    LIMIT 1
) AS latest_openapi ON TRUE
ORDER BY namespaces.namespace ASC, repos.repo ASC
`

type ListRepoCatalogInventoryRow struct {
	ID                          int64              `json:"id"`
	GitlabProjectID             int64              `json:"gitlab_project_id"`
	Namespace                   string             `json:"namespace"`
	Repo                        string             `json:"repo"`
	DefaultBranch               string             `json:"default_branch"`
	OpenapiForceRescan          bool               `json:"openapi_force_rescan"`
	ActiveApiCount              int64              `json:"active_api_count"`
	HeadPresent                 interface{}        `json:"head_present"`
	HeadRevisionID              int64              `json:"head_revision_id"`
	HeadRevisionSha             string             `json:"head_revision_sha"`
	HeadRevisionStatus          string             `json:"head_revision_status"`
	HeadRevisionOpenapiChanged  pgtype.Bool        `json:"head_revision_openapi_changed"`
	HeadRevisionReceivedAt      pgtype.Timestamptz `json:"head_revision_received_at"`
	HeadRevisionProcessedAt     pgtype.Timestamptz `json:"head_revision_processed_at"`
	SnapshotPresent             interface{}        `json:"snapshot_present"`
	SnapshotRevisionID          int64              `json:"snapshot_revision_id"`
	SnapshotRevisionSha         string             `json:"snapshot_revision_sha"`
	SnapshotRevisionProcessedAt pgtype.Timestamptz `json:"snapshot_revision_processed_at"`
}

func (q *Queries) ListRepoCatalogInventory(ctx context.Context) ([]ListRepoCatalogInventoryRow, error) {
	rows, err := q.db.Query(ctx, listRepoCatalogInventory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepoCatalogInventoryRow{}
	for rows.Next() {
		var i ListRepoCatalogInventoryRow
		if err := rows.Scan(
			&i.ID,
			&i.GitlabProjectID,
			&i.Namespace,
			&i.Repo,
			&i.DefaultBranch,
			&i.OpenapiForceRescan,
			&i.ActiveApiCount,
			&i.HeadPresent,
			&i.HeadRevisionID,
			&i.HeadRevisionSha,
			&i.HeadRevisionStatus,
			&i.HeadRevisionOpenapiChanged,
			&i.HeadRevisionReceivedAt,
			&i.HeadRevisionProcessedAt,
			&i.SnapshotPresent,
			&i.SnapshotRevisionID,
			&i.SnapshotRevisionSha,
			&i.SnapshotRevisionProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
