// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cli_reads.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAPICatalogInventory = `-- name: CountAPICatalogInventory :one
WITH repos_in_scope AS (
    SELECT
        repos.id AS repo_id,
        namespaces.namespace,
        repos.repo,
        repos.default_branch
    FROM repos
    JOIN namespaces ON namespaces.id = repos.namespace_id
    WHERE ($2::TEXT = '' OR namespaces.namespace = $2)
      AND ($3::TEXT = '' OR repos.repo = $3)
      AND EXISTS (
          SELECT 1
          FROM api_specs
          WHERE api_specs.repo_id = repos.id
            AND api_specs.status = 'active'
      )
),
latest_processed_openapi AS (
    SELECT
        repos_in_scope.repo_id,
        latest_openapi.id AS snapshot_revision_id
    FROM repos_in_scope
    LEFT JOIN LATERAL (
        SELECT id
        FROM ingest_events
        WHERE ingest_events.repo_id = repos_in_scope.repo_id
          AND ingest_events.branch = repos_in_scope.default_branch
          AND ingest_events.status = 'processed'
          AND ingest_events.openapi_changed = TRUE
        ORDER BY ingest_events.processed_at DESC NULLS LAST, ingest_events.id DESC
        LIMIT 1
    ) AS latest_openapi ON TRUE
),
repo_specs AS (
    SELECT
        api_specs.id AS api_spec_id,
        api_specs.repo_id,
        api_specs.root_path AS api,
        api_specs.status,
        api_specs.display_name
    FROM api_specs
    JOIN repos_in_scope ON repos_in_scope.repo_id = api_specs.repo_id
    WHERE api_specs.status = 'active'
),
resolved_rows AS (
    SELECT
        COALESCE(
            NULLIF(TRIM(spec_artifacts.spec_json #>> '{info,title}'), ''),
            NULLIF(TRIM(repo_specs.display_name), ''),
            TRIM(repo_specs.api)
        )::TEXT AS title,
        repo_specs.api
    FROM repos_in_scope
    JOIN repo_specs ON repo_specs.repo_id = repos_in_scope.repo_id
    LEFT JOIN latest_processed_openapi ON latest_processed_openapi.repo_id = repos_in_scope.repo_id
    LEFT JOIN api_spec_revisions
      ON api_spec_revisions.api_spec_id = repo_specs.api_spec_id
     AND api_spec_revisions.ingest_event_id = latest_processed_openapi.snapshot_revision_id
     AND api_spec_revisions.build_status = 'processed'
    LEFT JOIN spec_artifacts ON spec_artifacts.api_spec_revision_id = api_spec_revisions.id
)
SELECT
    COUNT(*)::BIGINT AS total_count,
    COALESCE(MAX(CHAR_LENGTH(TRIM(title))), 0)::BIGINT AS max_item_length
FROM resolved_rows
WHERE (
    $1::TEXT = ''
    OR title ILIKE $1::TEXT || '%'
    OR api ILIKE $1::TEXT || '%'
)
`

type CountAPICatalogInventoryParams struct {
	QueryPrefix string `json:"query_prefix"`
	Namespace   string `json:"namespace"`
	Repo        string `json:"repo"`
}

type CountAPICatalogInventoryRow struct {
	TotalCount    int64 `json:"total_count"`
	MaxItemLength int64 `json:"max_item_length"`
}

func (q *Queries) CountAPICatalogInventory(ctx context.Context, arg CountAPICatalogInventoryParams) (CountAPICatalogInventoryRow, error) {
	row := q.db.QueryRow(ctx, countAPICatalogInventory, arg.QueryPrefix, arg.Namespace, arg.Repo)
	var i CountAPICatalogInventoryRow
	err := row.Scan(&i.TotalCount, &i.MaxItemLength)
	return i, err
}

const countAPIInventoryByRepoRevision = `-- name: CountAPIInventoryByRepoRevision :one
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $2
      AND ingest_events.id = $3
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status, display_name
    FROM api_specs
    WHERE api_specs.repo_id = $2
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
),
resolved_rows AS (
    SELECT
        COALESCE(
            NULLIF(TRIM(spec_artifacts.spec_json #>> '{info,title}'), ''),
            NULLIF(TRIM(repo_specs.display_name), ''),
            TRIM(repo_specs.root_path)
        )::TEXT AS title,
        repo_specs.root_path AS api
    FROM repo_specs
    LEFT JOIN latest_processed ON latest_processed.api_spec_id = repo_specs.id
    LEFT JOIN spec_artifacts ON spec_artifacts.api_spec_revision_id = latest_processed.api_spec_revision_id
)
SELECT
    COUNT(*)::BIGINT AS total_count,
    COALESCE(MAX(CHAR_LENGTH(TRIM(title))), 0)::BIGINT AS max_item_length
FROM resolved_rows
WHERE (
    $1::TEXT = ''
    OR title ILIKE $1::TEXT || '%'
    OR api ILIKE $1::TEXT || '%'
)
`

type CountAPIInventoryByRepoRevisionParams struct {
	QueryPrefix        string `json:"query_prefix"`
	RepoID             int64  `json:"repo_id"`
	SnapshotRevisionID int64  `json:"snapshot_revision_id"`
}

type CountAPIInventoryByRepoRevisionRow struct {
	TotalCount    int64 `json:"total_count"`
	MaxItemLength int64 `json:"max_item_length"`
}

func (q *Queries) CountAPIInventoryByRepoRevision(ctx context.Context, arg CountAPIInventoryByRepoRevisionParams) (CountAPIInventoryByRepoRevisionRow, error) {
	row := q.db.QueryRow(ctx, countAPIInventoryByRepoRevision, arg.QueryPrefix, arg.RepoID, arg.SnapshotRevisionID)
	var i CountAPIInventoryByRepoRevisionRow
	err := row.Scan(&i.TotalCount, &i.MaxItemLength)
	return i, err
}

const countNamespaceCatalogInventory = `-- name: CountNamespaceCatalogInventory :one
SELECT COUNT(DISTINCT namespaces.namespace)::BIGINT AS total_count
FROM namespaces
JOIN repos ON repos.namespace_id = namespaces.id
WHERE EXISTS (
    SELECT 1
    FROM api_specs
    WHERE api_specs.repo_id = repos.id
      AND api_specs.status = 'active'
)
  AND ($1::TEXT = '' OR namespaces.namespace ILIKE $1::TEXT || '%')
`

func (q *Queries) CountNamespaceCatalogInventory(ctx context.Context, queryPrefix string) (int64, error) {
	row := q.db.QueryRow(ctx, countNamespaceCatalogInventory, queryPrefix)
	var total_count int64
	err := row.Scan(&total_count)
	return total_count, err
}

const countOperationCatalogInventory = `-- name: CountOperationCatalogInventory :one
WITH repos_in_scope AS (
    SELECT
        repos.id AS repo_id,
        namespaces.namespace,
        repos.repo,
        repos.default_branch
    FROM repos
    JOIN namespaces ON namespaces.id = repos.namespace_id
    WHERE ($1::TEXT = '' OR namespaces.namespace = $1)
      AND ($2::TEXT = '' OR repos.repo = $2)
      AND EXISTS (
          SELECT 1
          FROM api_specs
          WHERE api_specs.repo_id = repos.id
            AND api_specs.status = 'active'
      )
),
head_processed AS (
    SELECT repos_in_scope.repo_id
    FROM repos_in_scope
    JOIN LATERAL (
        SELECT status
        FROM ingest_events
        WHERE ingest_events.repo_id = repos_in_scope.repo_id
          AND ingest_events.branch = repos_in_scope.default_branch
        ORDER BY ingest_events.received_at DESC, ingest_events.id DESC
        LIMIT 1
    ) AS head ON TRUE
    WHERE head.status = 'processed'
),
latest_processed_openapi AS (
    SELECT
        repos_in_scope.repo_id,
        latest_openapi.id AS snapshot_revision_id
    FROM repos_in_scope
    JOIN head_processed ON head_processed.repo_id = repos_in_scope.repo_id
    JOIN LATERAL (
        SELECT id
        FROM ingest_events
        WHERE ingest_events.repo_id = repos_in_scope.repo_id
          AND ingest_events.branch = repos_in_scope.default_branch
          AND ingest_events.status = 'processed'
          AND ingest_events.openapi_changed = TRUE
        ORDER BY ingest_events.processed_at DESC NULLS LAST, ingest_events.id DESC
        LIMIT 1
    ) AS latest_openapi ON TRUE
),
repo_specs AS (
    SELECT
        api_specs.id AS api_spec_id,
        api_specs.repo_id
    FROM api_specs
    JOIN repos_in_scope ON repos_in_scope.repo_id = api_specs.repo_id
    WHERE api_specs.status = 'active'
),
matched_operations AS (
    SELECT
        endpoint_index.method,
        endpoint_index.path
    FROM latest_processed_openapi
    JOIN repo_specs ON repo_specs.repo_id = latest_processed_openapi.repo_id
    JOIN api_spec_revisions
      ON api_spec_revisions.api_spec_id = repo_specs.api_spec_id
     AND api_spec_revisions.ingest_event_id = latest_processed_openapi.snapshot_revision_id
     AND api_spec_revisions.build_status = 'processed'
    JOIN endpoint_index ON endpoint_index.api_spec_revision_id = api_spec_revisions.id
    WHERE (
        $3::TEXT = ''
        OR (UPPER(TRIM(endpoint_index.method)) || ' ' || TRIM(endpoint_index.path)) ILIKE $3::TEXT || '%'
        OR COALESCE(endpoint_index.operation_id, '') ILIKE $3::TEXT || '%'
    )
)
SELECT
    COUNT(*)::BIGINT AS total_count,
    COALESCE(MAX(CHAR_LENGTH(UPPER(TRIM(method)) || ' ' || TRIM(path))), 0)::BIGINT AS max_item_length
FROM matched_operations
`

type CountOperationCatalogInventoryParams struct {
	Namespace   string `json:"namespace"`
	Repo        string `json:"repo"`
	QueryPrefix string `json:"query_prefix"`
}

type CountOperationCatalogInventoryRow struct {
	TotalCount    int64 `json:"total_count"`
	MaxItemLength int64 `json:"max_item_length"`
}

func (q *Queries) CountOperationCatalogInventory(ctx context.Context, arg CountOperationCatalogInventoryParams) (CountOperationCatalogInventoryRow, error) {
	row := q.db.QueryRow(ctx, countOperationCatalogInventory, arg.Namespace, arg.Repo, arg.QueryPrefix)
	var i CountOperationCatalogInventoryRow
	err := row.Scan(&i.TotalCount, &i.MaxItemLength)
	return i, err
}

const countOperationInventoryByRepoRevision = `-- name: CountOperationInventoryByRepoRevision :one
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $1
      AND ingest_events.id = $2
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $1
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
),
matched_operations AS (
    SELECT
        endpoint_index.method,
        endpoint_index.path
    FROM latest_processed
    JOIN endpoint_index ON endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
    WHERE (
        $3::TEXT = ''
        OR (UPPER(TRIM(endpoint_index.method)) || ' ' || TRIM(endpoint_index.path)) ILIKE $3::TEXT || '%'
        OR COALESCE(endpoint_index.operation_id, '') ILIKE $3::TEXT || '%'
    )
)
SELECT
    COUNT(*)::BIGINT AS total_count,
    COALESCE(MAX(CHAR_LENGTH(UPPER(TRIM(method)) || ' ' || TRIM(path))), 0)::BIGINT AS max_item_length
FROM matched_operations
`

type CountOperationInventoryByRepoRevisionParams struct {
	RepoID             int64  `json:"repo_id"`
	SnapshotRevisionID int64  `json:"snapshot_revision_id"`
	QueryPrefix        string `json:"query_prefix"`
}

type CountOperationInventoryByRepoRevisionRow struct {
	TotalCount    int64 `json:"total_count"`
	MaxItemLength int64 `json:"max_item_length"`
}

func (q *Queries) CountOperationInventoryByRepoRevision(ctx context.Context, arg CountOperationInventoryByRepoRevisionParams) (CountOperationInventoryByRepoRevisionRow, error) {
	row := q.db.QueryRow(ctx, countOperationInventoryByRepoRevision, arg.RepoID, arg.SnapshotRevisionID, arg.QueryPrefix)
	var i CountOperationInventoryByRepoRevisionRow
	err := row.Scan(&i.TotalCount, &i.MaxItemLength)
	return i, err
}

const findOperationCandidatesByRepoRevisionAndAPIAndMethodPath = `-- name: FindOperationCandidatesByRepoRevisionAndAPIAndMethodPath :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $3
      AND ingest_events.id = $4
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $3
      AND api_specs.root_path = $5
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed
JOIN repo_specs ON repo_specs.id = latest_processed.api_spec_id
JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
WHERE endpoint_index.method = $1
  AND endpoint_index.path = $2
ORDER BY endpoint_index.method ASC, endpoint_index.path ASC
`

type FindOperationCandidatesByRepoRevisionAndAPIAndMethodPathParams struct {
	Method             string `json:"method"`
	Path               string `json:"path"`
	RepoID             int64  `json:"repo_id"`
	SnapshotRevisionID int64  `json:"snapshot_revision_id"`
	Api                string `json:"api"`
}

type FindOperationCandidatesByRepoRevisionAndAPIAndMethodPathRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) FindOperationCandidatesByRepoRevisionAndAPIAndMethodPath(ctx context.Context, arg FindOperationCandidatesByRepoRevisionAndAPIAndMethodPathParams) ([]FindOperationCandidatesByRepoRevisionAndAPIAndMethodPathRow, error) {
	rows, err := q.db.Query(ctx, findOperationCandidatesByRepoRevisionAndAPIAndMethodPath,
		arg.Method,
		arg.Path,
		arg.RepoID,
		arg.SnapshotRevisionID,
		arg.Api,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindOperationCandidatesByRepoRevisionAndAPIAndMethodPathRow{}
	for rows.Next() {
		var i FindOperationCandidatesByRepoRevisionAndAPIAndMethodPathRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOperationCandidatesByRepoRevisionAndAPIAndOperationID = `-- name: FindOperationCandidatesByRepoRevisionAndAPIAndOperationID :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $2
      AND ingest_events.id = $3
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $2
      AND api_specs.root_path = $4
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed
JOIN repo_specs ON repo_specs.id = latest_processed.api_spec_id
JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
WHERE endpoint_index.operation_id = $1
ORDER BY endpoint_index.method ASC, endpoint_index.path ASC
`

type FindOperationCandidatesByRepoRevisionAndAPIAndOperationIDParams struct {
	OperationID        pgtype.Text `json:"operation_id"`
	RepoID             int64       `json:"repo_id"`
	SnapshotRevisionID int64       `json:"snapshot_revision_id"`
	Api                string      `json:"api"`
}

type FindOperationCandidatesByRepoRevisionAndAPIAndOperationIDRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) FindOperationCandidatesByRepoRevisionAndAPIAndOperationID(ctx context.Context, arg FindOperationCandidatesByRepoRevisionAndAPIAndOperationIDParams) ([]FindOperationCandidatesByRepoRevisionAndAPIAndOperationIDRow, error) {
	rows, err := q.db.Query(ctx, findOperationCandidatesByRepoRevisionAndAPIAndOperationID,
		arg.OperationID,
		arg.RepoID,
		arg.SnapshotRevisionID,
		arg.Api,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindOperationCandidatesByRepoRevisionAndAPIAndOperationIDRow{}
	for rows.Next() {
		var i FindOperationCandidatesByRepoRevisionAndAPIAndOperationIDRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOperationCandidatesByRepoRevisionAndMethodPath = `-- name: FindOperationCandidatesByRepoRevisionAndMethodPath :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $3
      AND ingest_events.id = $4
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $3
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed
JOIN repo_specs ON repo_specs.id = latest_processed.api_spec_id
JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
WHERE endpoint_index.method = $1
  AND endpoint_index.path = $2
ORDER BY repo_specs.root_path ASC, endpoint_index.method ASC, endpoint_index.path ASC
`

type FindOperationCandidatesByRepoRevisionAndMethodPathParams struct {
	Method             string `json:"method"`
	Path               string `json:"path"`
	RepoID             int64  `json:"repo_id"`
	SnapshotRevisionID int64  `json:"snapshot_revision_id"`
}

type FindOperationCandidatesByRepoRevisionAndMethodPathRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) FindOperationCandidatesByRepoRevisionAndMethodPath(ctx context.Context, arg FindOperationCandidatesByRepoRevisionAndMethodPathParams) ([]FindOperationCandidatesByRepoRevisionAndMethodPathRow, error) {
	rows, err := q.db.Query(ctx, findOperationCandidatesByRepoRevisionAndMethodPath,
		arg.Method,
		arg.Path,
		arg.RepoID,
		arg.SnapshotRevisionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindOperationCandidatesByRepoRevisionAndMethodPathRow{}
	for rows.Next() {
		var i FindOperationCandidatesByRepoRevisionAndMethodPathRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOperationCandidatesByRepoRevisionAndOperationID = `-- name: FindOperationCandidatesByRepoRevisionAndOperationID :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $2
      AND ingest_events.id = $3
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $2
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed
JOIN repo_specs ON repo_specs.id = latest_processed.api_spec_id
JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
WHERE endpoint_index.operation_id = $1
ORDER BY repo_specs.root_path ASC, endpoint_index.method ASC, endpoint_index.path ASC
`

type FindOperationCandidatesByRepoRevisionAndOperationIDParams struct {
	OperationID        pgtype.Text `json:"operation_id"`
	RepoID             int64       `json:"repo_id"`
	SnapshotRevisionID int64       `json:"snapshot_revision_id"`
}

type FindOperationCandidatesByRepoRevisionAndOperationIDRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) FindOperationCandidatesByRepoRevisionAndOperationID(ctx context.Context, arg FindOperationCandidatesByRepoRevisionAndOperationIDParams) ([]FindOperationCandidatesByRepoRevisionAndOperationIDRow, error) {
	rows, err := q.db.Query(ctx, findOperationCandidatesByRepoRevisionAndOperationID, arg.OperationID, arg.RepoID, arg.SnapshotRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindOperationCandidatesByRepoRevisionAndOperationIDRow{}
	for rows.Next() {
		var i FindOperationCandidatesByRepoRevisionAndOperationIDRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAPISnapshotByRepoRevisionAndAPI = `-- name: GetAPISnapshotByRepoRevisionAndAPI :one
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $1
      AND ingest_events.id = $2
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status, display_name
    FROM api_specs
    WHERE api_specs.repo_id = $1
      AND api_specs.root_path = $3
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    repo_specs.display_name,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    spec_artifacts.etag AS spec_etag,
    spec_artifacts.size_bytes AS spec_size_bytes,
    COALESCE(operation_counts.operation_count, 0)::BIGINT AS operation_count
FROM repo_specs
LEFT JOIN latest_processed ON latest_processed.api_spec_id = repo_specs.id
LEFT JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
LEFT JOIN spec_artifacts ON spec_artifacts.api_spec_revision_id = latest_processed.api_spec_revision_id
LEFT JOIN LATERAL (
    SELECT COUNT(*)::BIGINT AS operation_count
    FROM endpoint_index
    WHERE endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
) AS operation_counts ON TRUE
`

type GetAPISnapshotByRepoRevisionAndAPIParams struct {
	RepoID             int64  `json:"repo_id"`
	SnapshotRevisionID int64  `json:"snapshot_revision_id"`
	Api                string `json:"api"`
}

type GetAPISnapshotByRepoRevisionAndAPIRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	DisplayName       pgtype.Text `json:"display_name"`
	ApiSpecRevisionID pgtype.Int8 `json:"api_spec_revision_id"`
	IngestEventID     pgtype.Int8 `json:"ingest_event_id"`
	IngestEventSha    pgtype.Text `json:"ingest_event_sha"`
	IngestEventBranch pgtype.Text `json:"ingest_event_branch"`
	SpecEtag          pgtype.Text `json:"spec_etag"`
	SpecSizeBytes     pgtype.Int8 `json:"spec_size_bytes"`
	OperationCount    int64       `json:"operation_count"`
}

func (q *Queries) GetAPISnapshotByRepoRevisionAndAPI(ctx context.Context, arg GetAPISnapshotByRepoRevisionAndAPIParams) (GetAPISnapshotByRepoRevisionAndAPIRow, error) {
	row := q.db.QueryRow(ctx, getAPISnapshotByRepoRevisionAndAPI, arg.RepoID, arg.SnapshotRevisionID, arg.Api)
	var i GetAPISnapshotByRepoRevisionAndAPIRow
	err := row.Scan(
		&i.ApiSpecID,
		&i.Api,
		&i.Status,
		&i.DisplayName,
		&i.ApiSpecRevisionID,
		&i.IngestEventID,
		&i.IngestEventSha,
		&i.IngestEventBranch,
		&i.SpecEtag,
		&i.SpecSizeBytes,
		&i.OperationCount,
	)
	return i, err
}

const getRepoCatalogFreshness = `-- name: GetRepoCatalogFreshness :one
SELECT
    repos.id,
    repos.gitlab_project_id,
    namespaces.namespace,
    repos.repo,
    repos.default_branch,
    repos.openapi_force_rescan,
    COALESCE(active_api_counts.active_api_count, 0)::BIGINT AS active_api_count,
    (head.id IS NOT NULL) AS head_present,
    COALESCE(head.id, 0)::BIGINT AS head_revision_id,
    COALESCE(head.sha, '')::TEXT AS head_revision_sha,
    COALESCE(head.status, '')::TEXT AS head_revision_status,
    head.openapi_changed AS head_revision_openapi_changed,
    COALESCE(head.received_at, TIMESTAMPTZ 'epoch') AS head_revision_received_at,
    head.processed_at AS head_revision_processed_at,
    (latest_openapi.id IS NOT NULL) AS snapshot_present,
    COALESCE(latest_openapi.id, 0)::BIGINT AS snapshot_revision_id,
    COALESCE(latest_openapi.sha, '')::TEXT AS snapshot_revision_sha,
    latest_openapi.processed_at AS snapshot_revision_processed_at
FROM repos
JOIN namespaces ON namespaces.id = repos.namespace_id
LEFT JOIN LATERAL (
    SELECT COUNT(*)::BIGINT AS active_api_count
    FROM api_specs
    WHERE api_specs.repo_id = repos.id
      AND api_specs.status = 'active'
) AS active_api_counts ON TRUE
LEFT JOIN LATERAL (
    SELECT id, sha, status, openapi_changed, received_at, processed_at
    FROM ingest_events
    WHERE ingest_events.repo_id = repos.id
      AND ingest_events.branch = repos.default_branch
    ORDER BY ingest_events.received_at DESC, ingest_events.id DESC
    LIMIT 1
) AS head ON TRUE
LEFT JOIN LATERAL (
    SELECT id, sha, processed_at
    FROM ingest_events
    WHERE ingest_events.repo_id = repos.id
      AND ingest_events.branch = repos.default_branch
      AND ingest_events.status = 'processed'
      AND ingest_events.openapi_changed = TRUE
    ORDER BY ingest_events.processed_at DESC NULLS LAST, ingest_events.id DESC
    LIMIT 1
) AS latest_openapi ON TRUE
WHERE namespaces.namespace = $1
  AND repos.repo = $2
`

type GetRepoCatalogFreshnessParams struct {
	Namespace string `json:"namespace"`
	Repo      string `json:"repo"`
}

type GetRepoCatalogFreshnessRow struct {
	ID                          int64              `json:"id"`
	GitlabProjectID             int64              `json:"gitlab_project_id"`
	Namespace                   string             `json:"namespace"`
	Repo                        string             `json:"repo"`
	DefaultBranch               string             `json:"default_branch"`
	OpenapiForceRescan          bool               `json:"openapi_force_rescan"`
	ActiveApiCount              int64              `json:"active_api_count"`
	HeadPresent                 interface{}        `json:"head_present"`
	HeadRevisionID              int64              `json:"head_revision_id"`
	HeadRevisionSha             string             `json:"head_revision_sha"`
	HeadRevisionStatus          string             `json:"head_revision_status"`
	HeadRevisionOpenapiChanged  pgtype.Bool        `json:"head_revision_openapi_changed"`
	HeadRevisionReceivedAt      pgtype.Timestamptz `json:"head_revision_received_at"`
	HeadRevisionProcessedAt     pgtype.Timestamptz `json:"head_revision_processed_at"`
	SnapshotPresent             interface{}        `json:"snapshot_present"`
	SnapshotRevisionID          int64              `json:"snapshot_revision_id"`
	SnapshotRevisionSha         string             `json:"snapshot_revision_sha"`
	SnapshotRevisionProcessedAt pgtype.Timestamptz `json:"snapshot_revision_processed_at"`
}

func (q *Queries) GetRepoCatalogFreshness(ctx context.Context, arg GetRepoCatalogFreshnessParams) (GetRepoCatalogFreshnessRow, error) {
	row := q.db.QueryRow(ctx, getRepoCatalogFreshness, arg.Namespace, arg.Repo)
	var i GetRepoCatalogFreshnessRow
	err := row.Scan(
		&i.ID,
		&i.GitlabProjectID,
		&i.Namespace,
		&i.Repo,
		&i.DefaultBranch,
		&i.OpenapiForceRescan,
		&i.ActiveApiCount,
		&i.HeadPresent,
		&i.HeadRevisionID,
		&i.HeadRevisionSha,
		&i.HeadRevisionStatus,
		&i.HeadRevisionOpenapiChanged,
		&i.HeadRevisionReceivedAt,
		&i.HeadRevisionProcessedAt,
		&i.SnapshotPresent,
		&i.SnapshotRevisionID,
		&i.SnapshotRevisionSha,
		&i.SnapshotRevisionProcessedAt,
	)
	return i, err
}

const listAPICatalogInventory = `-- name: ListAPICatalogInventory :many
WITH repos_in_scope AS (
    SELECT
        repos.id AS repo_id,
        namespaces.namespace,
        repos.repo,
        repos.default_branch
    FROM repos
    JOIN namespaces ON namespaces.id = repos.namespace_id
    WHERE ($1::TEXT = '' OR namespaces.namespace = $1)
      AND ($2::TEXT = '' OR repos.repo = $2)
      AND EXISTS (
          SELECT 1
          FROM api_specs
          WHERE api_specs.repo_id = repos.id
            AND api_specs.status = 'active'
      )
),
latest_processed_openapi AS (
    SELECT
        repos_in_scope.repo_id,
        latest_openapi.id AS snapshot_revision_id
    FROM repos_in_scope
    LEFT JOIN LATERAL (
        SELECT id
        FROM ingest_events
        WHERE ingest_events.repo_id = repos_in_scope.repo_id
          AND ingest_events.branch = repos_in_scope.default_branch
          AND ingest_events.status = 'processed'
          AND ingest_events.openapi_changed = TRUE
        ORDER BY ingest_events.processed_at DESC NULLS LAST, ingest_events.id DESC
        LIMIT 1
    ) AS latest_openapi ON TRUE
),
repo_specs AS (
    SELECT
        api_specs.id AS api_spec_id,
        api_specs.repo_id,
        api_specs.root_path AS api,
        api_specs.status,
        api_specs.display_name
    FROM api_specs
    JOIN repos_in_scope ON repos_in_scope.repo_id = api_specs.repo_id
    WHERE api_specs.status = 'active'
)
SELECT
    repos_in_scope.namespace,
    repos_in_scope.repo,
    repo_specs.api_spec_id,
    repo_specs.api,
    COALESCE(
        NULLIF(TRIM(spec_artifacts.spec_json #>> '{info,title}'), ''),
        NULLIF(TRIM(repo_specs.display_name), ''),
        TRIM(repo_specs.api)
    )::TEXT AS title,
    repo_specs.status,
    repo_specs.display_name,
    api_spec_revisions.id AS api_spec_revision_id,
    ingest_events.id AS ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    spec_artifacts.etag AS spec_etag,
    spec_artifacts.size_bytes AS spec_size_bytes,
    COALESCE(operation_counts.operation_count, 0)::BIGINT AS operation_count
FROM repos_in_scope
JOIN repo_specs ON repo_specs.repo_id = repos_in_scope.repo_id
LEFT JOIN latest_processed_openapi ON latest_processed_openapi.repo_id = repos_in_scope.repo_id
LEFT JOIN api_spec_revisions
  ON api_spec_revisions.api_spec_id = repo_specs.api_spec_id
 AND api_spec_revisions.ingest_event_id = latest_processed_openapi.snapshot_revision_id
 AND api_spec_revisions.build_status = 'processed'
LEFT JOIN ingest_events ON ingest_events.id = api_spec_revisions.ingest_event_id
LEFT JOIN spec_artifacts ON spec_artifacts.api_spec_revision_id = api_spec_revisions.id
LEFT JOIN LATERAL (
    SELECT COUNT(*)::BIGINT AS operation_count
    FROM endpoint_index
    WHERE endpoint_index.api_spec_revision_id = api_spec_revisions.id
) AS operation_counts ON TRUE
ORDER BY repos_in_scope.namespace ASC, repos_in_scope.repo ASC, repo_specs.api ASC
`

type ListAPICatalogInventoryParams struct {
	Namespace string `json:"namespace"`
	Repo      string `json:"repo"`
}

type ListAPICatalogInventoryRow struct {
	Namespace         string      `json:"namespace"`
	Repo              string      `json:"repo"`
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Title             string      `json:"title"`
	Status            string      `json:"status"`
	DisplayName       pgtype.Text `json:"display_name"`
	ApiSpecRevisionID pgtype.Int8 `json:"api_spec_revision_id"`
	IngestEventID     pgtype.Int8 `json:"ingest_event_id"`
	IngestEventSha    pgtype.Text `json:"ingest_event_sha"`
	IngestEventBranch pgtype.Text `json:"ingest_event_branch"`
	SpecEtag          pgtype.Text `json:"spec_etag"`
	SpecSizeBytes     pgtype.Int8 `json:"spec_size_bytes"`
	OperationCount    int64       `json:"operation_count"`
}

func (q *Queries) ListAPICatalogInventory(ctx context.Context, arg ListAPICatalogInventoryParams) ([]ListAPICatalogInventoryRow, error) {
	rows, err := q.db.Query(ctx, listAPICatalogInventory, arg.Namespace, arg.Repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPICatalogInventoryRow{}
	for rows.Next() {
		var i ListAPICatalogInventoryRow
		if err := rows.Scan(
			&i.Namespace,
			&i.Repo,
			&i.ApiSpecID,
			&i.Api,
			&i.Title,
			&i.Status,
			&i.DisplayName,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.SpecEtag,
			&i.SpecSizeBytes,
			&i.OperationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPICatalogInventoryPage = `-- name: ListAPICatalogInventoryPage :many
WITH repos_in_scope AS (
    SELECT
        repos.id AS repo_id,
        namespaces.namespace,
        repos.repo,
        repos.default_branch
    FROM repos
    JOIN namespaces ON namespaces.id = repos.namespace_id
    WHERE ($3::TEXT = '' OR namespaces.namespace = $3)
      AND ($4::TEXT = '' OR repos.repo = $4)
      AND EXISTS (
          SELECT 1
          FROM api_specs
          WHERE api_specs.repo_id = repos.id
            AND api_specs.status = 'active'
      )
),
latest_processed_openapi AS (
    SELECT
        repos_in_scope.repo_id,
        latest_openapi.id AS snapshot_revision_id
    FROM repos_in_scope
    LEFT JOIN LATERAL (
        SELECT id
        FROM ingest_events
        WHERE ingest_events.repo_id = repos_in_scope.repo_id
          AND ingest_events.branch = repos_in_scope.default_branch
          AND ingest_events.status = 'processed'
          AND ingest_events.openapi_changed = TRUE
        ORDER BY ingest_events.processed_at DESC NULLS LAST, ingest_events.id DESC
        LIMIT 1
    ) AS latest_openapi ON TRUE
),
repo_specs AS (
    SELECT
        api_specs.id AS api_spec_id,
        api_specs.repo_id,
        api_specs.root_path AS api,
        api_specs.status,
        api_specs.display_name
    FROM api_specs
    JOIN repos_in_scope ON repos_in_scope.repo_id = api_specs.repo_id
    WHERE api_specs.status = 'active'
),
resolved_rows AS (
    SELECT
        repos_in_scope.namespace,
        repos_in_scope.repo,
        repo_specs.api_spec_id,
        repo_specs.api,
        COALESCE(
            NULLIF(TRIM(spec_artifacts.spec_json #>> '{info,title}'), ''),
            NULLIF(TRIM(repo_specs.display_name), ''),
            TRIM(repo_specs.api)
        )::TEXT AS title,
        repo_specs.status,
        repo_specs.display_name,
        api_spec_revisions.id AS api_spec_revision_id,
        ingest_events.id AS ingest_event_id,
        ingest_events.sha AS ingest_event_sha,
        ingest_events.branch AS ingest_event_branch,
        spec_artifacts.etag AS spec_etag,
        spec_artifacts.size_bytes AS spec_size_bytes,
        COALESCE(operation_counts.operation_count, 0)::BIGINT AS operation_count
    FROM repos_in_scope
    JOIN repo_specs ON repo_specs.repo_id = repos_in_scope.repo_id
    LEFT JOIN latest_processed_openapi ON latest_processed_openapi.repo_id = repos_in_scope.repo_id
    LEFT JOIN api_spec_revisions
      ON api_spec_revisions.api_spec_id = repo_specs.api_spec_id
     AND api_spec_revisions.ingest_event_id = latest_processed_openapi.snapshot_revision_id
     AND api_spec_revisions.build_status = 'processed'
    LEFT JOIN ingest_events ON ingest_events.id = api_spec_revisions.ingest_event_id
    LEFT JOIN spec_artifacts ON spec_artifacts.api_spec_revision_id = api_spec_revisions.id
    LEFT JOIN LATERAL (
        SELECT COUNT(*)::BIGINT AS operation_count
        FROM endpoint_index
        WHERE endpoint_index.api_spec_revision_id = api_spec_revisions.id
    ) AS operation_counts ON TRUE
    WHERE (
        $5::TEXT = ''
        OR COALESCE(
            NULLIF(TRIM(spec_artifacts.spec_json #>> '{info,title}'), ''),
            NULLIF(TRIM(repo_specs.display_name), ''),
            TRIM(repo_specs.api)
        ) ILIKE $5::TEXT || '%'
        OR repo_specs.api ILIKE $5::TEXT || '%'
    )
)
SELECT
    namespace,
    repo,
    api_spec_id,
    api,
    title,
    status,
    display_name,
    api_spec_revision_id,
    ingest_event_id,
    ingest_event_sha,
    ingest_event_branch,
    spec_etag,
    spec_size_bytes,
    operation_count
FROM resolved_rows
ORDER BY namespace ASC, repo ASC, api ASC
LIMIT $2
OFFSET $1
`

type ListAPICatalogInventoryPageParams struct {
	PageOffset  int32  `json:"page_offset"`
	PageLimit   int32  `json:"page_limit"`
	Namespace   string `json:"namespace"`
	Repo        string `json:"repo"`
	QueryPrefix string `json:"query_prefix"`
}

type ListAPICatalogInventoryPageRow struct {
	Namespace         string      `json:"namespace"`
	Repo              string      `json:"repo"`
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Title             string      `json:"title"`
	Status            string      `json:"status"`
	DisplayName       pgtype.Text `json:"display_name"`
	ApiSpecRevisionID pgtype.Int8 `json:"api_spec_revision_id"`
	IngestEventID     pgtype.Int8 `json:"ingest_event_id"`
	IngestEventSha    pgtype.Text `json:"ingest_event_sha"`
	IngestEventBranch pgtype.Text `json:"ingest_event_branch"`
	SpecEtag          pgtype.Text `json:"spec_etag"`
	SpecSizeBytes     pgtype.Int8 `json:"spec_size_bytes"`
	OperationCount    int64       `json:"operation_count"`
}

func (q *Queries) ListAPICatalogInventoryPage(ctx context.Context, arg ListAPICatalogInventoryPageParams) ([]ListAPICatalogInventoryPageRow, error) {
	rows, err := q.db.Query(ctx, listAPICatalogInventoryPage,
		arg.PageOffset,
		arg.PageLimit,
		arg.Namespace,
		arg.Repo,
		arg.QueryPrefix,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPICatalogInventoryPageRow{}
	for rows.Next() {
		var i ListAPICatalogInventoryPageRow
		if err := rows.Scan(
			&i.Namespace,
			&i.Repo,
			&i.ApiSpecID,
			&i.Api,
			&i.Title,
			&i.Status,
			&i.DisplayName,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.SpecEtag,
			&i.SpecSizeBytes,
			&i.OperationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPISnapshotInventoryByRepoRevision = `-- name: ListAPISnapshotInventoryByRepoRevision :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $1
      AND ingest_events.id = $2
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status, display_name
    FROM api_specs
    WHERE api_specs.repo_id = $1
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    COALESCE(
        NULLIF(TRIM(spec_artifacts.spec_json #>> '{info,title}'), ''),
        NULLIF(TRIM(repo_specs.display_name), ''),
        TRIM(repo_specs.root_path)
    )::TEXT AS title,
    repo_specs.status,
    repo_specs.display_name,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    spec_artifacts.etag AS spec_etag,
    spec_artifacts.size_bytes AS spec_size_bytes,
    COALESCE(operation_counts.operation_count, 0)::BIGINT AS operation_count
FROM repo_specs
LEFT JOIN latest_processed ON latest_processed.api_spec_id = repo_specs.id
LEFT JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
LEFT JOIN spec_artifacts ON spec_artifacts.api_spec_revision_id = latest_processed.api_spec_revision_id
LEFT JOIN LATERAL (
    SELECT COUNT(*)::BIGINT AS operation_count
    FROM endpoint_index
    WHERE endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
) AS operation_counts ON TRUE
ORDER BY repo_specs.root_path ASC
`

type ListAPISnapshotInventoryByRepoRevisionParams struct {
	RepoID             int64 `json:"repo_id"`
	SnapshotRevisionID int64 `json:"snapshot_revision_id"`
}

type ListAPISnapshotInventoryByRepoRevisionRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Title             string      `json:"title"`
	Status            string      `json:"status"`
	DisplayName       pgtype.Text `json:"display_name"`
	ApiSpecRevisionID pgtype.Int8 `json:"api_spec_revision_id"`
	IngestEventID     pgtype.Int8 `json:"ingest_event_id"`
	IngestEventSha    pgtype.Text `json:"ingest_event_sha"`
	IngestEventBranch pgtype.Text `json:"ingest_event_branch"`
	SpecEtag          pgtype.Text `json:"spec_etag"`
	SpecSizeBytes     pgtype.Int8 `json:"spec_size_bytes"`
	OperationCount    int64       `json:"operation_count"`
}

func (q *Queries) ListAPISnapshotInventoryByRepoRevision(ctx context.Context, arg ListAPISnapshotInventoryByRepoRevisionParams) ([]ListAPISnapshotInventoryByRepoRevisionRow, error) {
	rows, err := q.db.Query(ctx, listAPISnapshotInventoryByRepoRevision, arg.RepoID, arg.SnapshotRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPISnapshotInventoryByRepoRevisionRow{}
	for rows.Next() {
		var i ListAPISnapshotInventoryByRepoRevisionRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Title,
			&i.Status,
			&i.DisplayName,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.SpecEtag,
			&i.SpecSizeBytes,
			&i.OperationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPISnapshotInventoryByRepoRevisionPage = `-- name: ListAPISnapshotInventoryByRepoRevisionPage :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $3
      AND ingest_events.id = $4
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status, display_name
    FROM api_specs
    WHERE api_specs.repo_id = $3
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
),
resolved_rows AS (
    SELECT
        repo_specs.id AS api_spec_id,
        repo_specs.root_path AS api,
        COALESCE(
            NULLIF(TRIM(spec_artifacts.spec_json #>> '{info,title}'), ''),
            NULLIF(TRIM(repo_specs.display_name), ''),
            TRIM(repo_specs.root_path)
        )::TEXT AS title,
        repo_specs.status,
        repo_specs.display_name,
        latest_processed.api_spec_revision_id,
        latest_processed.ingest_event_id,
        ingest_events.sha AS ingest_event_sha,
        ingest_events.branch AS ingest_event_branch,
        spec_artifacts.etag AS spec_etag,
        spec_artifacts.size_bytes AS spec_size_bytes,
        COALESCE(operation_counts.operation_count, 0)::BIGINT AS operation_count
    FROM repo_specs
    LEFT JOIN latest_processed ON latest_processed.api_spec_id = repo_specs.id
    LEFT JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
    LEFT JOIN spec_artifacts ON spec_artifacts.api_spec_revision_id = latest_processed.api_spec_revision_id
    LEFT JOIN LATERAL (
        SELECT COUNT(*)::BIGINT AS operation_count
        FROM endpoint_index
        WHERE endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
    ) AS operation_counts ON TRUE
    WHERE (
        $5::TEXT = ''
        OR COALESCE(
            NULLIF(TRIM(spec_artifacts.spec_json #>> '{info,title}'), ''),
            NULLIF(TRIM(repo_specs.display_name), ''),
            TRIM(repo_specs.root_path)
        ) ILIKE $5::TEXT || '%'
        OR repo_specs.root_path ILIKE $5::TEXT || '%'
    )
)
SELECT
    api_spec_id,
    api,
    title,
    status,
    display_name,
    api_spec_revision_id,
    ingest_event_id,
    ingest_event_sha,
    ingest_event_branch,
    spec_etag,
    spec_size_bytes,
    operation_count
FROM resolved_rows
ORDER BY api ASC
LIMIT $2
OFFSET $1
`

type ListAPISnapshotInventoryByRepoRevisionPageParams struct {
	PageOffset         int32  `json:"page_offset"`
	PageLimit          int32  `json:"page_limit"`
	RepoID             int64  `json:"repo_id"`
	SnapshotRevisionID int64  `json:"snapshot_revision_id"`
	QueryPrefix        string `json:"query_prefix"`
}

type ListAPISnapshotInventoryByRepoRevisionPageRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Title             string      `json:"title"`
	Status            string      `json:"status"`
	DisplayName       pgtype.Text `json:"display_name"`
	ApiSpecRevisionID pgtype.Int8 `json:"api_spec_revision_id"`
	IngestEventID     pgtype.Int8 `json:"ingest_event_id"`
	IngestEventSha    pgtype.Text `json:"ingest_event_sha"`
	IngestEventBranch pgtype.Text `json:"ingest_event_branch"`
	SpecEtag          pgtype.Text `json:"spec_etag"`
	SpecSizeBytes     pgtype.Int8 `json:"spec_size_bytes"`
	OperationCount    int64       `json:"operation_count"`
}

func (q *Queries) ListAPISnapshotInventoryByRepoRevisionPage(ctx context.Context, arg ListAPISnapshotInventoryByRepoRevisionPageParams) ([]ListAPISnapshotInventoryByRepoRevisionPageRow, error) {
	rows, err := q.db.Query(ctx, listAPISnapshotInventoryByRepoRevisionPage,
		arg.PageOffset,
		arg.PageLimit,
		arg.RepoID,
		arg.SnapshotRevisionID,
		arg.QueryPrefix,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPISnapshotInventoryByRepoRevisionPageRow{}
	for rows.Next() {
		var i ListAPISnapshotInventoryByRepoRevisionPageRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Title,
			&i.Status,
			&i.DisplayName,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.SpecEtag,
			&i.SpecSizeBytes,
			&i.OperationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNamespaceCatalogInventory = `-- name: ListNamespaceCatalogInventory :many
WITH namespace_rows AS (
    SELECT
        namespaces.namespace,
        COUNT(*)::BIGINT AS repo_count,
        COALESCE(BOOL_AND(COALESCE(head.status IN ('pending', 'processing'), FALSE)), FALSE) AS all_pending
    FROM namespaces
    JOIN repos ON repos.namespace_id = namespaces.id
    LEFT JOIN LATERAL (
        SELECT status
        FROM ingest_events
        WHERE ingest_events.repo_id = repos.id
          AND ingest_events.branch = repos.default_branch
        ORDER BY ingest_events.received_at DESC, ingest_events.id DESC
        LIMIT 1
    ) AS head ON TRUE
    WHERE EXISTS (
        SELECT 1
        FROM api_specs
        WHERE api_specs.repo_id = repos.id
          AND api_specs.status = 'active'
    )
    GROUP BY namespaces.namespace
),
filtered_rows AS (
    SELECT namespace, repo_count, all_pending
    FROM namespace_rows
    WHERE ($3::TEXT = '' OR namespace_rows.namespace ILIKE $3::TEXT || '%')
)
SELECT
    namespace,
    repo_count,
    all_pending
FROM filtered_rows
ORDER BY namespace ASC
LIMIT $2
OFFSET $1
`

type ListNamespaceCatalogInventoryParams struct {
	PageOffset  int32  `json:"page_offset"`
	PageLimit   int32  `json:"page_limit"`
	QueryPrefix string `json:"query_prefix"`
}

type ListNamespaceCatalogInventoryRow struct {
	Namespace  string      `json:"namespace"`
	RepoCount  int64       `json:"repo_count"`
	AllPending interface{} `json:"all_pending"`
}

func (q *Queries) ListNamespaceCatalogInventory(ctx context.Context, arg ListNamespaceCatalogInventoryParams) ([]ListNamespaceCatalogInventoryRow, error) {
	rows, err := q.db.Query(ctx, listNamespaceCatalogInventory, arg.PageOffset, arg.PageLimit, arg.QueryPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNamespaceCatalogInventoryRow{}
	for rows.Next() {
		var i ListNamespaceCatalogInventoryRow
		if err := rows.Scan(&i.Namespace, &i.RepoCount, &i.AllPending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationCatalogInventory = `-- name: ListOperationCatalogInventory :many
WITH repos_in_scope AS (
    SELECT
        repos.id AS repo_id,
        namespaces.namespace,
        repos.repo,
        repos.default_branch
    FROM repos
    JOIN namespaces ON namespaces.id = repos.namespace_id
    WHERE ($1::TEXT = '' OR namespaces.namespace = $1)
      AND EXISTS (
          SELECT 1
          FROM api_specs
          WHERE api_specs.repo_id = repos.id
            AND api_specs.status = 'active'
      )
),
head_processed AS (
    SELECT repos_in_scope.repo_id
    FROM repos_in_scope
    JOIN LATERAL (
        SELECT status
        FROM ingest_events
        WHERE ingest_events.repo_id = repos_in_scope.repo_id
          AND ingest_events.branch = repos_in_scope.default_branch
        ORDER BY ingest_events.received_at DESC, ingest_events.id DESC
        LIMIT 1
    ) AS head ON TRUE
    WHERE head.status = 'processed'
),
latest_processed_openapi AS (
    SELECT
        repos_in_scope.repo_id,
        latest_openapi.id AS snapshot_revision_id
    FROM repos_in_scope
    JOIN head_processed ON head_processed.repo_id = repos_in_scope.repo_id
    JOIN LATERAL (
        SELECT id
        FROM ingest_events
        WHERE ingest_events.repo_id = repos_in_scope.repo_id
          AND ingest_events.branch = repos_in_scope.default_branch
          AND ingest_events.status = 'processed'
          AND ingest_events.openapi_changed = TRUE
        ORDER BY ingest_events.processed_at DESC NULLS LAST, ingest_events.id DESC
        LIMIT 1
    ) AS latest_openapi ON TRUE
),
repo_specs AS (
    SELECT
        api_specs.id AS api_spec_id,
        api_specs.repo_id,
        api_specs.root_path AS api,
        api_specs.status
    FROM api_specs
    JOIN repos_in_scope ON repos_in_scope.repo_id = api_specs.repo_id
    WHERE api_specs.status = 'active'
)
SELECT
    repos_in_scope.namespace,
    repos_in_scope.repo,
    repo_specs.api_spec_id,
    repo_specs.api,
    repo_specs.status,
    api_spec_revisions.id AS api_spec_revision_id,
    ingest_events.id AS ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed_openapi
JOIN repos_in_scope ON repos_in_scope.repo_id = latest_processed_openapi.repo_id
JOIN repo_specs ON repo_specs.repo_id = latest_processed_openapi.repo_id
JOIN api_spec_revisions
  ON api_spec_revisions.api_spec_id = repo_specs.api_spec_id
 AND api_spec_revisions.ingest_event_id = latest_processed_openapi.snapshot_revision_id
 AND api_spec_revisions.build_status = 'processed'
JOIN ingest_events ON ingest_events.id = api_spec_revisions.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = api_spec_revisions.id
ORDER BY repos_in_scope.namespace ASC, repos_in_scope.repo ASC, repo_specs.api ASC, endpoint_index.method ASC, endpoint_index.path ASC
`

type ListOperationCatalogInventoryRow struct {
	Namespace         string      `json:"namespace"`
	Repo              string      `json:"repo"`
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) ListOperationCatalogInventory(ctx context.Context, namespace string) ([]ListOperationCatalogInventoryRow, error) {
	rows, err := q.db.Query(ctx, listOperationCatalogInventory, namespace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperationCatalogInventoryRow{}
	for rows.Next() {
		var i ListOperationCatalogInventoryRow
		if err := rows.Scan(
			&i.Namespace,
			&i.Repo,
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationCatalogInventoryPage = `-- name: ListOperationCatalogInventoryPage :many
WITH repos_in_scope AS (
    SELECT
        repos.id AS repo_id,
        namespaces.namespace,
        repos.repo,
        repos.default_branch
    FROM repos
    JOIN namespaces ON namespaces.id = repos.namespace_id
    WHERE ($4::TEXT = '' OR namespaces.namespace = $4)
      AND ($5::TEXT = '' OR repos.repo = $5)
      AND EXISTS (
          SELECT 1
          FROM api_specs
          WHERE api_specs.repo_id = repos.id
            AND api_specs.status = 'active'
      )
),
head_processed AS (
    SELECT repos_in_scope.repo_id
    FROM repos_in_scope
    JOIN LATERAL (
        SELECT status
        FROM ingest_events
        WHERE ingest_events.repo_id = repos_in_scope.repo_id
          AND ingest_events.branch = repos_in_scope.default_branch
        ORDER BY ingest_events.received_at DESC, ingest_events.id DESC
        LIMIT 1
    ) AS head ON TRUE
    WHERE head.status = 'processed'
),
latest_processed_openapi AS (
    SELECT
        repos_in_scope.repo_id,
        latest_openapi.id AS snapshot_revision_id
    FROM repos_in_scope
    JOIN head_processed ON head_processed.repo_id = repos_in_scope.repo_id
    JOIN LATERAL (
        SELECT id
        FROM ingest_events
        WHERE ingest_events.repo_id = repos_in_scope.repo_id
          AND ingest_events.branch = repos_in_scope.default_branch
          AND ingest_events.status = 'processed'
          AND ingest_events.openapi_changed = TRUE
        ORDER BY ingest_events.processed_at DESC NULLS LAST, ingest_events.id DESC
        LIMIT 1
    ) AS latest_openapi ON TRUE
),
repo_specs AS (
    SELECT
        api_specs.id AS api_spec_id,
        api_specs.repo_id,
        api_specs.root_path AS api,
        api_specs.status
    FROM api_specs
    JOIN repos_in_scope ON repos_in_scope.repo_id = api_specs.repo_id
    WHERE api_specs.status = 'active'
)
SELECT
    repos_in_scope.namespace,
    repos_in_scope.repo,
    repo_specs.api_spec_id,
    repo_specs.api,
    repo_specs.status,
    api_spec_revisions.id AS api_spec_revision_id,
    ingest_events.id AS ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed_openapi
JOIN repos_in_scope ON repos_in_scope.repo_id = latest_processed_openapi.repo_id
JOIN repo_specs ON repo_specs.repo_id = latest_processed_openapi.repo_id
JOIN api_spec_revisions
  ON api_spec_revisions.api_spec_id = repo_specs.api_spec_id
 AND api_spec_revisions.ingest_event_id = latest_processed_openapi.snapshot_revision_id
 AND api_spec_revisions.build_status = 'processed'
JOIN ingest_events ON ingest_events.id = api_spec_revisions.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = api_spec_revisions.id
WHERE (
    $1::TEXT = ''
    OR (UPPER(TRIM(endpoint_index.method)) || ' ' || TRIM(endpoint_index.path)) ILIKE $1::TEXT || '%'
    OR COALESCE(endpoint_index.operation_id, '') ILIKE $1::TEXT || '%'
)
ORDER BY repos_in_scope.namespace ASC, repos_in_scope.repo ASC, repo_specs.api ASC, endpoint_index.method ASC, endpoint_index.path ASC
LIMIT $3
OFFSET $2
`

type ListOperationCatalogInventoryPageParams struct {
	QueryPrefix string `json:"query_prefix"`
	PageOffset  int32  `json:"page_offset"`
	PageLimit   int32  `json:"page_limit"`
	Namespace   string `json:"namespace"`
	Repo        string `json:"repo"`
}

type ListOperationCatalogInventoryPageRow struct {
	Namespace         string      `json:"namespace"`
	Repo              string      `json:"repo"`
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) ListOperationCatalogInventoryPage(ctx context.Context, arg ListOperationCatalogInventoryPageParams) ([]ListOperationCatalogInventoryPageRow, error) {
	rows, err := q.db.Query(ctx, listOperationCatalogInventoryPage,
		arg.QueryPrefix,
		arg.PageOffset,
		arg.PageLimit,
		arg.Namespace,
		arg.Repo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperationCatalogInventoryPageRow{}
	for rows.Next() {
		var i ListOperationCatalogInventoryPageRow
		if err := rows.Scan(
			&i.Namespace,
			&i.Repo,
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationInventoryByRepoRevision = `-- name: ListOperationInventoryByRepoRevision :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $1
      AND ingest_events.id = $2
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $1
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed
JOIN repo_specs ON repo_specs.id = latest_processed.api_spec_id
JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
ORDER BY repo_specs.root_path ASC, endpoint_index.method ASC, endpoint_index.path ASC
`

type ListOperationInventoryByRepoRevisionParams struct {
	RepoID             int64 `json:"repo_id"`
	SnapshotRevisionID int64 `json:"snapshot_revision_id"`
}

type ListOperationInventoryByRepoRevisionRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) ListOperationInventoryByRepoRevision(ctx context.Context, arg ListOperationInventoryByRepoRevisionParams) ([]ListOperationInventoryByRepoRevisionRow, error) {
	rows, err := q.db.Query(ctx, listOperationInventoryByRepoRevision, arg.RepoID, arg.SnapshotRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperationInventoryByRepoRevisionRow{}
	for rows.Next() {
		var i ListOperationInventoryByRepoRevisionRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationInventoryByRepoRevisionAndAPI = `-- name: ListOperationInventoryByRepoRevisionAndAPI :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $1
      AND ingest_events.id = $2
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $1
      AND api_specs.root_path = $3
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed
JOIN repo_specs ON repo_specs.id = latest_processed.api_spec_id
JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
ORDER BY endpoint_index.method ASC, endpoint_index.path ASC
`

type ListOperationInventoryByRepoRevisionAndAPIParams struct {
	RepoID             int64  `json:"repo_id"`
	SnapshotRevisionID int64  `json:"snapshot_revision_id"`
	Api                string `json:"api"`
}

type ListOperationInventoryByRepoRevisionAndAPIRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) ListOperationInventoryByRepoRevisionAndAPI(ctx context.Context, arg ListOperationInventoryByRepoRevisionAndAPIParams) ([]ListOperationInventoryByRepoRevisionAndAPIRow, error) {
	rows, err := q.db.Query(ctx, listOperationInventoryByRepoRevisionAndAPI, arg.RepoID, arg.SnapshotRevisionID, arg.Api)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperationInventoryByRepoRevisionAndAPIRow{}
	for rows.Next() {
		var i ListOperationInventoryByRepoRevisionAndAPIRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationInventoryByRepoRevisionAndAPIPage = `-- name: ListOperationInventoryByRepoRevisionAndAPIPage :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $4
      AND ingest_events.id = $5
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $4
      AND api_specs.root_path = $6
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed
JOIN repo_specs ON repo_specs.id = latest_processed.api_spec_id
JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
WHERE (
    $1::TEXT = ''
    OR (UPPER(TRIM(endpoint_index.method)) || ' ' || TRIM(endpoint_index.path)) ILIKE $1::TEXT || '%'
    OR COALESCE(endpoint_index.operation_id, '') ILIKE $1::TEXT || '%'
)
ORDER BY endpoint_index.method ASC, endpoint_index.path ASC
LIMIT $3
OFFSET $2
`

type ListOperationInventoryByRepoRevisionAndAPIPageParams struct {
	QueryPrefix        string `json:"query_prefix"`
	PageOffset         int32  `json:"page_offset"`
	PageLimit          int32  `json:"page_limit"`
	RepoID             int64  `json:"repo_id"`
	SnapshotRevisionID int64  `json:"snapshot_revision_id"`
	Api                string `json:"api"`
}

type ListOperationInventoryByRepoRevisionAndAPIPageRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) ListOperationInventoryByRepoRevisionAndAPIPage(ctx context.Context, arg ListOperationInventoryByRepoRevisionAndAPIPageParams) ([]ListOperationInventoryByRepoRevisionAndAPIPageRow, error) {
	rows, err := q.db.Query(ctx, listOperationInventoryByRepoRevisionAndAPIPage,
		arg.QueryPrefix,
		arg.PageOffset,
		arg.PageLimit,
		arg.RepoID,
		arg.SnapshotRevisionID,
		arg.Api,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperationInventoryByRepoRevisionAndAPIPageRow{}
	for rows.Next() {
		var i ListOperationInventoryByRepoRevisionAndAPIPageRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationInventoryByRepoRevisionPage = `-- name: ListOperationInventoryByRepoRevisionPage :many
WITH RECURSIVE snapshot_ancestors AS (
    SELECT id, repo_id, sha, parent_sha, 0::BIGINT AS distance
    FROM ingest_events
    WHERE ingest_events.repo_id = $4
      AND ingest_events.id = $5
    UNION ALL
    SELECT parent.id, parent.repo_id, parent.sha, parent.parent_sha, snapshot_ancestors.distance + 1
    FROM ingest_events AS parent
    JOIN snapshot_ancestors
      ON parent.repo_id = snapshot_ancestors.repo_id
     AND parent.sha = snapshot_ancestors.parent_sha
),
repo_specs AS (
    SELECT id, root_path, status
    FROM api_specs
    WHERE api_specs.repo_id = $4
),
latest_processed AS (
    SELECT DISTINCT ON (api_spec_revisions.api_spec_id)
        api_spec_revisions.api_spec_id,
        api_spec_revisions.id AS api_spec_revision_id,
        api_spec_revisions.ingest_event_id
    FROM api_spec_revisions
    JOIN repo_specs ON repo_specs.id = api_spec_revisions.api_spec_id
    JOIN snapshot_ancestors ON snapshot_ancestors.id = api_spec_revisions.ingest_event_id
    WHERE api_spec_revisions.build_status = 'processed'
    ORDER BY api_spec_revisions.api_spec_id, snapshot_ancestors.distance ASC, api_spec_revisions.id DESC
)
SELECT
    repo_specs.id AS api_spec_id,
    repo_specs.root_path AS api,
    repo_specs.status,
    latest_processed.api_spec_revision_id,
    latest_processed.ingest_event_id,
    ingest_events.sha AS ingest_event_sha,
    ingest_events.branch AS ingest_event_branch,
    endpoint_index.method,
    endpoint_index.path,
    endpoint_index.operation_id,
    endpoint_index.summary,
    endpoint_index.deprecated,
    endpoint_index.raw_json
FROM latest_processed
JOIN repo_specs ON repo_specs.id = latest_processed.api_spec_id
JOIN ingest_events ON ingest_events.id = latest_processed.ingest_event_id
JOIN endpoint_index ON endpoint_index.api_spec_revision_id = latest_processed.api_spec_revision_id
WHERE (
    $1::TEXT = ''
    OR (UPPER(TRIM(endpoint_index.method)) || ' ' || TRIM(endpoint_index.path)) ILIKE $1::TEXT || '%'
    OR COALESCE(endpoint_index.operation_id, '') ILIKE $1::TEXT || '%'
)
ORDER BY repo_specs.root_path ASC, endpoint_index.method ASC, endpoint_index.path ASC
LIMIT $3
OFFSET $2
`

type ListOperationInventoryByRepoRevisionPageParams struct {
	QueryPrefix        string `json:"query_prefix"`
	PageOffset         int32  `json:"page_offset"`
	PageLimit          int32  `json:"page_limit"`
	RepoID             int64  `json:"repo_id"`
	SnapshotRevisionID int64  `json:"snapshot_revision_id"`
}

type ListOperationInventoryByRepoRevisionPageRow struct {
	ApiSpecID         int64       `json:"api_spec_id"`
	Api               string      `json:"api"`
	Status            string      `json:"status"`
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	IngestEventID     int64       `json:"ingest_event_id"`
	IngestEventSha    string      `json:"ingest_event_sha"`
	IngestEventBranch string      `json:"ingest_event_branch"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) ListOperationInventoryByRepoRevisionPage(ctx context.Context, arg ListOperationInventoryByRepoRevisionPageParams) ([]ListOperationInventoryByRepoRevisionPageRow, error) {
	rows, err := q.db.Query(ctx, listOperationInventoryByRepoRevisionPage,
		arg.QueryPrefix,
		arg.PageOffset,
		arg.PageLimit,
		arg.RepoID,
		arg.SnapshotRevisionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperationInventoryByRepoRevisionPageRow{}
	for rows.Next() {
		var i ListOperationInventoryByRepoRevisionPageRow
		if err := rows.Scan(
			&i.ApiSpecID,
			&i.Api,
			&i.Status,
			&i.ApiSpecRevisionID,
			&i.IngestEventID,
			&i.IngestEventSha,
			&i.IngestEventBranch,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoCatalogInventory = `-- name: ListRepoCatalogInventory :many
SELECT
    repos.id,
    repos.gitlab_project_id,
    namespaces.namespace,
    repos.repo,
    repos.default_branch,
    repos.openapi_force_rescan,
    COALESCE(active_api_counts.active_api_count, 0)::BIGINT AS active_api_count,
    (head.id IS NOT NULL) AS head_present,
    COALESCE(head.id, 0)::BIGINT AS head_revision_id,
    COALESCE(head.sha, '')::TEXT AS head_revision_sha,
    COALESCE(head.status, '')::TEXT AS head_revision_status,
    head.openapi_changed AS head_revision_openapi_changed,
    COALESCE(head.received_at, TIMESTAMPTZ 'epoch') AS head_revision_received_at,
    head.processed_at AS head_revision_processed_at,
    (latest_openapi.id IS NOT NULL) AS snapshot_present,
    COALESCE(latest_openapi.id, 0)::BIGINT AS snapshot_revision_id,
    COALESCE(latest_openapi.sha, '')::TEXT AS snapshot_revision_sha,
    latest_openapi.processed_at AS snapshot_revision_processed_at
FROM repos
JOIN namespaces ON namespaces.id = repos.namespace_id
LEFT JOIN LATERAL (
    SELECT COUNT(*)::BIGINT AS active_api_count
    FROM api_specs
    WHERE api_specs.repo_id = repos.id
      AND api_specs.status = 'active'
) AS active_api_counts ON TRUE
LEFT JOIN LATERAL (
    SELECT id, sha, status, openapi_changed, received_at, processed_at
    FROM ingest_events
    WHERE ingest_events.repo_id = repos.id
      AND ingest_events.branch = repos.default_branch
    ORDER BY ingest_events.received_at DESC, ingest_events.id DESC
    LIMIT 1
) AS head ON TRUE
LEFT JOIN LATERAL (
    SELECT id, sha, processed_at
    FROM ingest_events
    WHERE ingest_events.repo_id = repos.id
      AND ingest_events.branch = repos.default_branch
      AND ingest_events.status = 'processed'
      AND ingest_events.openapi_changed = TRUE
    ORDER BY ingest_events.processed_at DESC NULLS LAST, ingest_events.id DESC
    LIMIT 1
) AS latest_openapi ON TRUE
WHERE EXISTS (
    SELECT 1
    FROM api_specs
    WHERE api_specs.repo_id = repos.id
      AND api_specs.status = 'active'
)
ORDER BY namespaces.namespace ASC, repos.repo ASC
`

type ListRepoCatalogInventoryRow struct {
	ID                          int64              `json:"id"`
	GitlabProjectID             int64              `json:"gitlab_project_id"`
	Namespace                   string             `json:"namespace"`
	Repo                        string             `json:"repo"`
	DefaultBranch               string             `json:"default_branch"`
	OpenapiForceRescan          bool               `json:"openapi_force_rescan"`
	ActiveApiCount              int64              `json:"active_api_count"`
	HeadPresent                 interface{}        `json:"head_present"`
	HeadRevisionID              int64              `json:"head_revision_id"`
	HeadRevisionSha             string             `json:"head_revision_sha"`
	HeadRevisionStatus          string             `json:"head_revision_status"`
	HeadRevisionOpenapiChanged  pgtype.Bool        `json:"head_revision_openapi_changed"`
	HeadRevisionReceivedAt      pgtype.Timestamptz `json:"head_revision_received_at"`
	HeadRevisionProcessedAt     pgtype.Timestamptz `json:"head_revision_processed_at"`
	SnapshotPresent             interface{}        `json:"snapshot_present"`
	SnapshotRevisionID          int64              `json:"snapshot_revision_id"`
	SnapshotRevisionSha         string             `json:"snapshot_revision_sha"`
	SnapshotRevisionProcessedAt pgtype.Timestamptz `json:"snapshot_revision_processed_at"`
}

func (q *Queries) ListRepoCatalogInventory(ctx context.Context) ([]ListRepoCatalogInventoryRow, error) {
	rows, err := q.db.Query(ctx, listRepoCatalogInventory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepoCatalogInventoryRow{}
	for rows.Next() {
		var i ListRepoCatalogInventoryRow
		if err := rows.Scan(
			&i.ID,
			&i.GitlabProjectID,
			&i.Namespace,
			&i.Repo,
			&i.DefaultBranch,
			&i.OpenapiForceRescan,
			&i.ActiveApiCount,
			&i.HeadPresent,
			&i.HeadRevisionID,
			&i.HeadRevisionSha,
			&i.HeadRevisionStatus,
			&i.HeadRevisionOpenapiChanged,
			&i.HeadRevisionReceivedAt,
			&i.HeadRevisionProcessedAt,
			&i.SnapshotPresent,
			&i.SnapshotRevisionID,
			&i.SnapshotRevisionSha,
			&i.SnapshotRevisionProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
