// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delivery_attempts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeliveryAttempt = `-- name: CreateDeliveryAttempt :one
INSERT INTO delivery_attempts (
    subscription_id,
    revision_id,
    event_type,
    attempt_no,
    status,
    next_retry_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, subscription_id, revision_id, event_type, attempt_no, status, response_code, error, next_retry_at, created_at, updated_at
`

type CreateDeliveryAttemptParams struct {
	SubscriptionID int64              `json:"subscription_id"`
	RevisionID     int64              `json:"revision_id"`
	EventType      string             `json:"event_type"`
	AttemptNo      int32              `json:"attempt_no"`
	Status         string             `json:"status"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (DeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, createDeliveryAttempt,
		arg.SubscriptionID,
		arg.RevisionID,
		arg.EventType,
		arg.AttemptNo,
		arg.Status,
		arg.NextRetryAt,
	)
	var i DeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.RevisionID,
		&i.EventType,
		&i.AttemptNo,
		&i.Status,
		&i.ResponseCode,
		&i.Error,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueDeliveryAttempts = `-- name: ListDueDeliveryAttempts :many
SELECT id, subscription_id, revision_id, event_type, attempt_no, status, response_code, error, next_retry_at, created_at, updated_at
FROM delivery_attempts
WHERE status IN ('pending', 'retry_scheduled')
  AND (next_retry_at IS NULL OR next_retry_at <= NOW())
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListDueDeliveryAttempts(ctx context.Context, limitCount int32) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listDueDeliveryAttempts, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryAttempt{}
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.RevisionID,
			&i.EventType,
			&i.AttemptNo,
			&i.Status,
			&i.ResponseCode,
			&i.Error,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeliveryAttemptResult = `-- name: UpdateDeliveryAttemptResult :one
UPDATE delivery_attempts
SET status = $1,
    response_code = $2,
    error = $3,
    next_retry_at = $4,
    updated_at = NOW()
WHERE id = $5
RETURNING id, subscription_id, revision_id, event_type, attempt_no, status, response_code, error, next_retry_at, created_at, updated_at
`

type UpdateDeliveryAttemptResultParams struct {
	Status       string             `json:"status"`
	ResponseCode pgtype.Int4        `json:"response_code"`
	Error        string             `json:"error"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
	ID           int64              `json:"id"`
}

func (q *Queries) UpdateDeliveryAttemptResult(ctx context.Context, arg UpdateDeliveryAttemptResultParams) (DeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, updateDeliveryAttemptResult,
		arg.Status,
		arg.ResponseCode,
		arg.Error,
		arg.NextRetryAt,
		arg.ID,
	)
	var i DeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.RevisionID,
		&i.EventType,
		&i.AttemptNo,
		&i.Status,
		&i.ResponseCode,
		&i.Error,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
