// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: endpoint_index.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEndpointIndexByRevision = `-- name: DeleteEndpointIndexByRevision :exec
DELETE FROM endpoint_index
WHERE revision_id = $1
`

func (q *Queries) DeleteEndpointIndexByRevision(ctx context.Context, revisionID int64) error {
	_, err := q.db.Exec(ctx, deleteEndpointIndexByRevision, revisionID)
	return err
}

const getEndpointByMethodPath = `-- name: GetEndpointByMethodPath :one
SELECT id, revision_id, method, path, operation_id, summary, deprecated, raw_json, created_at
FROM endpoint_index
WHERE revision_id = $1
  AND method = $2
  AND path = $3
`

type GetEndpointByMethodPathParams struct {
	RevisionID int64  `json:"revision_id"`
	Method     string `json:"method"`
	Path       string `json:"path"`
}

func (q *Queries) GetEndpointByMethodPath(ctx context.Context, arg GetEndpointByMethodPathParams) (EndpointIndex, error) {
	row := q.db.QueryRow(ctx, getEndpointByMethodPath, arg.RevisionID, arg.Method, arg.Path)
	var i EndpointIndex
	err := row.Scan(
		&i.ID,
		&i.RevisionID,
		&i.Method,
		&i.Path,
		&i.OperationID,
		&i.Summary,
		&i.Deprecated,
		&i.RawJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertEndpointIndex = `-- name: InsertEndpointIndex :one
INSERT INTO endpoint_index (
    revision_id,
    method,
    path,
    operation_id,
    summary,
    deprecated,
    raw_json
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, revision_id, method, path, operation_id, summary, deprecated, raw_json, created_at
`

type InsertEndpointIndexParams struct {
	RevisionID  int64       `json:"revision_id"`
	Method      string      `json:"method"`
	Path        string      `json:"path"`
	OperationID pgtype.Text `json:"operation_id"`
	Summary     pgtype.Text `json:"summary"`
	Deprecated  bool        `json:"deprecated"`
	RawJson     []byte      `json:"raw_json"`
}

func (q *Queries) InsertEndpointIndex(ctx context.Context, arg InsertEndpointIndexParams) (EndpointIndex, error) {
	row := q.db.QueryRow(ctx, insertEndpointIndex,
		arg.RevisionID,
		arg.Method,
		arg.Path,
		arg.OperationID,
		arg.Summary,
		arg.Deprecated,
		arg.RawJson,
	)
	var i EndpointIndex
	err := row.Scan(
		&i.ID,
		&i.RevisionID,
		&i.Method,
		&i.Path,
		&i.OperationID,
		&i.Summary,
		&i.Deprecated,
		&i.RawJson,
		&i.CreatedAt,
	)
	return i, err
}

const listEndpointIndexByRevision = `-- name: ListEndpointIndexByRevision :many
SELECT id, revision_id, method, path, operation_id, summary, deprecated, raw_json, created_at
FROM endpoint_index
WHERE revision_id = $1
ORDER BY method, path
`

func (q *Queries) ListEndpointIndexByRevision(ctx context.Context, revisionID int64) ([]EndpointIndex, error) {
	rows, err := q.db.Query(ctx, listEndpointIndexByRevision, revisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EndpointIndex{}
	for rows.Next() {
		var i EndpointIndex
		if err := rows.Scan(
			&i.ID,
			&i.RevisionID,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
