// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: endpoint_index.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEndpointIndexByAPISpecRevision = `-- name: DeleteEndpointIndexByAPISpecRevision :exec
DELETE FROM endpoint_index
WHERE api_spec_revision_id = $1
`

func (q *Queries) DeleteEndpointIndexByAPISpecRevision(ctx context.Context, apiSpecRevisionID int64) error {
	_, err := q.db.Exec(ctx, deleteEndpointIndexByAPISpecRevision, apiSpecRevisionID)
	return err
}

const getEndpointByMethodPathForAPISpecRevision = `-- name: GetEndpointByMethodPathForAPISpecRevision :one
SELECT id, api_spec_revision_id, method, path, operation_id, summary, deprecated, raw_json, created_at
FROM endpoint_index
WHERE api_spec_revision_id = $1
  AND method = $2
  AND path = $3
`

type GetEndpointByMethodPathForAPISpecRevisionParams struct {
	ApiSpecRevisionID int64  `json:"api_spec_revision_id"`
	Method            string `json:"method"`
	Path              string `json:"path"`
}

func (q *Queries) GetEndpointByMethodPathForAPISpecRevision(ctx context.Context, arg GetEndpointByMethodPathForAPISpecRevisionParams) (EndpointIndex, error) {
	row := q.db.QueryRow(ctx, getEndpointByMethodPathForAPISpecRevision, arg.ApiSpecRevisionID, arg.Method, arg.Path)
	var i EndpointIndex
	err := row.Scan(
		&i.ID,
		&i.ApiSpecRevisionID,
		&i.Method,
		&i.Path,
		&i.OperationID,
		&i.Summary,
		&i.Deprecated,
		&i.RawJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertEndpointIndex = `-- name: InsertEndpointIndex :one
INSERT INTO endpoint_index (
    api_spec_revision_id,
    method,
    path,
    operation_id,
    summary,
    deprecated,
    raw_json
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, api_spec_revision_id, method, path, operation_id, summary, deprecated, raw_json, created_at
`

type InsertEndpointIndexParams struct {
	ApiSpecRevisionID int64       `json:"api_spec_revision_id"`
	Method            string      `json:"method"`
	Path              string      `json:"path"`
	OperationID       pgtype.Text `json:"operation_id"`
	Summary           pgtype.Text `json:"summary"`
	Deprecated        bool        `json:"deprecated"`
	RawJson           []byte      `json:"raw_json"`
}

func (q *Queries) InsertEndpointIndex(ctx context.Context, arg InsertEndpointIndexParams) (EndpointIndex, error) {
	row := q.db.QueryRow(ctx, insertEndpointIndex,
		arg.ApiSpecRevisionID,
		arg.Method,
		arg.Path,
		arg.OperationID,
		arg.Summary,
		arg.Deprecated,
		arg.RawJson,
	)
	var i EndpointIndex
	err := row.Scan(
		&i.ID,
		&i.ApiSpecRevisionID,
		&i.Method,
		&i.Path,
		&i.OperationID,
		&i.Summary,
		&i.Deprecated,
		&i.RawJson,
		&i.CreatedAt,
	)
	return i, err
}

const listEndpointIndexByAPISpecRevision = `-- name: ListEndpointIndexByAPISpecRevision :many
SELECT id, api_spec_revision_id, method, path, operation_id, summary, deprecated, raw_json, created_at
FROM endpoint_index
WHERE api_spec_revision_id = $1
ORDER BY method, path
`

func (q *Queries) ListEndpointIndexByAPISpecRevision(ctx context.Context, apiSpecRevisionID int64) ([]EndpointIndex, error) {
	rows, err := q.db.Query(ctx, listEndpointIndexByAPISpecRevision, apiSpecRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EndpointIndex{}
	for rows.Next() {
		var i EndpointIndex
		if err := rows.Scan(
			&i.ID,
			&i.ApiSpecRevisionID,
			&i.Method,
			&i.Path,
			&i.OperationID,
			&i.Summary,
			&i.Deprecated,
			&i.RawJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
