// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingest_events.sql

package sqlc

import (
	"context"
)

const createIngestEvent = `-- name: CreateIngestEvent :one
INSERT INTO ingest_events (
    tenant_id,
    repo_id,
    event_type,
    delivery_id,
    payload_json
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, tenant_id, repo_id, event_type, delivery_id, payload_json, received_at, status, error
`

type CreateIngestEventParams struct {
	TenantID    int64  `json:"tenant_id"`
	RepoID      int64  `json:"repo_id"`
	EventType   string `json:"event_type"`
	DeliveryID  string `json:"delivery_id"`
	PayloadJson []byte `json:"payload_json"`
}

func (q *Queries) CreateIngestEvent(ctx context.Context, arg CreateIngestEventParams) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, createIngestEvent,
		arg.TenantID,
		arg.RepoID,
		arg.EventType,
		arg.DeliveryID,
		arg.PayloadJson,
	)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RepoID,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const getIngestEventByRepoDelivery = `-- name: GetIngestEventByRepoDelivery :one
SELECT id, tenant_id, repo_id, event_type, delivery_id, payload_json, received_at, status, error
FROM ingest_events
WHERE repo_id = $1
  AND delivery_id = $2
`

type GetIngestEventByRepoDeliveryParams struct {
	RepoID     int64  `json:"repo_id"`
	DeliveryID string `json:"delivery_id"`
}

func (q *Queries) GetIngestEventByRepoDelivery(ctx context.Context, arg GetIngestEventByRepoDeliveryParams) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, getIngestEventByRepoDelivery, arg.RepoID, arg.DeliveryID)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RepoID,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const listPendingIngestEvents = `-- name: ListPendingIngestEvents :many
SELECT id, tenant_id, repo_id, event_type, delivery_id, payload_json, received_at, status, error
FROM ingest_events
WHERE status = 'pending'
ORDER BY received_at
LIMIT $1
`

func (q *Queries) ListPendingIngestEvents(ctx context.Context, limitCount int32) ([]IngestEvent, error) {
	rows, err := q.db.Query(ctx, listPendingIngestEvents, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestEvent{}
	for rows.Next() {
		var i IngestEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RepoID,
			&i.EventType,
			&i.DeliveryID,
			&i.PayloadJson,
			&i.ReceivedAt,
			&i.Status,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngestEventStatus = `-- name: UpdateIngestEventStatus :one
UPDATE ingest_events
SET status = $1,
    error = $2
WHERE id = $3
RETURNING id, tenant_id, repo_id, event_type, delivery_id, payload_json, received_at, status, error
`

type UpdateIngestEventStatusParams struct {
	Status string `json:"status"`
	Error  string `json:"error"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateIngestEventStatus(ctx context.Context, arg UpdateIngestEventStatusParams) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, updateIngestEventStatus, arg.Status, arg.Error, arg.ID)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RepoID,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.Status,
		&i.Error,
	)
	return i, err
}
