// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingest_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextIngestEvent = `-- name: ClaimNextIngestEvent :one
WITH candidate AS (
    SELECT id
    FROM ingest_events AS ie
    WHERE ie.status = 'pending'
      AND ie.next_retry_at <= NOW()
      AND NOT EXISTS (
          SELECT 1
          FROM ingest_events AS older
          WHERE older.repo_id = ie.repo_id
            AND older.id < ie.id
            AND older.status IN ('pending', 'processing')
      )
    ORDER BY ie.id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE ingest_events
SET status = 'processing',
    attempt_count = ingest_events.attempt_count + 1,
    error = ''
FROM candidate
WHERE ingest_events.id = candidate.id
RETURNING ingest_events.id, ingest_events.repo_id, ingest_events.sha, ingest_events.branch, ingest_events.parent_sha, ingest_events.event_type, ingest_events.delivery_id, ingest_events.payload_json, ingest_events.received_at, ingest_events.attempt_count, ingest_events.next_retry_at, ingest_events.processed_at, ingest_events.openapi_changed, ingest_events.status, ingest_events.error
`

func (q *Queries) ClaimNextIngestEvent(ctx context.Context) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, claimNextIngestEvent)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const createIngestEvent = `-- name: CreateIngestEvent :one
INSERT INTO ingest_events (
    repo_id,
    sha,
    branch,
    parent_sha,
    event_type,
    delivery_id,
    payload_json
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, repo_id, sha, branch, parent_sha, event_type, delivery_id, payload_json, received_at, attempt_count, next_retry_at, processed_at, openapi_changed, status, error
`

type CreateIngestEventParams struct {
	RepoID      int64       `json:"repo_id"`
	Sha         string      `json:"sha"`
	Branch      string      `json:"branch"`
	ParentSha   pgtype.Text `json:"parent_sha"`
	EventType   string      `json:"event_type"`
	DeliveryID  string      `json:"delivery_id"`
	PayloadJson []byte      `json:"payload_json"`
}

func (q *Queries) CreateIngestEvent(ctx context.Context, arg CreateIngestEventParams) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, createIngestEvent,
		arg.RepoID,
		arg.Sha,
		arg.Branch,
		arg.ParentSha,
		arg.EventType,
		arg.DeliveryID,
		arg.PayloadJson,
	)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const getIngestEventByRepoDelivery = `-- name: GetIngestEventByRepoDelivery :one
SELECT id, repo_id, sha, branch, parent_sha, event_type, delivery_id, payload_json, received_at, attempt_count, next_retry_at, processed_at, openapi_changed, status, error
FROM ingest_events
WHERE repo_id = $1
  AND delivery_id = $2
`

type GetIngestEventByRepoDeliveryParams struct {
	RepoID     int64  `json:"repo_id"`
	DeliveryID string `json:"delivery_id"`
}

func (q *Queries) GetIngestEventByRepoDelivery(ctx context.Context, arg GetIngestEventByRepoDeliveryParams) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, getIngestEventByRepoDelivery, arg.RepoID, arg.DeliveryID)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const getIngestEventByRepoSHA = `-- name: GetIngestEventByRepoSHA :one
SELECT id, repo_id, sha, branch, parent_sha, event_type, delivery_id, payload_json, received_at, attempt_count, next_retry_at, processed_at, openapi_changed, status, error
FROM ingest_events
WHERE repo_id = $1
  AND sha = $2
`

type GetIngestEventByRepoSHAParams struct {
	RepoID int64  `json:"repo_id"`
	Sha    string `json:"sha"`
}

func (q *Queries) GetIngestEventByRepoSHA(ctx context.Context, arg GetIngestEventByRepoSHAParams) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, getIngestEventByRepoSHA, arg.RepoID, arg.Sha)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const markIngestEventFailed = `-- name: MarkIngestEventFailed :one
UPDATE ingest_events
SET status = 'failed',
    processed_at = NOW(),
    openapi_changed = NULL,
    error = $1
WHERE id = $2
RETURNING id, repo_id, sha, branch, parent_sha, event_type, delivery_id, payload_json, received_at, attempt_count, next_retry_at, processed_at, openapi_changed, status, error
`

type MarkIngestEventFailedParams struct {
	Error string `json:"error"`
	ID    int64  `json:"id"`
}

func (q *Queries) MarkIngestEventFailed(ctx context.Context, arg MarkIngestEventFailedParams) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, markIngestEventFailed, arg.Error, arg.ID)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const markIngestEventProcessed = `-- name: MarkIngestEventProcessed :one
UPDATE ingest_events
SET status = 'processed',
    processed_at = NOW(),
    openapi_changed = $1,
    error = ''
WHERE id = $2
RETURNING id, repo_id, sha, branch, parent_sha, event_type, delivery_id, payload_json, received_at, attempt_count, next_retry_at, processed_at, openapi_changed, status, error
`

type MarkIngestEventProcessedParams struct {
	OpenapiChanged pgtype.Bool `json:"openapi_changed"`
	ID             int64       `json:"id"`
}

func (q *Queries) MarkIngestEventProcessed(ctx context.Context, arg MarkIngestEventProcessedParams) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, markIngestEventProcessed, arg.OpenapiChanged, arg.ID)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const scheduleIngestEventRetry = `-- name: ScheduleIngestEventRetry :one
UPDATE ingest_events
SET status = 'pending',
    error = $1,
    next_retry_at = $2
WHERE id = $3
RETURNING id, repo_id, sha, branch, parent_sha, event_type, delivery_id, payload_json, received_at, attempt_count, next_retry_at, processed_at, openapi_changed, status, error
`

type ScheduleIngestEventRetryParams struct {
	Error       string             `json:"error"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	ID          int64              `json:"id"`
}

func (q *Queries) ScheduleIngestEventRetry(ctx context.Context, arg ScheduleIngestEventRetryParams) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, scheduleIngestEventRetry, arg.Error, arg.NextRetryAt, arg.ID)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
	)
	return i, err
}
