// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiSpec struct {
	ID          int64              `json:"id"`
	RepoID      int64              `json:"repo_id"`
	RootPath    string             `json:"root_path"`
	Status      string             `json:"status"`
	DisplayName pgtype.Text        `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ApiSpecDependency struct {
	ApiSpecRevisionID int64  `json:"api_spec_revision_id"`
	FilePath          string `json:"file_path"`
}

type ApiSpecRevision struct {
	ID                 int64              `json:"id"`
	ApiSpecID          int64              `json:"api_spec_id"`
	IngestEventID      int64              `json:"ingest_event_id"`
	RootPathAtRevision string             `json:"root_path_at_revision"`
	BuildStatus        string             `json:"build_status"`
	Error              string             `json:"error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type DeliveryAttempt struct {
	ID             int64              `json:"id"`
	SubscriptionID int64              `json:"subscription_id"`
	ApiSpecID      int64              `json:"api_spec_id"`
	IngestEventID  int64              `json:"ingest_event_id"`
	EventType      string             `json:"event_type"`
	AttemptNo      int32              `json:"attempt_no"`
	Status         string             `json:"status"`
	ResponseCode   pgtype.Int4        `json:"response_code"`
	Error          string             `json:"error"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type EndpointIndex struct {
	ID                int64              `json:"id"`
	ApiSpecRevisionID int64              `json:"api_spec_revision_id"`
	Method            string             `json:"method"`
	Path              string             `json:"path"`
	OperationID       pgtype.Text        `json:"operation_id"`
	Summary           pgtype.Text        `json:"summary"`
	Deprecated        bool               `json:"deprecated"`
	RawJson           []byte             `json:"raw_json"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type IngestEvent struct {
	ID             int64              `json:"id"`
	RepoID         int64              `json:"repo_id"`
	Sha            string             `json:"sha"`
	Branch         string             `json:"branch"`
	ParentSha      pgtype.Text        `json:"parent_sha"`
	EventType      string             `json:"event_type"`
	DeliveryID     string             `json:"delivery_id"`
	PayloadJson    []byte             `json:"payload_json"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
	AttemptCount   int32              `json:"attempt_count"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	OpenapiChanged pgtype.Bool        `json:"openapi_changed"`
	Status         string             `json:"status"`
	Error          string             `json:"error"`
}

type Repo struct {
	ID                 int64              `json:"id"`
	GitlabProjectID    int64              `json:"gitlab_project_id"`
	PathWithNamespace  string             `json:"path_with_namespace"`
	DefaultBranch      string             `json:"default_branch"`
	OpenapiForceRescan bool               `json:"openapi_force_rescan"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type SchemaMigration struct {
	Version   string             `json:"version"`
	Checksum  string             `json:"checksum"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

type SpecArtifact struct {
	ID                int64              `json:"id"`
	ApiSpecRevisionID int64              `json:"api_spec_revision_id"`
	SpecJson          []byte             `json:"spec_json"`
	SpecYaml          string             `json:"spec_yaml"`
	Etag              string             `json:"etag"`
	SizeBytes         int64              `json:"size_bytes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type SpecChange struct {
	ID                    int64              `json:"id"`
	ApiSpecID             int64              `json:"api_spec_id"`
	FromApiSpecRevisionID pgtype.Int8        `json:"from_api_spec_revision_id"`
	ToApiSpecRevisionID   int64              `json:"to_api_spec_revision_id"`
	ChangeJson            []byte             `json:"change_json"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type StartupIndexState struct {
	Singleton     bool               `json:"singleton"`
	LastProjectID int64              `json:"last_project_id"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Subscription struct {
	ID                    int64              `json:"id"`
	RepoID                int64              `json:"repo_id"`
	TargetUrl             string             `json:"target_url"`
	Secret                string             `json:"secret"`
	Enabled               bool               `json:"enabled"`
	MaxAttempts           int32              `json:"max_attempts"`
	BackoffInitialSeconds int32              `json:"backoff_initial_seconds"`
	BackoffMaxSeconds     int32              `json:"backoff_max_seconds"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}
