// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeliveryAttempt struct {
	ID             int64              `json:"id"`
	SubscriptionID int64              `json:"subscription_id"`
	RevisionID     int64              `json:"revision_id"`
	EventType      string             `json:"event_type"`
	AttemptNo      int32              `json:"attempt_no"`
	Status         string             `json:"status"`
	ResponseCode   pgtype.Int4        `json:"response_code"`
	Error          string             `json:"error"`
	NextRetryAt    pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type EndpointIndex struct {
	ID          int64              `json:"id"`
	RevisionID  int64              `json:"revision_id"`
	Method      string             `json:"method"`
	Path        string             `json:"path"`
	OperationID pgtype.Text        `json:"operation_id"`
	Summary     pgtype.Text        `json:"summary"`
	Deprecated  bool               `json:"deprecated"`
	RawJson     []byte             `json:"raw_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type IngestEvent struct {
	ID           int64              `json:"id"`
	TenantID     int64              `json:"tenant_id"`
	RepoID       int64              `json:"repo_id"`
	Sha          string             `json:"sha"`
	Branch       string             `json:"branch"`
	ParentSha    pgtype.Text        `json:"parent_sha"`
	EventType    string             `json:"event_type"`
	DeliveryID   string             `json:"delivery_id"`
	PayloadJson  []byte             `json:"payload_json"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
	AttemptCount int32              `json:"attempt_count"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
	Status       string             `json:"status"`
	Error        string             `json:"error"`
}

type Repo struct {
	ID                int64              `json:"id"`
	TenantID          int64              `json:"tenant_id"`
	GitlabProjectID   int64              `json:"gitlab_project_id"`
	PathWithNamespace string             `json:"path_with_namespace"`
	DefaultBranch     string             `json:"default_branch"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Revision struct {
	ID             int64              `json:"id"`
	RepoID         int64              `json:"repo_id"`
	Sha            string             `json:"sha"`
	Branch         string             `json:"branch"`
	ParentSha      pgtype.Text        `json:"parent_sha"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	OpenapiChanged pgtype.Bool        `json:"openapi_changed"`
	Status         string             `json:"status"`
	Error          string             `json:"error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SpecArtifact struct {
	ID         int64              `json:"id"`
	RevisionID int64              `json:"revision_id"`
	SpecJson   []byte             `json:"spec_json"`
	SpecYaml   string             `json:"spec_yaml"`
	Etag       string             `json:"etag"`
	SizeBytes  int64              `json:"size_bytes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SpecChange struct {
	ID             int64              `json:"id"`
	RepoID         int64              `json:"repo_id"`
	FromRevisionID pgtype.Int8        `json:"from_revision_id"`
	ToRevisionID   int64              `json:"to_revision_id"`
	ChangeJson     []byte             `json:"change_json"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID                    int64              `json:"id"`
	TenantID              int64              `json:"tenant_id"`
	RepoID                int64              `json:"repo_id"`
	TargetUrl             string             `json:"target_url"`
	Secret                string             `json:"secret"`
	Enabled               bool               `json:"enabled"`
	MaxAttempts           int32              `json:"max_attempts"`
	BackoffInitialSeconds int32              `json:"backoff_initial_seconds"`
	BackoffMaxSeconds     int32              `json:"backoff_max_seconds"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID        int64              `json:"id"`
	Key       string             `json:"key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
