// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package sqlc

import (
	"context"
)

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (
    tenant_id,
    gitlab_project_id,
    path_with_namespace,
    default_branch
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, tenant_id, gitlab_project_id, path_with_namespace, default_branch, created_at, updated_at
`

type CreateRepoParams struct {
	TenantID          int64  `json:"tenant_id"`
	GitlabProjectID   int64  `json:"gitlab_project_id"`
	PathWithNamespace string `json:"path_with_namespace"`
	DefaultBranch     string `json:"default_branch"`
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, createRepo,
		arg.TenantID,
		arg.GitlabProjectID,
		arg.PathWithNamespace,
		arg.DefaultBranch,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByID = `-- name: GetRepoByID :one
SELECT id, tenant_id, gitlab_project_id, path_with_namespace, default_branch, created_at, updated_at
FROM repos
WHERE id = $1
`

func (q *Queries) GetRepoByID(ctx context.Context, id int64) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByID, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByTenantAndPath = `-- name: GetRepoByTenantAndPath :one
SELECT id, tenant_id, gitlab_project_id, path_with_namespace, default_branch, created_at, updated_at
FROM repos
WHERE tenant_id = $1
  AND path_with_namespace = $2
`

type GetRepoByTenantAndPathParams struct {
	TenantID          int64  `json:"tenant_id"`
	PathWithNamespace string `json:"path_with_namespace"`
}

func (q *Queries) GetRepoByTenantAndPath(ctx context.Context, arg GetRepoByTenantAndPathParams) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByTenantAndPath, arg.TenantID, arg.PathWithNamespace)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByTenantAndProjectID = `-- name: GetRepoByTenantAndProjectID :one
SELECT id, tenant_id, gitlab_project_id, path_with_namespace, default_branch, created_at, updated_at
FROM repos
WHERE tenant_id = $1
  AND gitlab_project_id = $2
`

type GetRepoByTenantAndProjectIDParams struct {
	TenantID        int64 `json:"tenant_id"`
	GitlabProjectID int64 `json:"gitlab_project_id"`
}

func (q *Queries) GetRepoByTenantAndProjectID(ctx context.Context, arg GetRepoByTenantAndProjectIDParams) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByTenantAndProjectID, arg.TenantID, arg.GitlabProjectID)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepoDefaultBranch = `-- name: UpdateRepoDefaultBranch :one
UPDATE repos
SET default_branch = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, tenant_id, gitlab_project_id, path_with_namespace, default_branch, created_at, updated_at
`

type UpdateRepoDefaultBranchParams struct {
	DefaultBranch string `json:"default_branch"`
	ID            int64  `json:"id"`
}

func (q *Queries) UpdateRepoDefaultBranch(ctx context.Context, arg UpdateRepoDefaultBranchParams) (Repo, error) {
	row := q.db.QueryRow(ctx, updateRepoDefaultBranch, arg.DefaultBranch, arg.ID)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GitlabProjectID,
		&i.PathWithNamespace,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
