// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revisions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRevision = `-- name: CreateRevision :one
INSERT INTO revisions (
    repo_id,
    sha,
    branch,
    parent_sha
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (repo_id, sha) DO UPDATE
SET branch = EXCLUDED.branch,
    parent_sha = EXCLUDED.parent_sha
RETURNING id, repo_id, sha, branch, parent_sha, processed_at, openapi_changed, status, error, created_at
`

type CreateRevisionParams struct {
	RepoID    int64       `json:"repo_id"`
	Sha       string      `json:"sha"`
	Branch    string      `json:"branch"`
	ParentSha pgtype.Text `json:"parent_sha"`
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) (Revision, error) {
	row := q.db.QueryRow(ctx, createRevision,
		arg.RepoID,
		arg.Sha,
		arg.Branch,
		arg.ParentSha,
	)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestProcessedOpenAPIRevisionByBranchExcludingID = `-- name: GetLatestProcessedOpenAPIRevisionByBranchExcludingID :one
SELECT id, repo_id, sha, branch, parent_sha, processed_at, openapi_changed, status, error, created_at
FROM revisions
WHERE repo_id = $1
  AND branch = $2
  AND status = 'processed'
  AND openapi_changed = TRUE
  AND id <> $3
ORDER BY processed_at DESC NULLS LAST, id DESC
LIMIT 1
`

type GetLatestProcessedOpenAPIRevisionByBranchExcludingIDParams struct {
	RepoID            int64  `json:"repo_id"`
	Branch            string `json:"branch"`
	ExcludeRevisionID int64  `json:"exclude_revision_id"`
}

func (q *Queries) GetLatestProcessedOpenAPIRevisionByBranchExcludingID(ctx context.Context, arg GetLatestProcessedOpenAPIRevisionByBranchExcludingIDParams) (Revision, error) {
	row := q.db.QueryRow(ctx, getLatestProcessedOpenAPIRevisionByBranchExcludingID, arg.RepoID, arg.Branch, arg.ExcludeRevisionID)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestProcessedRevisionByBranch = `-- name: GetLatestProcessedRevisionByBranch :one
SELECT id, repo_id, sha, branch, parent_sha, processed_at, openapi_changed, status, error, created_at
FROM revisions
WHERE repo_id = $1
  AND branch = $2
  AND status = 'processed'
ORDER BY processed_at DESC NULLS LAST, id DESC
LIMIT 1
`

type GetLatestProcessedRevisionByBranchParams struct {
	RepoID int64  `json:"repo_id"`
	Branch string `json:"branch"`
}

func (q *Queries) GetLatestProcessedRevisionByBranch(ctx context.Context, arg GetLatestProcessedRevisionByBranchParams) (Revision, error) {
	row := q.db.QueryRow(ctx, getLatestProcessedRevisionByBranch, arg.RepoID, arg.Branch)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getRevisionByID = `-- name: GetRevisionByID :one
SELECT id, repo_id, sha, branch, parent_sha, processed_at, openapi_changed, status, error, created_at
FROM revisions
WHERE id = $1
`

func (q *Queries) GetRevisionByID(ctx context.Context, id int64) (Revision, error) {
	row := q.db.QueryRow(ctx, getRevisionByID, id)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getRevisionByRepoSHA = `-- name: GetRevisionByRepoSHA :one
SELECT id, repo_id, sha, branch, parent_sha, processed_at, openapi_changed, status, error, created_at
FROM revisions
WHERE repo_id = $1
  AND sha = $2
`

type GetRevisionByRepoSHAParams struct {
	RepoID int64  `json:"repo_id"`
	Sha    string `json:"sha"`
}

func (q *Queries) GetRevisionByRepoSHA(ctx context.Context, arg GetRevisionByRepoSHAParams) (Revision, error) {
	row := q.db.QueryRow(ctx, getRevisionByRepoSHA, arg.RepoID, arg.Sha)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const markRevisionFailed = `-- name: MarkRevisionFailed :one
UPDATE revisions
SET processed_at = NOW(),
    status = 'failed',
    error = $1
WHERE id = $2
RETURNING id, repo_id, sha, branch, parent_sha, processed_at, openapi_changed, status, error, created_at
`

type MarkRevisionFailedParams struct {
	Error string `json:"error"`
	ID    int64  `json:"id"`
}

func (q *Queries) MarkRevisionFailed(ctx context.Context, arg MarkRevisionFailedParams) (Revision, error) {
	row := q.db.QueryRow(ctx, markRevisionFailed, arg.Error, arg.ID)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const markRevisionProcessed = `-- name: MarkRevisionProcessed :one
UPDATE revisions
SET processed_at = NOW(),
    openapi_changed = $1,
    status = 'processed',
    error = ''
WHERE id = $2
RETURNING id, repo_id, sha, branch, parent_sha, processed_at, openapi_changed, status, error, created_at
`

type MarkRevisionProcessedParams struct {
	OpenapiChanged pgtype.Bool `json:"openapi_changed"`
	ID             int64       `json:"id"`
}

func (q *Queries) MarkRevisionProcessed(ctx context.Context, arg MarkRevisionProcessedParams) (Revision, error) {
	row := q.db.QueryRow(ctx, markRevisionProcessed, arg.OpenapiChanged, arg.ID)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}
