// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revisions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRevisions = `-- name: CountRevisions :one
SELECT COUNT(*)::BIGINT
FROM ingest_events
`

func (q *Queries) CountRevisions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRevisions)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getLatestProcessedOpenAPIRevisionByBranchExcludingID = `-- name: GetLatestProcessedOpenAPIRevisionByBranchExcludingID :one
SELECT id, repo_id, sha, branch, parent_sha, event_type, delivery_id, payload_json, received_at, attempt_count, next_retry_at, processed_at, openapi_changed, status, error
FROM ingest_events
WHERE repo_id = $1
  AND branch = $2
  AND status = 'processed'
  AND openapi_changed = TRUE
  AND id <> $3
ORDER BY processed_at DESC NULLS LAST, id DESC
LIMIT 1
`

type GetLatestProcessedOpenAPIRevisionByBranchExcludingIDParams struct {
	RepoID            int64  `json:"repo_id"`
	Branch            string `json:"branch"`
	ExcludeRevisionID int64  `json:"exclude_revision_id"`
}

func (q *Queries) GetLatestProcessedOpenAPIRevisionByBranchExcludingID(ctx context.Context, arg GetLatestProcessedOpenAPIRevisionByBranchExcludingIDParams) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, getLatestProcessedOpenAPIRevisionByBranchExcludingID, arg.RepoID, arg.Branch, arg.ExcludeRevisionID)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const getLatestProcessedRevisionByBranch = `-- name: GetLatestProcessedRevisionByBranch :one
SELECT id, repo_id, sha, branch, parent_sha, event_type, delivery_id, payload_json, received_at, attempt_count, next_retry_at, processed_at, openapi_changed, status, error
FROM ingest_events
WHERE repo_id = $1
  AND branch = $2
  AND status = 'processed'
ORDER BY processed_at DESC NULLS LAST, id DESC
LIMIT 1
`

type GetLatestProcessedRevisionByBranchParams struct {
	RepoID int64  `json:"repo_id"`
	Branch string `json:"branch"`
}

func (q *Queries) GetLatestProcessedRevisionByBranch(ctx context.Context, arg GetLatestProcessedRevisionByBranchParams) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, getLatestProcessedRevisionByBranch, arg.RepoID, arg.Branch)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const getLatestRevisionByBranch = `-- name: GetLatestRevisionByBranch :one
SELECT id, repo_id, sha, branch, parent_sha, event_type, delivery_id, payload_json, received_at, attempt_count, next_retry_at, processed_at, openapi_changed, status, error
FROM ingest_events
WHERE repo_id = $1
  AND branch = $2
ORDER BY received_at DESC, id DESC
LIMIT 1
`

type GetLatestRevisionByBranchParams struct {
	RepoID int64  `json:"repo_id"`
	Branch string `json:"branch"`
}

func (q *Queries) GetLatestRevisionByBranch(ctx context.Context, arg GetLatestRevisionByBranchParams) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, getLatestRevisionByBranch, arg.RepoID, arg.Branch)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const getRevisionByID = `-- name: GetRevisionByID :one
SELECT id, repo_id, sha, branch, parent_sha, event_type, delivery_id, payload_json, received_at, attempt_count, next_retry_at, processed_at, openapi_changed, status, error
FROM ingest_events
WHERE id = $1
`

func (q *Queries) GetRevisionByID(ctx context.Context, id int64) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, getRevisionByID, id)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const getRevisionByRepoSHA = `-- name: GetRevisionByRepoSHA :one
SELECT id, repo_id, sha, branch, parent_sha, event_type, delivery_id, payload_json, received_at, attempt_count, next_retry_at, processed_at, openapi_changed, status, error
FROM ingest_events
WHERE repo_id = $1
  AND sha = $2
`

type GetRevisionByRepoSHAParams struct {
	RepoID int64  `json:"repo_id"`
	Sha    string `json:"sha"`
}

func (q *Queries) GetRevisionByRepoSHA(ctx context.Context, arg GetRevisionByRepoSHAParams) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, getRevisionByRepoSHA, arg.RepoID, arg.Sha)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
	)
	return i, err
}

const getRevisionByRepoSHAPrefix = `-- name: GetRevisionByRepoSHAPrefix :one
SELECT id, repo_id, sha, branch, parent_sha, event_type, delivery_id, payload_json, received_at, attempt_count, next_retry_at, processed_at, openapi_changed, status, error
FROM ingest_events
WHERE repo_id = $1
  AND sha LIKE $2 || '%'
ORDER BY received_at DESC, id DESC
LIMIT 1
`

type GetRevisionByRepoSHAPrefixParams struct {
	RepoID    int64       `json:"repo_id"`
	ShaPrefix pgtype.Text `json:"sha_prefix"`
}

func (q *Queries) GetRevisionByRepoSHAPrefix(ctx context.Context, arg GetRevisionByRepoSHAPrefixParams) (IngestEvent, error) {
	row := q.db.QueryRow(ctx, getRevisionByRepoSHAPrefix, arg.RepoID, arg.ShaPrefix)
	var i IngestEvent
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Sha,
		&i.Branch,
		&i.ParentSha,
		&i.EventType,
		&i.DeliveryID,
		&i.PayloadJson,
		&i.ReceivedAt,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.ProcessedAt,
		&i.OpenapiChanged,
		&i.Status,
		&i.Error,
	)
	return i, err
}
