// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spec_changes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpecChange = `-- name: CreateSpecChange :one
INSERT INTO spec_changes (
    api_spec_id,
    from_api_spec_revision_id,
    to_api_spec_revision_id,
    change_json
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (to_api_spec_revision_id) DO UPDATE
SET api_spec_id = EXCLUDED.api_spec_id,
    from_api_spec_revision_id = EXCLUDED.from_api_spec_revision_id,
    change_json = EXCLUDED.change_json
RETURNING id, api_spec_id, from_api_spec_revision_id, to_api_spec_revision_id, change_json, created_at
`

type CreateSpecChangeParams struct {
	ApiSpecID             int64       `json:"api_spec_id"`
	FromApiSpecRevisionID pgtype.Int8 `json:"from_api_spec_revision_id"`
	ToApiSpecRevisionID   int64       `json:"to_api_spec_revision_id"`
	ChangeJson            []byte      `json:"change_json"`
}

func (q *Queries) CreateSpecChange(ctx context.Context, arg CreateSpecChangeParams) (SpecChange, error) {
	row := q.db.QueryRow(ctx, createSpecChange,
		arg.ApiSpecID,
		arg.FromApiSpecRevisionID,
		arg.ToApiSpecRevisionID,
		arg.ChangeJson,
	)
	var i SpecChange
	err := row.Scan(
		&i.ID,
		&i.ApiSpecID,
		&i.FromApiSpecRevisionID,
		&i.ToApiSpecRevisionID,
		&i.ChangeJson,
		&i.CreatedAt,
	)
	return i, err
}

const getSpecChangeByAPISpecIDAndToAPISpecRevisionID = `-- name: GetSpecChangeByAPISpecIDAndToAPISpecRevisionID :one
SELECT id, api_spec_id, from_api_spec_revision_id, to_api_spec_revision_id, change_json, created_at
FROM spec_changes
WHERE api_spec_id = $1
  AND to_api_spec_revision_id = $2
`

type GetSpecChangeByAPISpecIDAndToAPISpecRevisionIDParams struct {
	ApiSpecID           int64 `json:"api_spec_id"`
	ToApiSpecRevisionID int64 `json:"to_api_spec_revision_id"`
}

func (q *Queries) GetSpecChangeByAPISpecIDAndToAPISpecRevisionID(ctx context.Context, arg GetSpecChangeByAPISpecIDAndToAPISpecRevisionIDParams) (SpecChange, error) {
	row := q.db.QueryRow(ctx, getSpecChangeByAPISpecIDAndToAPISpecRevisionID, arg.ApiSpecID, arg.ToApiSpecRevisionID)
	var i SpecChange
	err := row.Scan(
		&i.ID,
		&i.ApiSpecID,
		&i.FromApiSpecRevisionID,
		&i.ToApiSpecRevisionID,
		&i.ChangeJson,
		&i.CreatedAt,
	)
	return i, err
}
