// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spec_artifacts.sql

package sqlc

import (
	"context"
)

const getSpecArtifactByRevisionID = `-- name: GetSpecArtifactByRevisionID :one
SELECT id, revision_id, spec_json, spec_yaml, etag, size_bytes, created_at
FROM spec_artifacts
WHERE revision_id = $1
`

func (q *Queries) GetSpecArtifactByRevisionID(ctx context.Context, revisionID int64) (SpecArtifact, error) {
	row := q.db.QueryRow(ctx, getSpecArtifactByRevisionID, revisionID)
	var i SpecArtifact
	err := row.Scan(
		&i.ID,
		&i.RevisionID,
		&i.SpecJson,
		&i.SpecYaml,
		&i.Etag,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSpecArtifact = `-- name: UpsertSpecArtifact :one
INSERT INTO spec_artifacts (
    revision_id,
    spec_json,
    spec_yaml,
    etag,
    size_bytes
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (revision_id) DO UPDATE
SET spec_json = EXCLUDED.spec_json,
    spec_yaml = EXCLUDED.spec_yaml,
    etag = EXCLUDED.etag,
    size_bytes = EXCLUDED.size_bytes
RETURNING id, revision_id, spec_json, spec_yaml, etag, size_bytes, created_at
`

type UpsertSpecArtifactParams struct {
	RevisionID int64  `json:"revision_id"`
	SpecJson   []byte `json:"spec_json"`
	SpecYaml   string `json:"spec_yaml"`
	Etag       string `json:"etag"`
	SizeBytes  int64  `json:"size_bytes"`
}

func (q *Queries) UpsertSpecArtifact(ctx context.Context, arg UpsertSpecArtifactParams) (SpecArtifact, error) {
	row := q.db.QueryRow(ctx, upsertSpecArtifact,
		arg.RevisionID,
		arg.SpecJson,
		arg.SpecYaml,
		arg.Etag,
		arg.SizeBytes,
	)
	var i SpecArtifact
	err := row.Scan(
		&i.ID,
		&i.RevisionID,
		&i.SpecJson,
		&i.SpecYaml,
		&i.Etag,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}
