// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spec_changes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpecChange = `-- name: CreateSpecChange :one
INSERT INTO spec_changes (
    repo_id,
    from_revision_id,
    to_revision_id,
    change_json
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, repo_id, from_revision_id, to_revision_id, change_json, created_at
`

type CreateSpecChangeParams struct {
	RepoID         int64       `json:"repo_id"`
	FromRevisionID pgtype.Int8 `json:"from_revision_id"`
	ToRevisionID   int64       `json:"to_revision_id"`
	ChangeJson     []byte      `json:"change_json"`
}

func (q *Queries) CreateSpecChange(ctx context.Context, arg CreateSpecChangeParams) (SpecChange, error) {
	row := q.db.QueryRow(ctx, createSpecChange,
		arg.RepoID,
		arg.FromRevisionID,
		arg.ToRevisionID,
		arg.ChangeJson,
	)
	var i SpecChange
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.FromRevisionID,
		&i.ToRevisionID,
		&i.ChangeJson,
		&i.CreatedAt,
	)
	return i, err
}

const getSpecChangeByToRevision = `-- name: GetSpecChangeByToRevision :one
SELECT id, repo_id, from_revision_id, to_revision_id, change_json, created_at
FROM spec_changes
WHERE to_revision_id = $1
`

func (q *Queries) GetSpecChangeByToRevision(ctx context.Context, toRevisionID int64) (SpecChange, error) {
	row := q.db.QueryRow(ctx, getSpecChangeByToRevision, toRevisionID)
	var i SpecChange
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.FromRevisionID,
		&i.ToRevisionID,
		&i.ChangeJson,
		&i.CreatedAt,
	)
	return i, err
}
