// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: startup_index_state.sql

package sqlc

import (
	"context"
)

const advanceStartupIndexLastProjectID = `-- name: AdvanceStartupIndexLastProjectID :exec
INSERT INTO startup_index_state (
    singleton,
    last_project_id
)
VALUES (
    TRUE,
    $1
)
ON CONFLICT (singleton) DO UPDATE
SET last_project_id = GREATEST(startup_index_state.last_project_id, EXCLUDED.last_project_id),
    updated_at = NOW()
`

func (q *Queries) AdvanceStartupIndexLastProjectID(ctx context.Context, lastProjectID int64) error {
	_, err := q.db.Exec(ctx, advanceStartupIndexLastProjectID, lastProjectID)
	return err
}

const getStartupIndexLastProjectID = `-- name: GetStartupIndexLastProjectID :one
SELECT last_project_id
FROM startup_index_state
WHERE singleton = TRUE
`

func (q *Queries) GetStartupIndexLastProjectID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getStartupIndexLastProjectID)
	var last_project_id int64
	err := row.Scan(&last_project_id)
	return last_project_id, err
}
