// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package sqlc

import (
	"context"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    repo_id,
    target_url,
    secret,
    enabled,
    max_attempts,
    backoff_initial_seconds,
    backoff_max_seconds
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, repo_id, target_url, secret, enabled, max_attempts, backoff_initial_seconds, backoff_max_seconds, created_at, updated_at
`

type CreateSubscriptionParams struct {
	RepoID                int64  `json:"repo_id"`
	TargetUrl             string `json:"target_url"`
	Secret                string `json:"secret"`
	Enabled               bool   `json:"enabled"`
	MaxAttempts           int32  `json:"max_attempts"`
	BackoffInitialSeconds int32  `json:"backoff_initial_seconds"`
	BackoffMaxSeconds     int32  `json:"backoff_max_seconds"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.RepoID,
		arg.TargetUrl,
		arg.Secret,
		arg.Enabled,
		arg.MaxAttempts,
		arg.BackoffInitialSeconds,
		arg.BackoffMaxSeconds,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TargetUrl,
		&i.Secret,
		&i.Enabled,
		&i.MaxAttempts,
		&i.BackoffInitialSeconds,
		&i.BackoffMaxSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledSubscriptionsByRepo = `-- name: ListEnabledSubscriptionsByRepo :many
SELECT id, repo_id, target_url, secret, enabled, max_attempts, backoff_initial_seconds, backoff_max_seconds, created_at, updated_at
FROM subscriptions
WHERE repo_id = $1
  AND enabled = TRUE
ORDER BY id
`

func (q *Queries) ListEnabledSubscriptionsByRepo(ctx context.Context, repoID int64) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listEnabledSubscriptionsByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.TargetUrl,
			&i.Secret,
			&i.Enabled,
			&i.MaxAttempts,
			&i.BackoffInitialSeconds,
			&i.BackoffMaxSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSubscriptionEnabled = `-- name: SetSubscriptionEnabled :one
UPDATE subscriptions
SET enabled = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, repo_id, target_url, secret, enabled, max_attempts, backoff_initial_seconds, backoff_max_seconds, created_at, updated_at
`

type SetSubscriptionEnabledParams struct {
	Enabled bool  `json:"enabled"`
	ID      int64 `json:"id"`
}

func (q *Queries) SetSubscriptionEnabled(ctx context.Context, arg SetSubscriptionEnabledParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, setSubscriptionEnabled, arg.Enabled, arg.ID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TargetUrl,
		&i.Secret,
		&i.Enabled,
		&i.MaxAttempts,
		&i.BackoffInitialSeconds,
		&i.BackoffMaxSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
