// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package sqlc

import (
	"context"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (key)
VALUES ($1)
RETURNING id, key, created_at, updated_at
`

func (q *Queries) CreateTenant(ctx context.Context, key string) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, key)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, key, created_at, updated_at
FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id int64) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByKey = `-- name: GetTenantByKey :one
SELECT id, key, created_at, updated_at
FROM tenants
WHERE key = $1
`

func (q *Queries) GetTenantByKey(ctx context.Context, key string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByKey, key)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, key, created_at, updated_at
FROM tenants
ORDER BY id
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
