// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vacuum.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVacuumIssue = `-- name: CreateVacuumIssue :one
INSERT INTO vacuum_issues (
    api_spec_revision_id,
    rule_id,
    message,
    json_path,
    range_pos
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::INTEGER[]
)
RETURNING id, api_spec_revision_id, rule_id, message, json_path, range_pos, created_at
`

type CreateVacuumIssueParams struct {
	ApiSpecRevisionID int64   `json:"api_spec_revision_id"`
	RuleID            string  `json:"rule_id"`
	Message           string  `json:"message"`
	JsonPath          string  `json:"json_path"`
	RangePos          []int32 `json:"range_pos"`
}

func (q *Queries) CreateVacuumIssue(ctx context.Context, arg CreateVacuumIssueParams) (VacuumIssue, error) {
	row := q.db.QueryRow(ctx, createVacuumIssue,
		arg.ApiSpecRevisionID,
		arg.RuleID,
		arg.Message,
		arg.JsonPath,
		arg.RangePos,
	)
	var i VacuumIssue
	err := row.Scan(
		&i.ID,
		&i.ApiSpecRevisionID,
		&i.RuleID,
		&i.Message,
		&i.JsonPath,
		&i.RangePos,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVacuumIssuesByAPISpecRevisionID = `-- name: DeleteVacuumIssuesByAPISpecRevisionID :exec
DELETE FROM vacuum_issues
WHERE api_spec_revision_id = $1
`

func (q *Queries) DeleteVacuumIssuesByAPISpecRevisionID(ctx context.Context, apiSpecRevisionID int64) error {
	_, err := q.db.Exec(ctx, deleteVacuumIssuesByAPISpecRevisionID, apiSpecRevisionID)
	return err
}

const ensureVacuumRule = `-- name: EnsureVacuumRule :exec
WITH rule_input AS (
    SELECT $1::TEXT AS rule_id
)
INSERT INTO vacuum_rules (
    rule_id,
    severity,
    type,
    category_id,
    category_name,
    description,
    how_to_fix,
    given_path,
    rule_json
)
SELECT
    rule_input.rule_id,
    'warn',
    'validation',
    'validation',
    'Validation',
    'Rule metadata is not present in Shiva seed; issue was recorded with fallback metadata.',
    'Update Shiva vacuum rule seed to include this rule identifier.',
    '$',
    jsonb_build_object('id', rule_input.rule_id, 'generated_by', 'shiva-fallback')
FROM rule_input
ON CONFLICT (rule_id) DO NOTHING
`

func (q *Queries) EnsureVacuumRule(ctx context.Context, ruleID string) error {
	_, err := q.db.Exec(ctx, ensureVacuumRule, ruleID)
	return err
}

const listVacuumIssuesByAPISpecRevisionID = `-- name: ListVacuumIssuesByAPISpecRevisionID :many
SELECT id, api_spec_revision_id, rule_id, message, json_path, range_pos, created_at
FROM vacuum_issues
WHERE api_spec_revision_id = $1
ORDER BY id ASC
`

func (q *Queries) ListVacuumIssuesByAPISpecRevisionID(ctx context.Context, apiSpecRevisionID int64) ([]VacuumIssue, error) {
	rows, err := q.db.Query(ctx, listVacuumIssuesByAPISpecRevisionID, apiSpecRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VacuumIssue{}
	for rows.Next() {
		var i VacuumIssue
		if err := rows.Scan(
			&i.ID,
			&i.ApiSpecRevisionID,
			&i.RuleID,
			&i.Message,
			&i.JsonPath,
			&i.RangePos,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVacuumRules = `-- name: ListVacuumRules :many
SELECT rule_id, severity, type, category_id, category_name, description, how_to_fix, given_path, rule_json
FROM vacuum_rules
ORDER BY rule_id ASC
`

func (q *Queries) ListVacuumRules(ctx context.Context) ([]VacuumRule, error) {
	rows, err := q.db.Query(ctx, listVacuumRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VacuumRule{}
	for rows.Next() {
		var i VacuumRule
		if err := rows.Scan(
			&i.RuleID,
			&i.Severity,
			&i.Type,
			&i.CategoryID,
			&i.CategoryName,
			&i.Description,
			&i.HowToFix,
			&i.GivenPath,
			&i.RuleJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPISpecRevisionVacuumState = `-- name: UpdateAPISpecRevisionVacuumState :one
UPDATE api_spec_revisions
SET vacuum_status = $1,
    vacuum_error = $2,
    vacuum_validated_at = $3,
    updated_at = NOW()
WHERE id = $4
RETURNING
    id,
    api_spec_id,
    ingest_event_id,
    root_path_at_revision,
    build_status,
    error,
    vacuum_status,
    vacuum_error,
    vacuum_validated_at,
    created_at,
    updated_at
`

type UpdateAPISpecRevisionVacuumStateParams struct {
	VacuumStatus      string             `json:"vacuum_status"`
	VacuumError       string             `json:"vacuum_error"`
	VacuumValidatedAt pgtype.Timestamptz `json:"vacuum_validated_at"`
	ApiSpecRevisionID int64              `json:"api_spec_revision_id"`
}

func (q *Queries) UpdateAPISpecRevisionVacuumState(ctx context.Context, arg UpdateAPISpecRevisionVacuumStateParams) (ApiSpecRevision, error) {
	row := q.db.QueryRow(ctx, updateAPISpecRevisionVacuumState,
		arg.VacuumStatus,
		arg.VacuumError,
		arg.VacuumValidatedAt,
		arg.ApiSpecRevisionID,
	)
	var i ApiSpecRevision
	err := row.Scan(
		&i.ID,
		&i.ApiSpecID,
		&i.IngestEventID,
		&i.RootPathAtRevision,
		&i.BuildStatus,
		&i.Error,
		&i.VacuumStatus,
		&i.VacuumError,
		&i.VacuumValidatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
