CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    checksum TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS repos (
    id BIGSERIAL PRIMARY KEY,
    gitlab_project_id BIGINT NOT NULL,
    namespace TEXT NOT NULL,
    repo TEXT NOT NULL,
    default_branch TEXT NOT NULL,
    openapi_force_rescan BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (gitlab_project_id),
    UNIQUE (namespace, repo)
);

CREATE TABLE IF NOT EXISTS startup_index_state (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    last_project_id BIGINT NOT NULL CHECK (last_project_id >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS subscriptions (
    id BIGSERIAL PRIMARY KEY,
    repo_id BIGINT NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
    target_url TEXT NOT NULL,
    secret TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    max_attempts INTEGER NOT NULL DEFAULT 8 CHECK (max_attempts > 0),
    backoff_initial_seconds INTEGER NOT NULL DEFAULT 5 CHECK (backoff_initial_seconds > 0),
    backoff_max_seconds INTEGER NOT NULL DEFAULT 300 CHECK (backoff_max_seconds > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (repo_id, target_url)
);

CREATE INDEX IF NOT EXISTS subscriptions_repo_enabled_idx ON subscriptions(repo_id, enabled);

CREATE TABLE IF NOT EXISTS ingest_events (
    id BIGSERIAL PRIMARY KEY,
    repo_id BIGINT NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
    sha TEXT NOT NULL,
    branch TEXT NOT NULL,
    parent_sha TEXT,
    event_type TEXT NOT NULL,
    delivery_id TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_retry_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ,
    openapi_changed BOOLEAN,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'processed', 'failed')),
    error TEXT NOT NULL DEFAULT '',
    UNIQUE (repo_id, delivery_id),
    UNIQUE (repo_id, sha)
);

CREATE INDEX IF NOT EXISTS ingest_events_status_retry_idx ON ingest_events(status, next_retry_at, id);
CREATE INDEX IF NOT EXISTS ingest_events_repo_id_idx ON ingest_events(repo_id, id);
CREATE INDEX IF NOT EXISTS ingest_events_repo_branch_processed_idx ON ingest_events(repo_id, branch, processed_at DESC);
CREATE INDEX IF NOT EXISTS ingest_events_repo_received_idx ON ingest_events(repo_id, received_at DESC);
CREATE INDEX IF NOT EXISTS ingest_events_repo_branch_received_idx ON ingest_events(repo_id, branch, received_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS ingest_events_repo_branch_openapi_processed_idx
    ON ingest_events(repo_id, branch, processed_at DESC, id DESC)
    WHERE status = 'processed' AND openapi_changed = TRUE;

CREATE TABLE IF NOT EXISTS api_specs (
    id BIGSERIAL PRIMARY KEY,
    repo_id BIGINT NOT NULL REFERENCES repos(id) ON DELETE CASCADE,
    root_path TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'deleted')),
    display_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (repo_id, root_path)
);

CREATE INDEX IF NOT EXISTS api_specs_repo_status_idx ON api_specs(repo_id, status);

CREATE TABLE IF NOT EXISTS api_spec_revisions (
    id BIGSERIAL PRIMARY KEY,
    api_spec_id BIGINT NOT NULL REFERENCES api_specs(id) ON DELETE CASCADE,
    ingest_event_id BIGINT NOT NULL REFERENCES ingest_events(id) ON DELETE CASCADE,
    root_path_at_revision TEXT NOT NULL,
    build_status TEXT NOT NULL,
    error TEXT NOT NULL DEFAULT '',
    vacuum_status TEXT NOT NULL DEFAULT 'pending' CHECK (vacuum_status IN ('pending', 'processing', 'processed', 'failed')),
    vacuum_error TEXT NOT NULL DEFAULT '',
    vacuum_validated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (api_spec_id, ingest_event_id)
);

CREATE INDEX IF NOT EXISTS api_spec_revisions_ingest_event_id_idx ON api_spec_revisions(ingest_event_id);
CREATE INDEX IF NOT EXISTS api_spec_revisions_api_spec_snapshot_idx
    ON api_spec_revisions(api_spec_id, ingest_event_id DESC, id DESC);
CREATE INDEX IF NOT EXISTS api_spec_revisions_vacuum_status_idx ON api_spec_revisions(vacuum_status, id);

CREATE TABLE IF NOT EXISTS vacuum_rules (
    rule_id TEXT PRIMARY KEY,
    severity TEXT NOT NULL,
    type TEXT NOT NULL,
    category_id TEXT NOT NULL,
    category_name TEXT NOT NULL,
    description TEXT NOT NULL,
    how_to_fix TEXT NOT NULL,
    given_path TEXT NOT NULL,
    rule_json JSONB NOT NULL
);

-- vacuum v0.25.0 generate-ruleset all, normalized with recommended and formats removed.
-- vacuum_rules seed start
INSERT INTO vacuum_rules (rule_id, severity, type, category_id, category_name, description, how_to_fix, given_path, rule_json) VALUES
    ('camel-case-properties', 'warn', 'style', 'schemas', 'Schemas', 'Schema property names should use camelCase instead of snake_case, PascalCase, kebab-case, or other formats.', 'Schema property names should use camelCase for consistency and better compatibility with code generation tools. Property names should start with a lowercase letter and use uppercase letters for word boundaries.', '$', '{"category":{"description":"Schemas are how request bodies and response payloads are defined. They define the data going in and the data flowing out of an operation. These rules check for structural validity, checking types, checking required fields and validating correct use of structures.","id":"schemas","name":"Schemas"},"description":"Schema property names should use camelCase instead of snake_case, PascalCase, kebab-case, or other formats.","given":"$","howToFix":"Schema property names should use camelCase for consistency and better compatibility with code generation tools. Property names should start with a lowercase letter and use uppercase letters for word boundaries.","id":"camel-case-properties","resolved":true,"severity":"warn","then":{"function":"oasCamelCaseProperties"},"type":"style"}'::jsonb),
    ('component-description', 'warn', 'validation', 'descriptions', 'Descriptions', 'Component description check', 'Components are the inputs and outputs of a specification. A user needs to be able to understand each component and what it does. Descriptions are critical to understanding components. Add a description!', '$', '{"category":{"description":"Documentation is really important, in OpenAPI, just about everything can and should have a description. This set of rules checks for absent descriptions, poor quality descriptions (copy/paste), or short descriptions.","id":"descriptions","name":"Descriptions"},"description":"Component description check","given":"$","howToFix":"Components are the inputs and outputs of a specification. A user needs to be able to understand each component and what it does. Descriptions are critical to understanding components. Add a description!","id":"component-description","resolved":true,"severity":"warn","then":{"function":"oasComponentDescriptions"},"type":"validation"}'::jsonb),
    ('contact-properties', 'info', 'validation', 'information', 'Contract Information', 'Contact details are incomplete', 'Complete specification contact information. Fill in the ''name'', ''url'' and ''email''properties so consumers of the spec know how to reach you.', '$', '{"category":{"description":"The info object contains licencing, contact, authorship details and more. Checks to confirm required details have been completed.","id":"information","name":"Contract Information"},"description":"Contact details are incomplete","given":"$","howToFix":"Complete specification contact information. Fill in the ''name'', ''url'' and ''email''properties so consumers of the spec know how to reach you.","id":"contact-properties","resolved":true,"severity":"info","then":{"function":"infoContactProperties"},"type":"validation"}'::jsonb),
    ('description-duplication', 'info', 'validation', 'descriptions', 'Descriptions', 'Description duplication check', 'Descriptions are only useful, if they are meaningful. If a description is meaningful, then it won''t be something you copy and paste. Please don''t duplicate descriptions, make them deliberate and meaningful.', '$', '{"category":{"description":"Documentation is really important, in OpenAPI, just about everything can and should have a description. This set of rules checks for absent descriptions, poor quality descriptions (copy/paste), or short descriptions.","id":"descriptions","name":"Descriptions"},"description":"Description duplication check","given":"$","howToFix":"Descriptions are only useful, if they are meaningful. If a description is meaningful, then it won''t be something you copy and paste. Please don''t duplicate descriptions, make them deliberate and meaningful.","id":"description-duplication","severity":"info","then":{"function":"oasDescriptionDuplication"},"type":"validation"}'::jsonb),
    ('duplicate-paths', 'error', 'validation', 'operations', 'Operations', 'Paths cannot be duplicated; only the last definition will be kept.', 'Duplicate path definitions found in your OpenAPI specification. In YAML, duplicate keys are allowed, but only the last occurrence is used. This means earlier path definitions are silently ignored, which can lead to missing API endpoints in your specification.', '$', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"Paths cannot be duplicated; only the last definition will be kept.","given":"$","howToFix":"Duplicate path definitions found in your OpenAPI specification. In YAML, duplicate keys are allowed, but only the last occurrence is used. This means earlier path definitions are silently ignored, which can lead to missing API endpoints in your specification.","id":"duplicate-paths","severity":"error","then":{"function":"duplicatePaths"},"type":"validation"}'::jsonb),
    ('duplicated-entry-in-enum', 'error', 'validation', 'schemas', 'Schemas', 'Enum values must not have duplicate entry', 'Enums need to be unique, you can''t duplicate them in the same definition. Please remove the duplicate value.', '$', '{"category":{"description":"Schemas are how request bodies and response payloads are defined. They define the data going in and the data flowing out of an operation. These rules check for structural validity, checking types, checking required fields and validating correct use of structures.","id":"schemas","name":"Schemas"},"description":"Enum values must not have duplicate entry","given":"$","howToFix":"Enums need to be unique, you can''t duplicate them in the same definition. Please remove the duplicate value.","id":"duplicated-entry-in-enum","severity":"error","then":{"function":"duplicatedEnum"},"type":"validation"}'::jsonb),
    ('info-contact', 'warn', 'validation', 'information', 'Contract Information', 'Info section is missing contact details', 'The specification ''info'' section doesn''t contain a ''contact'' object. Add it and make sure to complete ''name'', ''url'' and ''email'' properties so consumers of the spec know how to reach you.', '$', '{"category":{"description":"The info object contains licencing, contact, authorship details and more. Checks to confirm required details have been completed.","id":"information","name":"Contract Information"},"description":"Info section is missing contact details","given":"$","howToFix":"The specification ''info'' section doesn''t contain a ''contact'' object. Add it and make sure to complete ''name'', ''url'' and ''email'' properties so consumers of the spec know how to reach you.","id":"info-contact","resolved":true,"severity":"warn","then":{"function":"infoContact"},"type":"validation"}'::jsonb),
    ('info-description', 'error', 'validation', 'information', 'Contract Information', 'Info section is missing a description', 'The ''info'' section is missing a description, surely you want people to know what this spec is all about, right?', '$', '{"category":{"description":"The info object contains licencing, contact, authorship details and more. Checks to confirm required details have been completed.","id":"information","name":"Contract Information"},"description":"Info section is missing a description","given":"$","howToFix":"The ''info'' section is missing a description, surely you want people to know what this spec is all about, right?","id":"info-description","resolved":true,"severity":"error","then":{"function":"infoDescription"},"type":"validation"}'::jsonb),
    ('info-license', 'info', 'style', 'information', 'Contract Information', 'Info section should contain a license', 'The ''info'' section is missing a ''license'' object. Please add an appropriate one', '$.info', '{"category":{"description":"The info object contains licencing, contact, authorship details and more. Checks to confirm required details have been completed.","id":"information","name":"Contract Information"},"description":"Info section should contain a license","given":"$.info","howToFix":"The ''info'' section is missing a ''license'' object. Please add an appropriate one","id":"info-license","resolved":true,"severity":"info","then":{"function":"infoLicense"},"type":"style"}'::jsonb),
    ('info-license-spdx', 'error', 'validation', 'information', 'Contract Information', 'License section cannot contain both an identifier and a URL, they are mutually exclusive.', 'A license can contain either a URL or an SPDX identifier, but not both, They are mutually exclusive and cannot both be present. Choose one or the other', '$', '{"category":{"description":"The info object contains licencing, contact, authorship details and more. Checks to confirm required details have been completed.","id":"information","name":"Contract Information"},"description":"License section cannot contain both an identifier and a URL, they are mutually exclusive.","given":"$","howToFix":"A license can contain either a URL or an SPDX identifier, but not both, They are mutually exclusive and cannot both be present. Choose one or the other","id":"info-license-spdx","resolved":true,"severity":"error","then":{"function":"infoLicenseURLSPDX"},"type":"validation"}'::jsonb),
    ('license-url', 'info', 'style', 'information', 'Contract Information', 'License should contain a URL', 'The ''info'' section license URL is missing. If you add a license, you need to make sure  that you link to an appropriate URL for that license.', '$.info.license', '{"category":{"description":"The info object contains licencing, contact, authorship details and more. Checks to confirm required details have been completed.","id":"information","name":"Contract Information"},"description":"License should contain a URL","given":"$.info.license","howToFix":"The ''info'' section license URL is missing. If you add a license, you need to make sure  that you link to an appropriate URL for that license.","id":"license-url","resolved":true,"severity":"info","then":{"function":"infoLicenseUrl"},"type":"style"}'::jsonb),
    ('migrate-zally-ignore', 'warn', 'validation', 'validation', 'Validation', 'x-zally-ignore keys should be migrated to x-lint-ignore for compatibility with vacuum', 'Migrate x-zally-ignore directives to vacuum''s x-lint-ignore. Rename the key to x-lint-ignore and update the ignored rule id to the vacuum equivalent rule.', '$', '{"category":{"description":"Validation rules make sure that certain characters or patterns have not been used that may cause issues when rendering in different types of applications.","id":"validation","name":"Validation"},"description":"x-zally-ignore keys should be migrated to x-lint-ignore for compatibility with vacuum","given":"$","howToFix":"Migrate x-zally-ignore directives to vacuum''s x-lint-ignore. Rename the key to x-lint-ignore and update the ignored rule id to the vacuum equivalent rule.","id":"migrate-zally-ignore","resolved":true,"severity":"warn","then":{"function":"migrateZallyIgnore"},"type":"validation"}'::jsonb),
    ('no-$ref-siblings', 'error', 'validation', 'schemas', 'Schemas', '$ref values cannot be placed next to other properties (like a description)', '$ref values must not be placed next to sibling nodes, There should only be a single node  when using $ref. A common mistake is adding ''description'' next to a $ref. This is wrong. remove all siblings!', '$', '{"category":{"description":"Schemas are how request bodies and response payloads are defined. They define the data going in and the data flowing out of an operation. These rules check for structural validity, checking types, checking required fields and validating correct use of structures.","id":"schemas","name":"Schemas"},"description":"$ref values cannot be placed next to other properties (like a description)","given":"$","howToFix":"$ref values must not be placed next to sibling nodes, There should only be a single node  when using $ref. A common mistake is adding ''description'' next to a $ref. This is wrong. remove all siblings!","id":"no-$ref-siblings","severity":"error","then":{"function":"refSiblings"},"type":"validation"}'::jsonb),
    ('no-ambiguous-paths', 'error', 'validation', 'operations', 'Operations', 'Paths need to resolve unambiguously from one another', 'Paths must all resolve unambiguously, they can''t be confused with one another (/{id}/ambiguous and /ambiguous/{id} are the same thing. Make sure every path and the variables used are unique and do conflict with one another. Check the ordering of variables and the naming of path segments.', '$', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"Paths need to resolve unambiguously from one another","given":"$","howToFix":"Paths must all resolve unambiguously, they can''t be confused with one another (/{id}/ambiguous and /ambiguous/{id} are the same thing. Make sure every path and the variables used are unique and do conflict with one another. Check the ordering of variables and the naming of path segments.","id":"no-ambiguous-paths","resolved":true,"severity":"error","then":{"function":"noAmbiguousPaths"},"type":"validation"}'::jsonb),
    ('no-eval-in-markdown', 'error', 'validation', 'validation', 'Validation', 'Markdown descriptions must not have `eval()` statements''', 'Remove all references to ''eval()'' in the description. These can be used by malicious actors to embed code in contracts that is then executed when read by a browser.', '$', '{"category":{"description":"Validation rules make sure that certain characters or patterns have not been used that may cause issues when rendering in different types of applications.","id":"validation","name":"Validation"},"description":"Markdown descriptions must not have `eval()` statements''","given":"$","howToFix":"Remove all references to ''eval()'' in the description. These can be used by malicious actors to embed code in contracts that is then executed when read by a browser.","id":"no-eval-in-markdown","resolved":true,"severity":"error","then":{"function":"noEvalDescription","functionOptions":{"pattern":"eval\\("}},"type":"validation"}'::jsonb),
    ('no-http-verbs-in-path', 'warn', 'style', 'operations', 'Operations', 'Path segments must not contain an HTTP verb', 'When HTTP verbs (get/post/put etc) are used in path segments, it muddies the semantics of REST and creates a confusing and inconsistent experience. It''s highly recommended that verbs are not used in path segments. Replace those HTTP verbs with more meaningful nouns.', '$', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"Path segments must not contain an HTTP verb","given":"$","howToFix":"When HTTP verbs (get/post/put etc) are used in path segments, it muddies the semantics of REST and creates a confusing and inconsistent experience. It''s highly recommended that verbs are not used in path segments. Replace those HTTP verbs with more meaningful nouns.","id":"no-http-verbs-in-path","severity":"warn","then":{"function":"noVerbsInPath"},"type":"style"}'::jsonb),
    ('no-request-body', 'warn', 'style', 'operations', 'Operations', 'HTTP GET and DELETE should not accept request bodies', 'Remove ''requestBody'' from HTTP GET and DELETE methods', '$', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"HTTP GET and DELETE should not accept request bodies","given":"$","howToFix":"Remove ''requestBody'' from HTTP GET and DELETE methods","id":"no-request-body","severity":"warn","then":{"function":"noRequestBody"},"type":"style"}'::jsonb),
    ('no-script-tags-in-markdown', 'error', 'validation', 'validation', 'Validation', 'Markdown descriptions must not have `<script>` tags''', 'Remove all references to ''<script>'' tags from the description. These can be used by malicious actors to load remote code if the spec is being parsed by a browser.', '$', '{"category":{"description":"Validation rules make sure that certain characters or patterns have not been used that may cause issues when rendering in different types of applications.","id":"validation","name":"Validation"},"description":"Markdown descriptions must not have `<script>` tags''","given":"$","howToFix":"Remove all references to ''<script>'' tags from the description. These can be used by malicious actors to load remote code if the spec is being parsed by a browser.","id":"no-script-tags-in-markdown","resolved":true,"severity":"error","then":{"function":"noEvalDescription","functionOptions":{"pattern":"<script"}},"type":"validation"}'::jsonb),
    ('no-unnecessary-combinator', 'warn', 'style', 'schemas', 'Schemas', 'Schema combinators (allOf, anyOf, oneOf) with only one item should be replaced with the item directly.', 'Schema combinators (allOf, anyOf, oneOf) with only a single item are unnecessary and should be replaced with the item directly for cleaner, more readable schemas.', '$', '{"category":{"description":"Schemas are how request bodies and response payloads are defined. They define the data going in and the data flowing out of an operation. These rules check for structural validity, checking types, checking required fields and validating correct use of structures.","id":"schemas","name":"Schemas"},"description":"Schema combinators (allOf, anyOf, oneOf) with only one item should be replaced with the item directly.","given":"$","howToFix":"Schema combinators (allOf, anyOf, oneOf) with only a single item are unnecessary and should be replaced with the item directly for cleaner, more readable schemas.","id":"no-unnecessary-combinator","resolved":true,"severity":"warn","then":{"function":"oasUnnecessaryCombinator"},"type":"style"}'::jsonb),
    ('nullable-enum-contains-null', 'warn', 'validation', 'schemas', 'Schemas', 'Nullable enums must explicitly include null in the enum array', 'When a schema is marked as nullable (using ''nullable: true'' in OpenAPI 3.0 or ''type: [<type>, "null"]'' in OpenAPI 3.1), and also defines an enum array, the enum must explicitly contain a null value (without quotes). Simply marking the schema as nullable is not enough - the null value must be listed in the enum array. Add null (unquoted) to your enum array, for example: enum: [active, inactive, null]', '$', '{"category":{"description":"Schemas are how request bodies and response payloads are defined. They define the data going in and the data flowing out of an operation. These rules check for structural validity, checking types, checking required fields and validating correct use of structures.","id":"schemas","name":"Schemas"},"description":"Nullable enums must explicitly include null in the enum array","given":"$","howToFix":"When a schema is marked as nullable (using ''nullable: true'' in OpenAPI 3.0 or ''type: [<type>, \"null\"]'' in OpenAPI 3.1), and also defines an enum array, the enum must explicitly contain a null value (without quotes). Simply marking the schema as nullable is not enough - the null value must be listed in the enum array. Add null (unquoted) to your enum array, for example: enum: [active, inactive, null]","id":"nullable-enum-contains-null","resolved":true,"severity":"warn","then":{"function":"nullableEnum"},"type":"validation"}'::jsonb),
    ('oas-missing-type', 'info', 'validation', 'schemas', 'Schemas', 'All schemas and their properties should have a type field (unless using enum, const, or a composition)', 'Add a `type` field to all schemas and properties. Valid types are: string, number, integer, boolean, array, object, or null.', '$', '{"category":{"description":"Schemas are how request bodies and response payloads are defined. They define the data going in and the data flowing out of an operation. These rules check for structural validity, checking types, checking required fields and validating correct use of structures.","id":"schemas","name":"Schemas"},"description":"All schemas and their properties should have a type field (unless using enum, const, or a composition)","given":"$","howToFix":"Add a `type` field to all schemas and properties. Valid types are: string, number, integer, boolean, array, object, or null.","id":"oas-missing-type","severity":"info","then":{"function":"missingType"},"type":"validation"}'::jsonb),
    ('oas-schema-check', 'error', 'validation', 'schemas', 'Schemas', 'All document schemas must have a valid type defined', 'Make sure each schema has a value type defined. Without a type, the schema is useless', '$', '{"category":{"description":"Schemas are how request bodies and response payloads are defined. They define the data going in and the data flowing out of an operation. These rules check for structural validity, checking types, checking required fields and validating correct use of structures.","id":"schemas","name":"Schemas"},"description":"All document schemas must have a valid type defined","given":"$","howToFix":"Make sure each schema has a value type defined. Without a type, the schema is useless","id":"oas-schema-check","severity":"error","then":{"function":"schemaTypeCheck"},"type":"validation"}'::jsonb),
    ('oas2-anyOf', 'error', 'validation', 'schemas', 'Schemas', '`anyOf` was introduced in OpenAPI 3.0, cannot be used un OpenAPI 2 specs', 'You can''t use ''anyOf'' in Swagger/OpenAPI 2 specs. It was added in version 3. You have to remove it', '$', '{"category":{"description":"Schemas are how request bodies and response payloads are defined. They define the data going in and the data flowing out of an operation. These rules check for structural validity, checking types, checking required fields and validating correct use of structures.","id":"schemas","name":"Schemas"},"description":"`anyOf` was introduced in OpenAPI 3.0, cannot be used un OpenAPI 2 specs","given":"$","howToFix":"You can''t use ''anyOf'' in Swagger/OpenAPI 2 specs. It was added in version 3. You have to remove it","id":"oas2-anyOf","severity":"error","then":{"function":"oasPolymorphicAnyOf"},"type":"validation"}'::jsonb),
    ('oas2-api-host', 'info', 'style', 'information', 'Contract Information', 'OpenAPI `host` must be present and a non-empty string', 'The ''host'' value is missing. How is a user supposed to know where the API actually lives? The host is critical in order for consumers to be able to call the API. Add an API host!', '$', '{"category":{"description":"The info object contains licencing, contact, authorship details and more. Checks to confirm required details have been completed.","id":"information","name":"Contract Information"},"description":"OpenAPI `host` must be present and a non-empty string","given":"$","howToFix":"The ''host'' value is missing. How is a user supposed to know where the API actually lives? The host is critical in order for consumers to be able to call the API. Add an API host!","id":"oas2-api-host","severity":"info","then":{"field":"host","function":"truthy"},"type":"style"}'::jsonb),
    ('oas2-api-schemes', 'warn', 'validation', 'information', 'Contract Information', 'OpenAPI host `schemes` must be present and non-empty array', 'Add an array of supported host ''schemes'' to the root of the specification. These are the available API schemes (like https/http).', '$', '{"category":{"description":"The info object contains licencing, contact, authorship details and more. Checks to confirm required details have been completed.","id":"information","name":"Contract Information"},"description":"OpenAPI host `schemes` must be present and non-empty array","given":"$","howToFix":"Add an array of supported host ''schemes'' to the root of the specification. These are the available API schemes (like https/http).","id":"oas2-api-schemes","severity":"warn","then":{"field":"schemes","function":"schema","functionOptions":{"forceValidation":true,"schema":{"items":{"minItems":1,"type":"string"},"type":"array","uniqueItems":true}}},"type":"validation"}'::jsonb),
    ('oas2-discriminator', 'error', 'validation', 'schemas', 'Schemas', 'discriminators are used correctly in schemas', 'When using polymorphism, a discriminator should also be provided to allow tools to understand how to compose your models when generating code. Add a correct discriminator.', '$', '{"category":{"description":"Schemas are how request bodies and response payloads are defined. They define the data going in and the data flowing out of an operation. These rules check for structural validity, checking types, checking required fields and validating correct use of structures.","id":"schemas","name":"Schemas"},"description":"discriminators are used correctly in schemas","given":"$","howToFix":"When using polymorphism, a discriminator should also be provided to allow tools to understand how to compose your models when generating code. Add a correct discriminator.","id":"oas2-discriminator","resolved":true,"severity":"error","then":{"function":"oasDiscriminator"},"type":"validation"}'::jsonb),
    ('oas2-host-not-example', 'warn', 'style', 'information', 'Contract Information', 'Host URL should not point at example.com', 'Remove ''example.com'' from the host URL, it''s not going to work.', '$.host', '{"category":{"description":"The info object contains licencing, contact, authorship details and more. Checks to confirm required details have been completed.","id":"information","name":"Contract Information"},"description":"Host URL should not point at example.com","given":"$.host","howToFix":"Remove ''example.com'' from the host URL, it''s not going to work.","id":"oas2-host-not-example","severity":"warn","then":{"function":"pattern","functionOptions":{"notMatch":"example\\.com"}},"type":"style"}'::jsonb),
    ('oas2-host-trailing-slash', 'warn', 'style', 'information', 'Contract Information', 'Host URL should not contain a trailing slash', 'Remove the trailing slash from the host URL. This may cause some tools to incorrectly add a double slash to paths.', '$.host', '{"category":{"description":"The info object contains licencing, contact, authorship details and more. Checks to confirm required details have been completed.","id":"information","name":"Contract Information"},"description":"Host URL should not contain a trailing slash","given":"$.host","howToFix":"Remove the trailing slash from the host URL. This may cause some tools to incorrectly add a double slash to paths.","id":"oas2-host-trailing-slash","severity":"warn","then":{"function":"pattern","functionOptions":{"notMatch":"/$"}},"type":"style"}'::jsonb),
    ('oas2-oneOf', 'error', 'validation', 'schemas', 'Schemas', '`oneOf` was introduced in OpenAPI 3.0, cannot be used un OpenAPI 2 specs', 'You can''t use ''oneOf'' in Swagger/OpenAPI 2 specs. It was added in version 3. You have to remove it', '$', '{"category":{"description":"Schemas are how request bodies and response payloads are defined. They define the data going in and the data flowing out of an operation. These rules check for structural validity, checking types, checking required fields and validating correct use of structures.","id":"schemas","name":"Schemas"},"description":"`oneOf` was introduced in OpenAPI 3.0, cannot be used un OpenAPI 2 specs","given":"$","howToFix":"You can''t use ''oneOf'' in Swagger/OpenAPI 2 specs. It was added in version 3. You have to remove it","id":"oas2-oneOf","severity":"error","then":{"function":"oasPolymorphicOneOf"},"type":"validation"}'::jsonb),
    ('oas2-operation-formData-consume-check', 'warn', 'validation', 'operations', 'Operations', 'Operations with `in: formData` parameter must include `application/x-www-form-urlencoded` or `multipart/form-data` in their `consumes` property.', 'When using ''formData'', the parameter must include the correct mime-types. Make sure you use ''application/x-www-form-urlencoded'' or ''multipart/form-data'' as the ''consumes'' value in your parameter.', '$', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"Operations with `in: formData` parameter must include `application/x-www-form-urlencoded` or `multipart/form-data` in their `consumes` property.","given":"$","howToFix":"When using ''formData'', the parameter must include the correct mime-types. Make sure you use ''application/x-www-form-urlencoded'' or ''multipart/form-data'' as the ''consumes'' value in your parameter.","id":"oas2-operation-formData-consume-check","resolved":true,"severity":"warn","then":{"function":"oasOpFormDataConsumeCheck"},"type":"validation"}'::jsonb),
    ('oas2-operation-security-defined', 'error', 'validation', 'security', 'Security', '`security` values must match a scheme defined in securityDefinitions', 'When defining security definitions for operations, you need to ensure they match the globally defined security schemes. Check $.securityDefinitions to make sure your values align.', '$', '{"category":{"description":"Security plays a central role in RESTful APIs. These rules make sure that the correct definitions have been used and put in the right places.","id":"security","name":"Security"},"description":"`security` values must match a scheme defined in securityDefinitions","given":"$","howToFix":"When defining security definitions for operations, you need to ensure they match the globally defined security schemes. Check $.securityDefinitions to make sure your values align.","id":"oas2-operation-security-defined","resolved":true,"severity":"error","then":{"function":"oas2OpSecurityDefined"},"type":"validation"}'::jsonb),
    ('oas2-parameter-description', 'warn', 'style', 'descriptions', 'Descriptions', 'Parameter description checks', 'All parameters should have a description. Descriptions are critical to understanding how an API works correctly. Please add a description to all parameters.', '$', '{"category":{"description":"Documentation is really important, in OpenAPI, just about everything can and should have a description. This set of rules checks for absent descriptions, poor quality descriptions (copy/paste), or short descriptions.","id":"descriptions","name":"Descriptions"},"description":"Parameter description checks","given":"$","howToFix":"All parameters should have a description. Descriptions are critical to understanding how an API works correctly. Please add a description to all parameters.","id":"oas2-parameter-description","resolved":true,"severity":"warn","then":{"function":"oasParamDescriptions"},"type":"style"}'::jsonb),
    ('oas2-schema', 'error', 'validation', 'validation', 'Validation', 'OpenAPI 2 specification is invalid', 'The schema isn''t valid Swagger/OpenAPI 2. Check the errors for more details', '$', '{"category":{"description":"Validation rules make sure that certain characters or patterns have not been used that may cause issues when rendering in different types of applications.","id":"validation","name":"Validation"},"description":"OpenAPI 2 specification is invalid","given":"$","howToFix":"The schema isn''t valid Swagger/OpenAPI 2. Check the errors for more details","id":"oas2-schema","severity":"error","then":{"function":"oasDocumentSchema"},"type":"validation"}'::jsonb),
    ('oas2-unused-definition', 'warn', 'validation', 'schemas', 'Schemas', 'Check for unused definitions and bad references', 'Orphaned components are not used by anything. You might have plans to use them later, or they could be older schemas that never got cleaned up. A clean spec is a happy spec. Prune your orphaned components.', '$', '{"category":{"description":"Schemas are how request bodies and response payloads are defined. They define the data going in and the data flowing out of an operation. These rules check for structural validity, checking types, checking required fields and validating correct use of structures.","id":"schemas","name":"Schemas"},"description":"Check for unused definitions and bad references","given":"$","howToFix":"Orphaned components are not used by anything. You might have plans to use them later, or they could be older schemas that never got cleaned up. A clean spec is a happy spec. Prune your orphaned components.","id":"oas2-unused-definition","severity":"warn","then":{"function":"oasUnusedComponent"},"type":"validation"}'::jsonb),
    ('oas3-api-servers', 'warn', 'validation', 'validation', 'Validation', 'Check for valid API servers definition', 'Ensure server URIs are correct and valid, check the schemes, ensure descriptions are complete.', '$', '{"category":{"description":"Validation rules make sure that certain characters or patterns have not been used that may cause issues when rendering in different types of applications.","id":"validation","name":"Validation"},"description":"Check for valid API servers definition","given":"$","howToFix":"Ensure server URIs are correct and valid, check the schemes, ensure descriptions are complete.","id":"oas3-api-servers","severity":"warn","then":{"function":"oasAPIServers"},"type":"validation"}'::jsonb),
    ('oas3-example-external-check', 'warn', 'validation', 'examples', 'Examples', 'Examples cannot use both `value` and `externalValue` together.', 'Examples are critical for consumers to be able to understand schemas and models defined by the spec. Without examples, developers can''t understand the type of data the API will return in real life. Examples are turned into mocks and can provide a rich testing capability for APIs. Add detailed examples everywhere!', '$', '{"category":{"description":"Examples help consumers understand how API calls should look. They are really important for automated tooling for mocking and testing. These rules check examples have been added to component schemas, parameters and operations. These rules also check that examples match the schema and types provided.","id":"examples","name":"Examples"},"description":"Examples cannot use both `value` and `externalValue` together.","given":"$","howToFix":"Examples are critical for consumers to be able to understand schemas and models defined by the spec. Without examples, developers can''t understand the type of data the API will return in real life. Examples are turned into mocks and can provide a rich testing capability for APIs. Add detailed examples everywhere!","id":"oas3-example-external-check","severity":"warn","then":{"function":"oasExampleExternal"},"type":"validation"}'::jsonb),
    ('oas3-host-not-example', 'warn', 'style', 'information', 'Contract Information', 'Server URL should not point at example.com', 'Remove ''example.com from the ''servers'' URL, it''s not going to work.', '$.servers[*].url', '{"category":{"description":"The info object contains licencing, contact, authorship details and more. Checks to confirm required details have been completed.","id":"information","name":"Contract Information"},"description":"Server URL should not point at example.com","given":"$.servers[*].url","howToFix":"Remove ''example.com from the ''servers'' URL, it''s not going to work.","id":"oas3-host-not-example","severity":"warn","then":{"function":"pattern","functionOptions":{"notMatch":"example\\.com"}},"type":"style"}'::jsonb),
    ('oas3-missing-example', 'warn', 'validation', 'examples', 'Examples', 'Ensure everything that can have an example, contains one', 'Examples are critical for consumers to be able to understand schemas and models defined by the spec. Without examples, developers can''t understand the type of data the API will return in real life. Examples are turned into mocks and can provide a rich testing capability for APIs. Add detailed examples everywhere!', '$', '{"category":{"description":"Examples help consumers understand how API calls should look. They are really important for automated tooling for mocking and testing. These rules check examples have been added to component schemas, parameters and operations. These rules also check that examples match the schema and types provided.","id":"examples","name":"Examples"},"description":"Ensure everything that can have an example, contains one","given":"$","howToFix":"Examples are critical for consumers to be able to understand schemas and models defined by the spec. Without examples, developers can''t understand the type of data the API will return in real life. Examples are turned into mocks and can provide a rich testing capability for APIs. Add detailed examples everywhere!","id":"oas3-missing-example","severity":"warn","then":{"function":"oasExampleMissing"},"type":"validation"}'::jsonb),
    ('oas3-no-$ref-siblings', 'error', 'validation', 'schemas', 'Schemas', '`$ref` values cannot be placed next to other properties, except `description` and `summary`', '$ref values must not be placed next to sibling nodes, except `description` and `summary` nodes.  This is wrong. remove all additional siblings!', '$', '{"category":{"description":"Schemas are how request bodies and response payloads are defined. They define the data going in and the data flowing out of an operation. These rules check for structural validity, checking types, checking required fields and validating correct use of structures.","id":"schemas","name":"Schemas"},"description":"`$ref` values cannot be placed next to other properties, except `description` and `summary`","given":"$","howToFix":"$ref values must not be placed next to sibling nodes, except `description` and `summary` nodes.  This is wrong. remove all additional siblings!","id":"oas3-no-$ref-siblings","severity":"error","then":{"function":"oasRefSiblings"},"type":"validation"}'::jsonb),
    ('oas3-operation-security-defined', 'error', 'validation', 'security', 'Security', '`security` values must match a scheme defined in components.securitySchemes', 'When defining security values for operations, you need to ensure they match the globally defined security schemes. Check $.components.securitySchemes to make sure your values align.', '$', '{"category":{"description":"Security plays a central role in RESTful APIs. These rules make sure that the correct definitions have been used and put in the right places.","id":"security","name":"Security"},"description":"`security` values must match a scheme defined in components.securitySchemes","given":"$","howToFix":"When defining security values for operations, you need to ensure they match the globally defined security schemes. Check $.components.securitySchemes to make sure your values align.","id":"oas3-operation-security-defined","resolved":true,"severity":"error","then":{"function":"oasOpSecurityDefined","functionOptions":{"schemesPath":"$.components.securitySchemes"}},"type":"validation"}'::jsonb),
    ('oas3-parameter-description', 'warn', 'style', 'descriptions', 'Descriptions', 'Parameter description checks', 'All parameters should have a description. Descriptions are critical to understanding how an API works correctly. Please add a description to all parameters.', '$', '{"category":{"description":"Documentation is really important, in OpenAPI, just about everything can and should have a description. This set of rules checks for absent descriptions, poor quality descriptions (copy/paste), or short descriptions.","id":"descriptions","name":"Descriptions"},"description":"Parameter description checks","given":"$","howToFix":"All parameters should have a description. Descriptions are critical to understanding how an API works correctly. Please add a description to all parameters.","id":"oas3-parameter-description","resolved":true,"severity":"warn","then":{"function":"oasParamDescriptions"},"type":"style"}'::jsonb),
    ('oas3-schema', 'error', 'validation', 'schemas', 'Schemas', 'OpenAPI 3+ specification is invalid', 'The schema isn''t valid OpenAPI 3. Check the errors for more details', '$', '{"category":{"description":"Schemas are how request bodies and response payloads are defined. They define the data going in and the data flowing out of an operation. These rules check for structural validity, checking types, checking required fields and validating correct use of structures.","id":"schemas","name":"Schemas"},"description":"OpenAPI 3+ specification is invalid","given":"$","howToFix":"The schema isn''t valid OpenAPI 3. Check the errors for more details","id":"oas3-schema","severity":"error","then":{"function":"oasDocumentSchema"},"type":"validation"}'::jsonb),
    ('oas3-server-trailing-slash', 'warn', 'style', 'information', 'Contract Information', 'server URL should not contain a trailing slash', 'Remove the trailing slash from the server URL. This may cause some tools to incorrectly add a double slash to paths.', '$.servers[*]', '{"category":{"description":"The info object contains licencing, contact, authorship details and more. Checks to confirm required details have been completed.","id":"information","name":"Contract Information"},"description":"server URL should not contain a trailing slash","given":"$.servers[*]","howToFix":"Remove the trailing slash from the server URL. This may cause some tools to incorrectly add a double slash to paths.","id":"oas3-server-trailing-slash","severity":"warn","then":{"field":"url","function":"pattern","functionOptions":{"notMatch":"/$"}},"type":"style"}'::jsonb),
    ('oas3-unused-component', 'warn', 'validation', 'schemas', 'Schemas', 'Check for unused components and bad references', 'Unused components / definitions are generally the result of the OpenAPI contract being updated without considering references. Another reference could have been updated, or an operation changed that no longer references this component. Remove this component from the spec, or re-link to it from another component or operation to fix the problem.', '$', '{"category":{"description":"Schemas are how request bodies and response payloads are defined. They define the data going in and the data flowing out of an operation. These rules check for structural validity, checking types, checking required fields and validating correct use of structures.","id":"schemas","name":"Schemas"},"description":"Check for unused components and bad references","given":"$","howToFix":"Unused components / definitions are generally the result of the OpenAPI contract being updated without considering references. Another reference could have been updated, or an operation changed that no longer references this component. Remove this component from the spec, or re-link to it from another component or operation to fix the problem.","id":"oas3-unused-component","severity":"warn","then":{"function":"oasUnusedComponent"},"type":"validation"}'::jsonb),
    ('oas3-valid-schema-example', 'warn', 'validation', 'examples', 'Examples', 'If an example has been used, check the schema is valid', 'Examples are critical for consumers to be able to understand schemas and models defined by the spec. Without examples, developers can''t understand the type of data the API will return in real life. Examples are turned into mocks and can provide a rich testing capability for APIs. Add detailed examples everywhere!', '$', '{"category":{"description":"Examples help consumers understand how API calls should look. They are really important for automated tooling for mocking and testing. These rules check examples have been added to component schemas, parameters and operations. These rules also check that examples match the schema and types provided.","id":"examples","name":"Examples"},"description":"If an example has been used, check the schema is valid","given":"$","howToFix":"Examples are critical for consumers to be able to understand schemas and models defined by the spec. Without examples, developers can''t understand the type of data the API will return in real life. Examples are turned into mocks and can provide a rich testing capability for APIs. Add detailed examples everywhere!","id":"oas3-valid-schema-example","severity":"warn","then":{"function":"oasExampleSchema"},"type":"validation"}'::jsonb),
    ('openapi-tags', 'warn', 'validation', 'tags', 'Tags', 'Top level spec `tags` must not be empty, and must be an array', 'Add a global ''tags'' object to the root of the spec. Global tags are used by operations to define taxonomy and information architecture by tools. Tags generate navigation in documentation as well as modules in code generation.', '$', '{"category":{"description":"Tags are used as meta-data for operations. They are mainly used by tooling as a taxonomy mechanism to build navigation, search and more. Tags are important as they help consumers navigate the contract when using documentation, testing, code generation or analysis tools.","id":"tags","name":"Tags"},"description":"Top level spec `tags` must not be empty, and must be an array","given":"$","howToFix":"Add a global ''tags'' object to the root of the spec. Global tags are used by operations to define taxonomy and information architecture by tools. Tags generate navigation in documentation as well as modules in code generation.","id":"openapi-tags","resolved":true,"severity":"warn","then":{"field":"tags","function":"schema","functionOptions":{"forceValidation":true,"schema":{"items":{"minItems":1,"type":"object"},"type":"array","uniqueItems":true}}},"type":"validation"}'::jsonb),
    ('openapi-tags-alphabetical', 'info', 'style', 'tags', 'Tags', 'Tags must be in alphabetical order', 'The global tags defined in the spec are not listed alphabetically, Everything is much better when data is pre-sorted. Order the tags in alphabetical sequence.', '$.tags', '{"category":{"description":"Tags are used as meta-data for operations. They are mainly used by tooling as a taxonomy mechanism to build navigation, search and more. Tags are important as they help consumers navigate the contract when using documentation, testing, code generation or analysis tools.","id":"tags","name":"Tags"},"description":"Tags must be in alphabetical order","given":"$.tags","howToFix":"The global tags defined in the spec are not listed alphabetically, Everything is much better when data is pre-sorted. Order the tags in alphabetical sequence.","id":"openapi-tags-alphabetical","resolved":true,"severity":"info","then":{"function":"alphabetical","functionOptions":{"keyedBy":"name"}},"type":"style"}'::jsonb),
    ('operation-4xx-response', 'warn', 'validation', 'operations', 'Operations', 'Make sure operations return at least one `4xx` error response to help with bad requests', 'Make sure each operation defines at least one 4xx error response. 4xx Errors are used to inform clients they are using the API incorrectly, with bad input, or malformed requests. An API with no errorsdefined is really hard to navigate.', '$', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"Make sure operations return at least one `4xx` error response to help with bad requests","given":"$","howToFix":"Make sure each operation defines at least one 4xx error response. 4xx Errors are used to inform clients they are using the API incorrectly, with bad input, or malformed requests. An API with no errorsdefined is really hard to navigate.","id":"operation-4xx-response","resolved":true,"severity":"warn","then":{"function":"oasOpErrorResponse"},"type":"validation"}'::jsonb),
    ('operation-description', 'warn', 'validation', 'descriptions', 'Descriptions', 'Operation description checks', 'All operations must have a description. Descriptions explain how the operation works, and how users should use it and what to expect. Operation descriptions make up the bulk of API documentation. so please, add a description!', '$', '{"category":{"description":"Documentation is really important, in OpenAPI, just about everything can and should have a description. This set of rules checks for absent descriptions, poor quality descriptions (copy/paste), or short descriptions.","id":"descriptions","name":"Descriptions"},"description":"Operation description checks","given":"$","howToFix":"All operations must have a description. Descriptions explain how the operation works, and how users should use it and what to expect. Operation descriptions make up the bulk of API documentation. so please, add a description!","id":"operation-description","resolved":true,"severity":"warn","then":{"function":"oasDescriptions","functionOptions":{"minWords":"1"}},"type":"validation"}'::jsonb),
    ('operation-operationId', 'error', 'validation', 'operations', 'Operations', 'Every operation must contain an `operationId`.', 'Every single operation needs an operationId. It''s a critical requirement to be able to identify each individual operation uniquely. Please add an operationId to the operation.', '$', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"Every operation must contain an `operationId`.","given":"$","howToFix":"Every single operation needs an operationId. It''s a critical requirement to be able to identify each individual operation uniquely. Please add an operationId to the operation.","id":"operation-operationId","severity":"error","then":{"function":"oasOpId"},"type":"validation"}'::jsonb),
    ('operation-operationId-unique', 'error', 'validation', 'operations', 'Operations', 'Every operation must have unique `operationId`.', 'An operationId needs to be unique, there can''t be any duplicates in the document, you can''t re-use them. Make sure the ID used for this operation is unique.', '$.paths', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"Every operation must have unique `operationId`.","given":"$.paths","howToFix":"An operationId needs to be unique, there can''t be any duplicates in the document, you can''t re-use them. Make sure the ID used for this operation is unique.","id":"operation-operationId-unique","resolved":true,"severity":"error","then":{"function":"oasOpIdUnique"},"type":"validation"}'::jsonb),
    ('operation-operationId-valid-in-url', 'error', 'validation', 'operations', 'Operations', 'OperationId must use URL friendly characters', 'An operationId is critical to correct code generation and operation identification. The operationId should really be designed in a way to make it friendly when used as part of a URL. Remove non-standard URL characters.', '$.paths[*][*]', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"OperationId must use URL friendly characters","given":"$.paths[*][*]","howToFix":"An operationId is critical to correct code generation and operation identification. The operationId should really be designed in a way to make it friendly when used as part of a URL. Remove non-standard URL characters.","id":"operation-operationId-valid-in-url","resolved":true,"severity":"error","then":{"field":"operationId","function":"pattern","functionOptions":{"match":"^[A-Za-z0-9-._~:/?#\\[\\]@!\\$&''()*+,;=]*$"}},"type":"validation"}'::jsonb),
    ('operation-parameters', 'error', 'validation', 'operations', 'Operations', 'Operation parameters are unique and non-repeating.', 'Make sure that all the operation parameters are unique and non-repeating, don''t duplicate names, don''tre-use parameter names in the same operation.', '$.paths', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"Operation parameters are unique and non-repeating.","given":"$.paths","howToFix":"Make sure that all the operation parameters are unique and non-repeating, don''t duplicate names, don''tre-use parameter names in the same operation.","id":"operation-parameters","resolved":true,"severity":"error","then":{"function":"oasOpParams"},"type":"validation"}'::jsonb),
    ('operation-singular-tag', 'warn', 'validation', 'tags', 'Tags', 'Operation cannot have more than a single tag defined', 'Using tags as ''groups'' for operations makes a lot of sense. It stops making sense when multiple tags are used for an operation. Reduce tag count down to one for the operation.', '$', '{"category":{"description":"Tags are used as meta-data for operations. They are mainly used by tooling as a taxonomy mechanism to build navigation, search and more. Tags are important as they help consumers navigate the contract when using documentation, testing, code generation or analysis tools.","id":"tags","name":"Tags"},"description":"Operation cannot have more than a single tag defined","given":"$","howToFix":"Using tags as ''groups'' for operations makes a lot of sense. It stops making sense when multiple tags are used for an operation. Reduce tag count down to one for the operation.","id":"operation-singular-tag","severity":"warn","then":{"function":"oasOpSingleTag"},"type":"validation"}'::jsonb),
    ('operation-success-response', 'warn', 'style', 'operations', 'Operations', 'Operation must have at least one `2xx` or a `3xx` response.', 'Make sure that your operation returns a ''success'' response via  2xx or 3xx response code. An API consumer will always expect a success response', '$', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"Operation must have at least one `2xx` or a `3xx` response.","given":"$","howToFix":"Make sure that your operation returns a ''success'' response via  2xx or 3xx response code. An API consumer will always expect a success response","id":"operation-success-response","resolved":true,"severity":"warn","then":{"field":"responses","function":"oasOpSuccessResponse"},"type":"style"}'::jsonb),
    ('operation-tag-defined', 'warn', 'validation', 'tags', 'Tags', 'Operation tags must be defined in global tags.', 'This tag has not been defined in the global scope, you should always ensure that any tags used in operations, are defined globally in the root ''tags'' definition.', '$', '{"category":{"description":"Tags are used as meta-data for operations. They are mainly used by tooling as a taxonomy mechanism to build navigation, search and more. Tags are important as they help consumers navigate the contract when using documentation, testing, code generation or analysis tools.","id":"tags","name":"Tags"},"description":"Operation tags must be defined in global tags.","given":"$","howToFix":"This tag has not been defined in the global scope, you should always ensure that any tags used in operations, are defined globally in the root ''tags'' definition.","id":"operation-tag-defined","resolved":true,"severity":"warn","then":{"function":"oasTagDefined"},"type":"validation"}'::jsonb),
    ('operation-tags', 'warn', 'validation', 'tags', 'Tags', 'Operation `tags` are missing/empty', 'Operations use tags to define the domain(s) they are apart of. Generally a single tag per operation is used, however some tools use multiple tags. The point is that you need tags! Add some tags to the operation that match the globally available ones.', '$', '{"category":{"description":"Tags are used as meta-data for operations. They are mainly used by tooling as a taxonomy mechanism to build navigation, search and more. Tags are important as they help consumers navigate the contract when using documentation, testing, code generation or analysis tools.","id":"tags","name":"Tags"},"description":"Operation `tags` are missing/empty","given":"$","howToFix":"Operations use tags to define the domain(s) they are apart of. Generally a single tag per operation is used, however some tools use multiple tags. The point is that you need tags! Add some tags to the operation that match the globally available ones.","id":"operation-tags","resolved":true,"severity":"warn","then":{"function":"oasOperationTags"},"type":"validation"}'::jsonb),
    ('path-declarations-must-exist', 'error', 'validation', 'operations', 'Operations', 'Path parameter declarations must not be empty ex. `/api/{}` is invalid', 'Paths define the endpoint for operations. Without paths, there is no API. You need to add ''paths'' to the root of the specification.', '$.paths', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"Path parameter declarations must not be empty ex. `/api/{}` is invalid","given":"$.paths","howToFix":"Paths define the endpoint for operations. Without paths, there is no API. You need to add ''paths'' to the root of the specification.","id":"path-declarations-must-exist","resolved":true,"severity":"error","then":{"function":"pattern","functionOptions":{"notMatch":"{}"}},"type":"validation"}'::jsonb),
    ('path-item-refs', 'warn', 'validation', 'operations', 'Operations', 'Operations within path items should not use $ref values. $ref is only valid directly on the path item object itself.', 'Operations within path items should not use $ref. If you need to reference a reusable definition, use $ref at the path item level instead', '$', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"Operations within path items should not use $ref values. $ref is only valid directly on the path item object itself.","given":"$","howToFix":"Operations within path items should not use $ref. If you need to reference a reusable definition, use $ref at the path item level instead","id":"path-item-refs","severity":"warn","then":{"function":"pathItemReferences"},"type":"validation"}'::jsonb),
    ('path-keys-no-trailing-slash', 'warn', 'validation', 'operations', 'Operations', 'Path must not end with a slash', 'Paths should not end with a trailing slash, it can confuse tooling and isn''t valid as a path Remove the trailing slash from the path.', '$.paths', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"Path must not end with a slash","given":"$.paths","howToFix":"Paths should not end with a trailing slash, it can confuse tooling and isn''t valid as a path Remove the trailing slash from the path.","id":"path-keys-no-trailing-slash","resolved":true,"severity":"warn","then":{"function":"pattern","functionOptions":{"notMatch":".+\\/$"}},"type":"validation"}'::jsonb),
    ('path-not-include-query', 'error', 'validation', 'operations', 'Operations', 'Path must not include query string', 'Query strings are defined as parameters for an operation, they should not be included in the path Please remove it and correctly define as a parameter.', '$.paths', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"Path must not include query string","given":"$.paths","howToFix":"Query strings are defined as parameters for an operation, they should not be included in the path Please remove it and correctly define as a parameter.","id":"path-not-include-query","resolved":true,"severity":"error","then":{"function":"pattern","functionOptions":{"notMatch":"\\?"}},"type":"validation"}'::jsonb),
    ('path-params', 'error', 'validation', 'operations', 'Operations', 'Path parameters must be defined and valid.', 'Path parameters need to match up with the parameters defined for the path, or in an operation that sits under that path. Make sure variable names match up and are defined correctly.', '$', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"Path parameters must be defined and valid.","given":"$","howToFix":"Path parameters need to match up with the parameters defined for the path, or in an operation that sits under that path. Make sure variable names match up and are defined correctly.","id":"path-params","resolved":true,"severity":"error","then":{"function":"oasPathParam"},"type":"validation"}'::jsonb),
    ('paths-kebab-case', 'warn', 'validation', 'operations', 'Operations', 'Path segments must only use kebab-case (no underscores or uppercase)', 'Path segments should not contain any uppercase letters, punctuation or underscores. The only valid way to separate words in a segment, is to use a hyphen ''-''. The elements that are violating the rule are highlighted in the violation description. These are the elements that need to change.', '$', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"Path segments must only use kebab-case (no underscores or uppercase)","given":"$","howToFix":"Path segments should not contain any uppercase letters, punctuation or underscores. The only valid way to separate words in a segment, is to use a hyphen ''-''. The elements that are violating the rule are highlighted in the violation description. These are the elements that need to change.","id":"paths-kebab-case","severity":"warn","then":{"function":"pathsKebabCase"},"type":"validation"}'::jsonb),
    ('post-response-success', 'warn', 'validation', 'operations', 'Operations', 'POST Operations should have a success response defined', 'Make sure your POST operations return a ''success'' response via 2xx or 3xx response code. ', '$.paths.*.post.responses', '{"category":{"description":"Operations are the core of the contract, they define paths and HTTP methods. These rules check operations have been well constructed, looks for operationId, parameter, schema and return types in depth.","id":"operations","name":"Operations"},"description":"POST Operations should have a success response defined","given":"$.paths.*.post.responses","howToFix":"Make sure your POST operations return a ''success'' response via 2xx or 3xx response code. ","id":"post-response-success","severity":"warn","then":{"function":"postResponseSuccess","functionOptions":{"properties":["2XX","3XX","200","201","202","204","205","206","207","208","226","300","301","302","303","304","305","306","307","308"]}},"type":"validation"}'::jsonb),
    ('tag-description', 'warn', 'validation', 'tags', 'Tags', 'Tag must have a description defined', 'Tags are used to group operations into meaningful domains. Without a description, how is anyone supposed to understand what the grouping means? Add a description to your global tag.', '$', '{"category":{"description":"Tags are used as meta-data for operations. They are mainly used by tooling as a taxonomy mechanism to build navigation, search and more. Tags are important as they help consumers navigate the contract when using documentation, testing, code generation or analysis tools.","id":"tags","name":"Tags"},"description":"Tag must have a description defined","given":"$","howToFix":"Tags are used to group operations into meaningful domains. Without a description, how is anyone supposed to understand what the grouping means? Add a description to your global tag.","id":"tag-description","resolved":true,"severity":"warn","then":{"function":"tagDescription"},"type":"validation"}'::jsonb),
    ('typed-enum', 'warn', 'validation', 'schemas', 'Schemas', 'Enum values must respect the specified type', 'Enum values lock down the number of variable inputs a parameter or schema can have. The problem here is that the Enum defined, does not match the specified type. Fix the type!', '$', '{"category":{"description":"Schemas are how request bodies and response payloads are defined. They define the data going in and the data flowing out of an operation. These rules check for structural validity, checking types, checking required fields and validating correct use of structures.","id":"schemas","name":"Schemas"},"description":"Enum values must respect the specified type","given":"$","howToFix":"Enum values lock down the number of variable inputs a parameter or schema can have. The problem here is that the Enum defined, does not match the specified type. Fix the type!","id":"typed-enum","resolved":true,"severity":"warn","then":{"function":"typedEnum"},"type":"validation"}'::jsonb)
;
-- vacuum_rules seed end

CREATE TABLE IF NOT EXISTS vacuum_issues (
    id BIGSERIAL PRIMARY KEY,
    api_spec_revision_id BIGINT NOT NULL REFERENCES api_spec_revisions(id) ON DELETE CASCADE,
    rule_id TEXT NOT NULL REFERENCES vacuum_rules(rule_id),
    message TEXT NOT NULL,
    json_path TEXT NOT NULL,
    range_pos INTEGER[] NOT NULL CHECK (cardinality(range_pos) = 4),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS vacuum_issues_api_spec_revision_rule_idx
    ON vacuum_issues(api_spec_revision_id, rule_id);
CREATE INDEX IF NOT EXISTS vacuum_issues_rule_id_idx ON vacuum_issues(rule_id);

CREATE TABLE IF NOT EXISTS api_spec_dependencies (
    api_spec_revision_id BIGINT NOT NULL REFERENCES api_spec_revisions(id) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    UNIQUE (api_spec_revision_id, file_path)
);

CREATE TABLE IF NOT EXISTS spec_artifacts (
    id BIGSERIAL PRIMARY KEY,
    api_spec_revision_id BIGINT NOT NULL UNIQUE REFERENCES api_spec_revisions(id) ON DELETE CASCADE,
    spec_json JSONB NOT NULL,
    spec_yaml TEXT NOT NULL,
    etag TEXT NOT NULL,
    size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS endpoint_index (
    id BIGSERIAL PRIMARY KEY,
    api_spec_revision_id BIGINT NOT NULL REFERENCES api_spec_revisions(id) ON DELETE CASCADE,
    method TEXT NOT NULL,
    path TEXT NOT NULL,
    operation_id TEXT,
    summary TEXT,
    deprecated BOOLEAN NOT NULL DEFAULT FALSE,
    raw_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (api_spec_revision_id, method, path)
);

CREATE INDEX IF NOT EXISTS endpoint_index_api_spec_revision_idx ON endpoint_index(api_spec_revision_id);
CREATE INDEX IF NOT EXISTS endpoint_index_lookup_idx ON endpoint_index(api_spec_revision_id, method, path);
CREATE INDEX IF NOT EXISTS endpoint_index_operation_lookup_idx
    ON endpoint_index(api_spec_revision_id, operation_id)
    WHERE operation_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS spec_changes (
    id BIGSERIAL PRIMARY KEY,
    api_spec_id BIGINT NOT NULL REFERENCES api_specs(id) ON DELETE CASCADE,
    from_api_spec_revision_id BIGINT REFERENCES api_spec_revisions(id) ON DELETE SET NULL,
    to_api_spec_revision_id BIGINT NOT NULL UNIQUE REFERENCES api_spec_revisions(id) ON DELETE CASCADE,
    change_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS spec_changes_api_spec_created_idx ON spec_changes(api_spec_id, created_at DESC);

CREATE TABLE IF NOT EXISTS delivery_attempts (
    id BIGSERIAL PRIMARY KEY,
    subscription_id BIGINT NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
    api_spec_id BIGINT NOT NULL REFERENCES api_specs(id) ON DELETE CASCADE,
    ingest_event_id BIGINT NOT NULL REFERENCES ingest_events(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL CHECK (event_type IN ('spec.updated.full', 'spec.updated.diff')),
    attempt_no INTEGER NOT NULL CHECK (attempt_no > 0),
    status TEXT NOT NULL CHECK (status IN ('pending', 'retry_scheduled', 'succeeded', 'failed')),
    response_code INTEGER,
    error TEXT NOT NULL DEFAULT '',
    next_retry_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (subscription_id, api_spec_id, ingest_event_id, event_type, attempt_no)
);

CREATE INDEX IF NOT EXISTS delivery_attempts_retry_idx ON delivery_attempts(status, next_retry_at);
CREATE INDEX IF NOT EXISTS delivery_attempts_subscription_idx ON delivery_attempts(subscription_id, created_at DESC);
